insert into YFS_REGION (REGION_KEY,REGION_SCHEMA_KEY,REGION_NAME,REGION_DESCRIPTION,PARENT_REGION_KEY,REGION_LEVEL_NAME,CAN_AGGREGATE,CREATEUSERID, MODIFYUSERID, CREATEPROGID, MODIFYPROGID, LOCKID) VALUES
('NT','ALL_CA','NT','NT','CAN','State','Y','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT18','ALL_CA','Hay River','Hay River','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT19','ALL_CA','Ulukhaktok','Ulukhaktok','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT20','ALL_CA','Aklavik','Aklavik','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT21','ALL_CA','Enterprise','Enterprise','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT22','ALL_CA','Fort Liard','Fort Liard','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT23','ALL_CA','Tsiigehtchic','Tsiigehtchic','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT24','ALL_CA','Inuvik','Inuvik','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT25','ALL_CA','Behchoko','Behchoko','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT26','ALL_CA','Whati','Whati','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT27','ALL_CA','Tuktoyaktuk','Tuktoyaktuk','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT28','ALL_CA','Lutselk''e','Lutselk''e','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT1','ALL_CA','Gameti','Gameti','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT2','ALL_CA','Fort Good Hope','Fort Good Hope','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT3','ALL_CA','Yellowknife','Yellowknife','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT4','ALL_CA','Norman Wells','Norman Wells','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT5','ALL_CA','Trout Lake','Trout Lake','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT6','ALL_CA','Sachs Harbour','Sachs Harbour','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT7','ALL_CA','Colville Lake','Colville Lake','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT8','ALL_CA','Paulatuk','Paulatuk','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT9','ALL_CA','Wekweti','Wekweti','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT10','ALL_CA','Fort McPherson','Fort McPherson','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT11','ALL_CA','Fort Simpson','Fort Simpson','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT12','ALL_CA','Fort Smith','Fort Smith','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT13','ALL_CA','Wrigley','Wrigley','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT14','ALL_CA','Deline','Deline','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT15','ALL_CA','Fort Providence','Fort Providence','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT16','ALL_CA','Fort Resolution','Fort Resolution','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NT17','ALL_CA','Tulita','Tulita','NT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0);
commit;
insert into YFS_REGION (REGION_KEY,REGION_SCHEMA_KEY,REGION_NAME,REGION_DESCRIPTION,PARENT_REGION_KEY,REGION_LEVEL_NAME,CAN_AGGREGATE,CREATEUSERID, MODIFYUSERID, CREATEPROGID, MODIFYPROGID, LOCKID) VALUES
('NL','ALL_CA','NL','NL','CAN','State','Y','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL1','ALL_CA','Barachois Brook','Barachois Brook','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL2','ALL_CA','Bartletts Harbour','Bartletts Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL3','ALL_CA','Bauline','Bauline','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL4','ALL_CA','Bishops Falls','Bishops Falls','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL5','ALL_CA','Bridgeport','Bridgeport','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL6','ALL_CA','Cormack','Cormack','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL7','ALL_CA','Eddies Cove','Eddies Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL8','ALL_CA','Eddies Cove West','Eddies Cove West','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL9','ALL_CA','Fortune','Fortune','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL10','ALL_CA','Goulds','Goulds','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL11','ALL_CA','Harbour Breton','Harbour Breton','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL12','ALL_CA','Horwood','Horwood','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL13','ALL_CA','Kings Cove','Kings Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL14','ALL_CA','Kippens','Kippens','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL15','ALL_CA','Placentia','Placentia','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL16','ALL_CA','Rencontre East','Rencontre East','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL17','ALL_CA','Roberts Arm','Roberts Arm','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL18','ALL_CA','Shalloway Cove','Shalloway Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL19','ALL_CA','Southern Bay','Southern Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL20','ALL_CA','Triton','Triton','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL21','ALL_CA','Twillingate','Twillingate','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL22','ALL_CA','Little Hearts Ease','Little Hearts Ease','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL23','ALL_CA','Hampden','Hampden','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL24','ALL_CA','Head Bay d''Espoir','Head Bay d''Espoir','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL25','ALL_CA','Grand Falls-Windsor','Grand Falls-Windsor','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL26','ALL_CA','Conception Bay South','Conception Bay South','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL27','ALL_CA','Conche','Conche','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL28','ALL_CA','Eastport','Eastport','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL29','ALL_CA','Baine Harbour','Baine Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL30','ALL_CA','Gander Bay','Gander Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL31','ALL_CA','Outer Cove','Outer Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL32','ALL_CA','Botwood','Botwood','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL33','ALL_CA','North West Brook','North West Brook','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL34','ALL_CA','Dildo','Dildo','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL35','ALL_CA','Monkstown','Monkstown','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL36','ALL_CA','Frederickton','Frederickton','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL37','ALL_CA','Jerseyside','Jerseyside','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL38','ALL_CA','Long Harbour','Long Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL39','ALL_CA','Cappahayden','Cappahayden','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL40','ALL_CA','Makinsons','Makinsons','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL41','ALL_CA','Grand Beach','Grand Beach','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL42','ALL_CA','Embree','Embree','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL43','ALL_CA','Wild Cove Wb','Wild Cove Wb','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL44','ALL_CA','Carters Cove','Carters Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL45','ALL_CA','Trinity BB','Trinity BB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL46','ALL_CA','Sunnyside','Sunnyside','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL47','ALL_CA','Petite Forte','Petite Forte','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL48','ALL_CA','St Anthony East','St Anthony East','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL49','ALL_CA','Stoneville','Stoneville','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL50','ALL_CA','Norris Arm','Norris Arm','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL51','ALL_CA','Lawn','Lawn','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL52','ALL_CA','Pynn''s Brook','Pynn''s Brook','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL53','ALL_CA','Broad Cove Bdv','Broad Cove Bdv','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL54','ALL_CA','Brigus','Brigus','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL55','ALL_CA','Bellevue','Bellevue','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL56','ALL_CA','Port Rexton','Port Rexton','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL57','ALL_CA','Duntara','Duntara','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL58','ALL_CA','Badger','Badger','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL59','ALL_CA','Point Leamington','Point Leamington','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL60','ALL_CA','Little Bay PB','Little Bay PB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL61','ALL_CA','Woodstock','Woodstock','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL62','ALL_CA','St Lunaire-Griquet','St Lunaire-Griquet','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL63','ALL_CA','Cannings Cove','Cannings Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL64','ALL_CA','Red Head Cove','Red Head Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL65','ALL_CA','Port Albert','Port Albert','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL66','ALL_CA','Arnolds Cove','Arnolds Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL67','ALL_CA','Bell Island Front','Bell Island Front','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL68','ALL_CA','Buchans','Buchans','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL69','ALL_CA','Conne River','Conne River','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL70','ALL_CA','Cottlesville','Cottlesville','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL71','ALL_CA','Cottrells Cove','Cottrells Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL72','ALL_CA','Valley Pond','Valley Pond','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL73','ALL_CA','Harrys Harbour','Harrys Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL74','ALL_CA','Heart''s Desire','Heart''s Desire','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL75','ALL_CA','Hopedale','Hopedale','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL76','ALL_CA','Lumsden','Lumsden','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL77','ALL_CA','Moretons Harbour','Moretons Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL78','ALL_CA','Mud Lake','Mud Lake','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL79','ALL_CA','Ochre Pit Cove','Ochre Pit Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL80','ALL_CA','Paradise','Paradise','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL81','ALL_CA','Portugal Cove-St Philips','Portugal Cove-St Philips','N','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL82','ALL_CA','Ramea','Ramea','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL83','ALL_CA','Renews','Renews','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL84','ALL_CA','Sandy Cove','Sandy Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL85','ALL_CA','Torbay','Torbay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL86','ALL_CA','Hermitage','Hermitage','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL87','ALL_CA','Branch','Branch','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL88','ALL_CA','Stag Harbour','Stag Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL89','ALL_CA','Epworth','Epworth','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL90','ALL_CA','Corner Brook','Corner Brook','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL91','ALL_CA','Cavendish','Cavendish','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL92','ALL_CA','Main Point','Main Point','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL93','ALL_CA','Spaniards Bay','Spaniards Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL94','ALL_CA','Hillview','Hillview','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL95','ALL_CA','Campbellton','Campbellton','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL96','ALL_CA','Colinet','Colinet','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL97','ALL_CA','Sallys Cove','Sallys Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL98','ALL_CA','Pollards Point','Pollards Point','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL99','ALL_CA','Bay l''Argent','Bay l''Argent','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL100','ALL_CA','Cartwright','Cartwright','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL101','ALL_CA','Cartyville','Cartyville','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL102','ALL_CA','Marystown','Marystown','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL103','ALL_CA','St Brides','St Brides','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL104','ALL_CA','Bay Bulls','Bay Bulls','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL105','ALL_CA','Grey River','Grey River','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL106','ALL_CA','Trepassey','Trepassey','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL107','ALL_CA','Victoria Cove','Victoria Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL108','ALL_CA','Grand Bay East','Grand Bay East','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL109','ALL_CA','Brighton','Brighton','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL110','ALL_CA','Glovertown','Glovertown','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL111','ALL_CA','Peterview','Peterview','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL112','ALL_CA','St Chads','St Chads','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL113','ALL_CA','Woodfords','Woodfords','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL114','ALL_CA','Dunville','Dunville','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL115','ALL_CA','Tors Cove','Tors Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL116','ALL_CA','Bird Cove','Bird Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL117','ALL_CA','Red Harbour PB','Red Harbour PB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL118','ALL_CA','Bell Island','Bell Island','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL119','ALL_CA','Boat Harbour West','Boat Harbour West','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL120','ALL_CA','Bonne Bay Pond','Bonne Bay Pond','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL121','ALL_CA','Buchans Junction','Buchans Junction','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL122','ALL_CA','Bunyans Cove','Bunyans Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL123','ALL_CA','Chance Cove','Chance Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL124','ALL_CA','Freshwater PB','Freshwater PB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL125','ALL_CA','Greenspond','Greenspond','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL126','ALL_CA','Harbour Grace South','Harbour Grace South','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL127','ALL_CA','Jobs Cove','Jobs Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL128','ALL_CA','Kilbride','Kilbride','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL129','ALL_CA','New Perlican','New Perlican','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL130','ALL_CA','Pacquet','Pacquet','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL131','ALL_CA','Pasadena','Pasadena','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL132','ALL_CA','Raleigh','Raleigh','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL133','ALL_CA','South River','South River','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL134','ALL_CA','Whitbourne','Whitbourne','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL135','ALL_CA','Little Harbour East PB','Little Harbour East PB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL136','ALL_CA','Bloomfield','Bloomfield','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL137','ALL_CA','Green Island Cove','Green Island Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL138','ALL_CA','Islington','Islington','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL139','ALL_CA','Melrose','Melrose','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL140','ALL_CA','Clarenville','Clarenville','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL141','ALL_CA','Pound Cove','Pound Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL142','ALL_CA','Postville','Postville','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL143','ALL_CA','Gambo South','Gambo South','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL144','ALL_CA','Wings Point','Wings Point','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL145','ALL_CA','English Harbour East','English Harbour East','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL146','ALL_CA','Lark Harbour','Lark Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL147','ALL_CA','Bellburns','Bellburns','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL148','ALL_CA','Black Tickle','Black Tickle','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL149','ALL_CA','Croque','Croque','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL150','ALL_CA','Snooks Arm','Snooks Arm','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL151','ALL_CA','Hare Bay BB','Hare Bay BB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL152','ALL_CA','Makkovik','Makkovik','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL153','ALL_CA','Marys Harbour','Marys Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL154','ALL_CA','Marysvale','Marysvale','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL155','ALL_CA','St Brendans','St Brendans','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL156','ALL_CA','South Dildo','South Dildo','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL157','ALL_CA','South East Bight','South East Bight','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL158','ALL_CA','Nain','Nain','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL159','ALL_CA','Templeman','Templeman','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL160','ALL_CA','York Harbour','York Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL161','ALL_CA','Hickmans Harbour','Hickmans Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL162','ALL_CA','Colliers Riverhead','Colliers Riverhead','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL163','ALL_CA','Bay de Verde','Bay de Verde','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL164','ALL_CA','Keels','Keels','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL165','ALL_CA','Gooseberry Cove','Gooseberry Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL166','ALL_CA','Lewins Cove','Lewins Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL167','ALL_CA','Shea Heights','Shea Heights','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL168','ALL_CA','Chapel Arm','Chapel Arm','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL169','ALL_CA','Terrenceville','Terrenceville','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL170','ALL_CA','Wesleyville','Wesleyville','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL171','ALL_CA','L''Anse au Clair','L''Anse au Clair','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL172','ALL_CA','La Scie','La Scie','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL173','ALL_CA','Port Hope Simpson','Port Hope Simpson','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL174','ALL_CA','Grand le Pierre','Grand le Pierre','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL175','ALL_CA','Bonavista','Bonavista','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL176','ALL_CA','Hants Harbour','Hants Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL177','ALL_CA','Little Bay East','Little Bay East','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL178','ALL_CA','Little Bay Islands','Little Bay Islands','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL179','ALL_CA','Tickle Cove','Tickle Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL180','ALL_CA','Hodges Cove','Hodges Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL181','ALL_CA','Comfort Cove-Newstead','Comfort Cove-Newstead','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL182','ALL_CA','Boyds Cove','Boyds Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL183','ALL_CA','Burlington','Burlington','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL184','ALL_CA','Heart''s Delight','Heart''s Delight','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL185','ALL_CA','Middle Cove','Middle Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL186','ALL_CA','Miles Cove','Miles Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL187','ALL_CA','Mount Arlington Heights','Mount Arlington Heights','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL188','ALL_CA','Noels Pond','Noels Pond','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL189','ALL_CA','North River','North River','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL190','ALL_CA','Red Bay','Red Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL191','ALL_CA','Rigolet','Rigolet','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL192','ALL_CA','Rocky Harbour','Rocky Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL193','ALL_CA','South Branch','South Branch','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL194','ALL_CA','Springdale','Springdale','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL195','ALL_CA','West Bay Centre','West Bay Centre','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL196','ALL_CA','Cooks Harbour','Cooks Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL197','ALL_CA','Green Island Brook','Green Island Brook','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL198','ALL_CA','St. John''s','St. John''s','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL199','ALL_CA','Fleur de Lys','Fleur de Lys','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL200','ALL_CA','Howley','Howley','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL201','ALL_CA','English Harbour West','English Harbour West','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL202','ALL_CA','North West River','North West River','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL203','ALL_CA','Creston','Creston','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL204','ALL_CA','Caplin Cove Bdv','Caplin Cove Bdv','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL205','ALL_CA','Lower Island Cove','Lower Island Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL206','ALL_CA','Sops Arm','Sops Arm','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL207','ALL_CA','Trinity TB','Trinity TB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL208','ALL_CA','Petty Harbour','Petty Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL209','ALL_CA','Shearstown','Shearstown','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL210','ALL_CA','Change Islands','Change Islands','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL211','ALL_CA','Western Bay','Western Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL212','ALL_CA','Badgers Quay','Badgers Quay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL213','ALL_CA','New Harbour TB','New Harbour TB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL214','ALL_CA','Little Bay NDB','Little Bay NDB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL215','ALL_CA','Port au Choix','Port au Choix','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL216','ALL_CA','Port au Port','Port au Port','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL217','ALL_CA','St Vincents','St Vincents','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL218','ALL_CA','Portland Creek','Portland Creek','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL219','ALL_CA','St Juliens','St Juliens','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL220','ALL_CA','Victoria Cb','Victoria Cb','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL221','ALL_CA','Port Anson','Port Anson','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL222','ALL_CA','Port Blandford','Port Blandford','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL223','ALL_CA','Aguathuna','Aguathuna','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL224','ALL_CA','Benton','Benton','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL225','ALL_CA','Catalina','Catalina','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL226','ALL_CA','Frenchmans Cove FB','Frenchmans Cove FB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL227','ALL_CA','Gallants','Gallants','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL228','ALL_CA','Garden Cove PB','Garden Cove PB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL229','ALL_CA','Harbour Grace','Harbour Grace','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL230','ALL_CA','Millertown','Millertown','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL231','ALL_CA','Leading Tickles','Leading Tickles','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL232','ALL_CA','Logy Bay','Logy Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL233','ALL_CA','Tizzards Harbour','Tizzards Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL234','ALL_CA','Westport','Westport','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL235','ALL_CA','Winterland','Winterland','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL236','ALL_CA','Winterton','Winterton','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL237','ALL_CA','Port de Grave','Port de Grave','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL238','ALL_CA','Tilting','Tilting','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL239','ALL_CA','Salvage','Salvage','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL240','ALL_CA','Mings Bight','Mings Bight','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL241','ALL_CA','Cape Freels North','Cape Freels North','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL242','ALL_CA','Cape Ray','Cape Ray','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL243','ALL_CA','Main Brook','Main Brook','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL244','ALL_CA','Gander','Gander','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL245','ALL_CA','Pouch Cove','Pouch Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL246','ALL_CA','Gambo','Gambo','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL247','ALL_CA','Englee','Englee','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL248','ALL_CA','Bide Arm','Bide Arm','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL249','ALL_CA','Rushoon','Rushoon','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL250','ALL_CA','Burin Bay Arm','Burin Bay Arm','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL251','ALL_CA','Glenwood','Glenwood','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL252','ALL_CA','Coleys Point South','Coleys Point South','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL253','ALL_CA','Trout River','Trout River','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL254','ALL_CA','Codroy','Codroy','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL255','ALL_CA','Rattling Brook','Rattling Brook','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL256','ALL_CA','Coachmans Cove','Coachmans Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL257','ALL_CA','Charlottetown LAB','Charlottetown LAB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL258','ALL_CA','Musgrave Harbour','Musgrave Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL259','ALL_CA','Wiltondale','Wiltondale','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL260','ALL_CA','Doyles','Doyles','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL261','ALL_CA','Holyrood','Holyrood','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL262','ALL_CA','River of Ponds','River of Ponds','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL263','ALL_CA','Grates Cove','Grates Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL264','ALL_CA','Robinsons','Robinsons','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL265','ALL_CA','Pools Cove','Pools Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL266','ALL_CA','La Poile','La Poile','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL267','ALL_CA','Hawkes Bay','Hawkes Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL268','ALL_CA','Lewisporte','Lewisporte','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL269','ALL_CA','Laurenceton','Laurenceton','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL270','ALL_CA','Fair Haven','Fair Haven','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL271','ALL_CA','Chapel Cove','Chapel Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL272','ALL_CA','Greens Harbour','Greens Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL273','ALL_CA','Gaultois','Gaultois','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL274','ALL_CA','St Fintans','St Fintans','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL275','ALL_CA','Port Union','Port Union','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL276','ALL_CA','St Marys','St Marys','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL277','ALL_CA','Isle-aux-Morts','Isle-aux-Morts','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL278','ALL_CA','Lodge Bay','Lodge Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL279','ALL_CA','St Lewis','St Lewis','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL280','ALL_CA','Roddickton','Roddickton','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL281','ALL_CA','Rodgers Cove','Rodgers Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL282','ALL_CA','Ladle Cove','Ladle Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL283','ALL_CA','Beaumont','Beaumont','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL284','ALL_CA','Black Duck Siding','Black Duck Siding','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL285','ALL_CA','Burnt Islands Blp','Burnt Islands Blp','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL286','ALL_CA','Burnt Point Bdv','Burnt Point Bdv','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL287','ALL_CA','Charlottetown','Charlottetown','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL288','ALL_CA','Dover','Dover','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL289','ALL_CA','Flatrock','Flatrock','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL290','ALL_CA','Fogo','Fogo','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL291','ALL_CA','Frenchmans Cove Boi','Frenchmans Cove Boi','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL292','ALL_CA','Heatherton','Heatherton','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL293','ALL_CA','Hillgrade','Hillgrade','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL294','ALL_CA','Island Harbour','Island Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL295','ALL_CA','Kings Point','Kings Point','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL296','ALL_CA','Loon Bay','Loon Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL297','ALL_CA','Middle Arm GB','Middle Arm GB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL298','ALL_CA','Mount Moriah','Mount Moriah','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL299','ALL_CA','Parkers Cove','Parkers Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL300','ALL_CA','Sandringham','Sandringham','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL301','ALL_CA','St Albans','St Albans','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL302','ALL_CA','Williams Harbour','Williams Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL303','ALL_CA','Little Catalina','Little Catalina','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL304','ALL_CA','Plum Point','Plum Point','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL305','ALL_CA','Newmans Cove','Newmans Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL306','ALL_CA','Gander Bay South','Gander Bay South','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL307','ALL_CA','Nippers Harbour','Nippers Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL308','ALL_CA','Brents Cove','Brents Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL309','ALL_CA','Burin','Burin','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL310','ALL_CA','New Melbourne','New Melbourne','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL311','ALL_CA','Carbonear','Carbonear','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL312','ALL_CA','Baie Verte','Baie Verte','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL313','ALL_CA','Little St Lawrence','Little St Lawrence','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL314','ALL_CA','Highlands','Highlands','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL315','ALL_CA','North Harbour SMB','North Harbour SMB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL316','ALL_CA','Old Perlican','Old Perlican','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL317','ALL_CA','Calvert','Calvert','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL318','ALL_CA','Deep Bay','Deep Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL319','ALL_CA','Summerford','Summerford','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL320','ALL_CA','St Anthony','St Anthony','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL321','ALL_CA','Summerville','Summerville','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL322','ALL_CA','Norris Point','Norris Point','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL323','ALL_CA','Norris Arm Northside','Norris Arm Northside','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL324','ALL_CA','Channel-Port-aux-Basques','Channel-Port-aux-Basques','N','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL325','ALL_CA','Brigus Junction','Brigus Junction','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL326','ALL_CA','Blaketown','Blaketown','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL327','ALL_CA','Massey Drive','Massey Drive','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL328','ALL_CA','Brownsdale','Brownsdale','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL329','ALL_CA','Pilleys Island','Pilleys Island','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL330','ALL_CA','Glovertown South','Glovertown South','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL331','ALL_CA','St Davids','St Davids','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL332','ALL_CA','Port Saunders','Port Saunders','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL333','ALL_CA','Little Burnt Bay','Little Burnt Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL334','ALL_CA','Parsons Pond','Parsons Pond','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL335','ALL_CA','Francois','Francois','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL336','ALL_CA','St Josephs Sal','St Josephs Sal','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL337','ALL_CA','Lethbridge','Lethbridge','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL338','ALL_CA','Come by Chance','Come by Chance','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL339','ALL_CA','Black Duck Cove','Black Duck Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL340','ALL_CA','Aspen Cove','Aspen Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL341','ALL_CA','Brookfield','Brookfield','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL342','ALL_CA','Castors River','Castors River','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL343','ALL_CA','Clarkes Beach','Clarkes Beach','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL344','ALL_CA','Deer Lake','Deer Lake','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL345','ALL_CA','Forteau','Forteau','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL346','ALL_CA','Harbour Main','Harbour Main','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL347','ALL_CA','Heart''s Content','Heart''s Content','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL348','ALL_CA','Lance Cove','Lance Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL349','ALL_CA','Mobile','Mobile','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL350','ALL_CA','Mount Pearl','Mount Pearl','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL351','ALL_CA','Newtown','Newtown','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL352','ALL_CA','Reefs Harbour','Reefs Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL353','ALL_CA','Southern Harbour PB','Southern Harbour PB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL354','ALL_CA','Whiteway','Whiteway','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL355','ALL_CA','Herring Neck','Herring Neck','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL356','ALL_CA','Seal Cove FB','Seal Cove FB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL357','ALL_CA','Indian Bay BB','Indian Bay BB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL358','ALL_CA','Benoits Cove','Benoits Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL359','ALL_CA','Stephenville Crossing','Stephenville Crossing','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL360','ALL_CA','Round Harbour GB','Round Harbour GB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL361','ALL_CA','Riverhead Harbour Grace','Riverhead Harbour Grace','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL362','ALL_CA','Churchill Falls','Churchill Falls','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL363','ALL_CA','Flowers Cove','Flowers Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL364','ALL_CA','Burgoynes Cove','Burgoynes Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL365','ALL_CA','Swift Current','Swift Current','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL366','ALL_CA','Wabush','Wabush','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL367','ALL_CA','Seldom','Seldom','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL368','ALL_CA','Cupids','Cupids','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL369','ALL_CA','North Harbour PB','North Harbour PB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL370','ALL_CA','Old Shop','Old Shop','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL371','ALL_CA','Daniels Harbour','Daniels Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL372','ALL_CA','St Bernards-Jacques Fontaine','St Bernards-Jacques Fontaine','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL373','ALL_CA','Lamaline','Lamaline','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL374','ALL_CA','Princeton','Princeton','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL375','ALL_CA','Wareham-Centreville','Wareham-Centreville','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL376','ALL_CA','Baytona','Baytona','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL377','ALL_CA','Aquaforte','Aquaforte','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL378','ALL_CA','Carmanville','Carmanville','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL379','ALL_CA','Jacksons Arm','Jacksons Arm','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL380','ALL_CA','Jacksons Cove','Jacksons Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL381','ALL_CA','Northern Bay','Northern Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL382','ALL_CA','Avondale','Avondale','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL383','ALL_CA','McCallum','McCallum','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL384','ALL_CA','Plate Cove East','Plate Cove East','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL385','ALL_CA','Pools Island','Pools Island','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL386','ALL_CA','Normans Cove','Normans Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL387','ALL_CA','L''Anse au Loup','L''Anse au Loup','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL388','ALL_CA','St Shotts','St Shotts','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL389','ALL_CA','Garnish','Garnish','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL390','ALL_CA','Reidville','Reidville','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL391','ALL_CA','Lourdes','Lourdes','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL392','ALL_CA','Salmon Cove Bdv','Salmon Cove Bdv','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL393','ALL_CA','Traytown','Traytown','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL394','ALL_CA','Bonne Bay','Bonne Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL395','ALL_CA','Cow Head','Cow Head','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL396','ALL_CA','Creston North','Creston North','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL397','ALL_CA','Fox Harbour PB','Fox Harbour PB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL398','ALL_CA','Happy Valley-Goose Bay','Happy Valley-Goose Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL399','ALL_CA','Harbour Mille','Harbour Mille','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL400','ALL_CA','Harbour Round','Harbour Round','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL401','ALL_CA','Hopeall','Hopeall','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL402','ALL_CA','Joe Batts Arm','Joe Batts Arm','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL403','ALL_CA','Knights Cove','Knights Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL404','ALL_CA','Milltown','Milltown','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL405','ALL_CA','Natuashish','Natuashish','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL406','ALL_CA','Open Hall','Open Hall','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL407','ALL_CA','Rose Blanche','Rose Blanche','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL408','ALL_CA','Ship Harbour PB','Ship Harbour PB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL409','ALL_CA','West St Modeste','West St Modeste','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL410','ALL_CA','Fermeuse','Fermeuse','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL411','ALL_CA','Ferryland','Ferryland','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL412','ALL_CA','Seal Cove WB','Seal Cove WB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL413','ALL_CA','Upper Island Cove','Upper Island Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL414','ALL_CA','Stephenville','Stephenville','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL415','ALL_CA','Conception Harbour','Conception Harbour','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL416','ALL_CA','Labrador City','Labrador City','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL417','ALL_CA','Cape St George','Cape St George','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL418','ALL_CA','Paradise River','Paradise River','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL419','ALL_CA','Mount Carmel','Mount Carmel','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL420','ALL_CA','Burgeo','Burgeo','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL421','ALL_CA','Cape Broyle','Cape Broyle','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL422','ALL_CA','Sweet Bay','Sweet Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL423','ALL_CA','Jeffreys','Jeffreys','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL424','ALL_CA','Musgravetown','Musgravetown','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL425','ALL_CA','Point of Bay','Point of Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL426','ALL_CA','Witless Bay','Witless Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL427','ALL_CA','South Brook GB','South Brook GB','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL428','ALL_CA','Deadmans Bay','Deadmans Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL429','ALL_CA','New Chelsea','New Chelsea','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL430','ALL_CA','Bay Roberts','Bay Roberts','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL431','ALL_CA','St Andrews','St Andrews','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL432','ALL_CA','Belleoram','Belleoram','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL433','ALL_CA','Durrell','Durrell','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL434','ALL_CA','Plate Cove West','Plate Cove West','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL435','ALL_CA','Shoe Cove','Shoe Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL436','ALL_CA','Coxs Cove','Coxs Cove','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL437','ALL_CA','Grand Bank','Grand Bank','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL438','ALL_CA','Charleston','Charleston','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL439','ALL_CA','Anchor Point','Anchor Point','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL440','ALL_CA','Birchy Bay','Birchy Bay','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL441','ALL_CA','Birchy Head','Birchy Head','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL442','ALL_CA','St Pauls','St Pauls','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL443','ALL_CA','Elliston','Elliston','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL444','ALL_CA','St Georges','St Georges','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL445','ALL_CA','St Judes','St Judes','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL446','ALL_CA','St Lawrence','St Lawrence','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NL447','ALL_CA','Burnside','Burnside','NL','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0);
commit;
insert into YFS_REGION (REGION_KEY,REGION_SCHEMA_KEY,REGION_NAME,REGION_DESCRIPTION,PARENT_REGION_KEY,REGION_LEVEL_NAME,CAN_AGGREGATE,CREATEUSERID, MODIFYUSERID, CREATEPROGID, MODIFYPROGID, LOCKID) VALUES
('NU','ALL_CA','NU','NU','CAN','State','Y','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU1','ALL_CA','Arviat','Arviat','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU2','ALL_CA','Chesterfield Inlet','Chesterfield Inlet','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU3','ALL_CA','Cape Dorset','Cape Dorset','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU4','ALL_CA','Coral Harbour','Coral Harbour','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU5','ALL_CA','Rankin Inlet','Rankin Inlet','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU6','ALL_CA','Hall Beach','Hall Beach','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU7','ALL_CA','Baker Lake','Baker Lake','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU8','ALL_CA','Bay Chimo','Bay Chimo','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU9','ALL_CA','Kugluktuk','Kugluktuk','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU10','ALL_CA','Arctic Bay','Arctic Bay','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU11','ALL_CA','Iqaluit','Iqaluit','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU12','ALL_CA','Cambridge Bay','Cambridge Bay','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU13','ALL_CA','Kugaaruk','Kugaaruk','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU14','ALL_CA','Whale Cove','Whale Cove','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU15','ALL_CA','Sanikiluaq','Sanikiluaq','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU16','ALL_CA','Resolute','Resolute','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU17','ALL_CA','Repulse Bay','Repulse Bay','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU18','ALL_CA','Kimmirut','Kimmirut','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU19','ALL_CA','Kivitoo','Kivitoo','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU20','ALL_CA','Igloolik','Igloolik','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU21','ALL_CA','Grise Fiord','Grise Fiord','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU22','ALL_CA','Eureka','Eureka','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU23','ALL_CA','Taloyoak','Taloyoak','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU24','ALL_CA','Pond Inlet','Pond Inlet','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU25','ALL_CA','Qikiqtarjuaq','Qikiqtarjuaq','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU26','ALL_CA','Gjoa Haven','Gjoa Haven','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU27','ALL_CA','Clyde River','Clyde River','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NU28','ALL_CA','Pangnirtung','Pangnirtung','NU','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0);
commit;






