insert into YFS_REGION (REGION_KEY,REGION_SCHEMA_KEY,REGION_NAME,REGION_DESCRIPTION,PARENT_REGION_KEY,REGION_LEVEL_NAME,CAN_AGGREGATE,CREATEUSERID, MODIFYUSERID, CREATEPROGID, MODIFYPROGID, LOCKID) VALUES
('PE','ALL_CA','PE','PE','CAN','State','Y','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE55','ALL_CA','Ellerslie','Ellerslie','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE56','ALL_CA','Mount Albion','Mount Albion','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE57','ALL_CA','Pisquid West','Pisquid West','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE58','ALL_CA','Union Road','Union Road','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE59','ALL_CA','Charlottetown','Charlottetown','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE60','ALL_CA','Springvale','Springvale','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE61','ALL_CA','Bloomfield Station','Bloomfield Station','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE62','ALL_CA','Mount Herbert','Mount Herbert','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE63','ALL_CA','Murray Harbour','Murray Harbour','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE64','ALL_CA','Elmira','Elmira','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE65','ALL_CA','Kensington','Kensington','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE66','ALL_CA','Bunbury','Bunbury','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE67','ALL_CA','Hunter River','Hunter River','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE68','ALL_CA','Mermaid','Mermaid','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE69','ALL_CA','Wellington Station','Wellington Station','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE70','ALL_CA','Richmond','Richmond','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE71','ALL_CA','Auburn','Auburn','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE72','ALL_CA','Ebenezer','Ebenezer','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE73','ALL_CA','Borden-Carleton','Borden-Carleton','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE74','ALL_CA','Elmsdale','Elmsdale','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE75','ALL_CA','Lennox Island','Lennox Island','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE76','ALL_CA','Belle River','Belle River','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE77','ALL_CA','Marshfield','Marshfield','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE78','ALL_CA','Stratford','Stratford','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE79','ALL_CA','Tyne Valley','Tyne Valley','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE80','ALL_CA','Johnstons River','Johnstons River','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE81','ALL_CA','Bedeque','Bedeque','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE82','ALL_CA','Suffolk','Suffolk','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE83','ALL_CA','Lake Verde','Lake Verde','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE84','ALL_CA','Oyster Bed','Oyster Bed','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE85','ALL_CA','Cardigan','Cardigan','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE86','ALL_CA','Clyde River','Clyde River','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE87','ALL_CA','South Winsloe','South Winsloe','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE88','ALL_CA','York','York','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE89','ALL_CA','Tignish','Tignish','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE90','ALL_CA','Murray River','Murray River','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE91','ALL_CA','Argyle Shore','Argyle Shore','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE43','ALL_CA','Kinkora','Kinkora','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE44','ALL_CA','Milton Station','Milton Station','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE45','ALL_CA','Pownal','Pownal','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE46','ALL_CA','Mount Mellick','Mount Mellick','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE47','ALL_CA','Tarantum','Tarantum','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE48','ALL_CA','Miscouche','Miscouche','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE49','ALL_CA','Mount Stewart','Mount Stewart','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE50','ALL_CA','Waterside','Waterside','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE51','ALL_CA','Central Bedeque','Central Bedeque','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE52','ALL_CA','St-Louis','St-Louis','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE53','ALL_CA','St-Peters Bay','St-Peters Bay','PE+A6953:A7046','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE1','ALL_CA','Albany','Albany','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE2','ALL_CA','Crapaud','Crapaud','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE3','ALL_CA','North Rustico','North Rustico','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE4','ALL_CA','Warren Grove','Warren Grove','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE5','ALL_CA','Green Gables','Green Gables','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE6','ALL_CA','New Glasgow','New Glasgow','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE7','ALL_CA','North Winsloe','North Winsloe','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE8','ALL_CA','North Milton','North Milton','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE9','ALL_CA','Souris','Souris','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE10','ALL_CA','Cornwall','Cornwall','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE11','ALL_CA','Georgetown','Georgetown','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE12','ALL_CA','Winsloe','Winsloe','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE13','ALL_CA','Wheatley River','Wheatley River','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE14','ALL_CA','Vernon Bridge','Vernon Bridge','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE15','ALL_CA','Bonshaw','Bonshaw','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE16','ALL_CA','Alexandra','Alexandra','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE17','ALL_CA','Belfast','Belfast','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE18','ALL_CA','Miminegash','Miminegash','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE19','ALL_CA','Websters Corner','Websters Corner','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE20','ALL_CA','Hazelbrook','Hazelbrook','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE21','ALL_CA','Hermitage','Hermitage','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE22','ALL_CA','Donagh','Donagh','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE23','ALL_CA','North Wiltshire','North Wiltshire','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE24','ALL_CA','Fort Augustus','Fort Augustus','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE25','ALL_CA','Village Green','Village Green','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE26','ALL_CA','Montague','Montague','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE27','ALL_CA','Dunstaffnage','Dunstaffnage','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE28','ALL_CA','Harrington','Harrington','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE29','ALL_CA','Freetown','Freetown','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE30','ALL_CA','Coleman','Coleman','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE31','ALL_CA','Brackley Beach','Brackley Beach','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE32','ALL_CA','Summerside','Summerside','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE33','ALL_CA','Bethel','Bethel','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE34','ALL_CA','Alberton','Alberton','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE35','ALL_CA','Breadalbane','Breadalbane','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE36','ALL_CA','Slemon Park','Slemon Park','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE37','ALL_CA','Brackley','Brackley','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE38','ALL_CA','Victoria','Victoria','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE39','ALL_CA','Glenfinnan','Glenfinnan','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE40','ALL_CA','O''Leary','O''Leary','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE41','ALL_CA','Canoe Cove','Canoe Cove','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE42','ALL_CA','Frenchfort','Frenchfort','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('PE54','ALL_CA','Morell','Morell','PE','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0);
commit;