insert into YFS_REGION (REGION_KEY,REGION_SCHEMA_KEY,REGION_NAME,REGION_DESCRIPTION,PARENT_REGION_KEY,REGION_LEVEL_NAME,CAN_AGGREGATE,CREATEUSERID, MODIFYUSERID, CREATEPROGID, MODIFYPROGID, LOCKID) VALUES 
('CAN','ALL_CA','CA','Canada states',' ','Country','Y','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB','ALL_CA','MB','MB','CAN','State','Y','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB1','ALL_CA','Beulah','Beulah','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB2','ALL_CA','Dakota Tipi','Dakota Tipi','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB3','ALL_CA','Dropmore','Dropmore','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB4','ALL_CA','Elkhorn','Elkhorn','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB5','ALL_CA','Fork River','Fork River','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB6','ALL_CA','Forrest Station','Forrest Station','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB7','ALL_CA','Foxwarren','Foxwarren','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB8','ALL_CA','Komarno','Komarno','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB9','ALL_CA','Libau','Libau','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB10','ALL_CA','Lowe Farm','Lowe Farm','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB11','ALL_CA','Lundar','Lundar','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB12','ALL_CA','Macdonald','Macdonald','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB13','ALL_CA','Manson','Manson','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB14','ALL_CA','Menzie','Menzie','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB15','ALL_CA','Pauingassi','Pauingassi','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB16','ALL_CA','Pierson','Pierson','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB17','ALL_CA','Rossburn','Rossburn','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB18','ALL_CA','Sandy Lake','Sandy Lake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB19','ALL_CA','Tootinaowaziibeeng','Tootinaowaziibeeng','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB20','ALL_CA','Vermette','Vermette','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB21','ALL_CA','Vista','Vista','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB22','ALL_CA','Vogar','Vogar','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB23','ALL_CA','East St Paul','East St Paul','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB24','ALL_CA','Lakeland','Lakeland','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB25','ALL_CA','Whiteshell','Whiteshell','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB26','ALL_CA','Oak Lake','Oak Lake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB27','ALL_CA','Kirkella','Kirkella','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB28','ALL_CA','Gladstone','Gladstone','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB29','ALL_CA','Ninga','Ninga','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB30','ALL_CA','Fort Alexander','Fort Alexander','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB31','ALL_CA','St Martin','St Martin','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB32','ALL_CA','Hilbre','Hilbre','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB33','ALL_CA','Cartier','Cartier','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB34','ALL_CA','Macgregor','Macgregor','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB35','ALL_CA','Roblin','Roblin','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB36','ALL_CA','McCreary','McCreary','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB37','ALL_CA','Domain','Domain','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB38','ALL_CA','Stockton','Stockton','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB39','ALL_CA','Souris','Souris','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB40','ALL_CA','Chatfield','Chatfield','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB41','ALL_CA','Pinawa','Pinawa','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB42','ALL_CA','Napinka','Napinka','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB43','ALL_CA','Oakview','Oakview','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB44','ALL_CA','Oakville','Oakville','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB45','ALL_CA','Hamiota','Hamiota','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB46','ALL_CA','Toutes Aides','Toutes Aides','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB47','ALL_CA','Headingley','Headingley','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB48','ALL_CA','Rossendale','Rossendale','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB49','ALL_CA','Sidney','Sidney','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB50','ALL_CA','Victoria Beach','Victoria Beach','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB51','ALL_CA','Whitemouth','Whitemouth','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB52','ALL_CA','Arnaud','Arnaud','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB53','ALL_CA','Ashville','Ashville','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB54','ALL_CA','Baldur','Baldur','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB55','ALL_CA','Boissevain','Boissevain','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB56','ALL_CA','Ginew','Ginew','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB57','ALL_CA','Howden','Howden','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB58','ALL_CA','La Riviere','La Riviere','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB59','ALL_CA','Marquette','Marquette','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB60','ALL_CA','Neepawa','Neepawa','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB61','ALL_CA','Negginan','Negginan','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB62','ALL_CA','Poplar Point','Poplar Point','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB63','ALL_CA','Pukatawagan','Pukatawagan','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB64','ALL_CA','Rapid City','Rapid City','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB65','ALL_CA','St Adolphe','St Adolphe','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB66','ALL_CA','Ste Anne','Ste Anne','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB67','ALL_CA','Woodmore','Woodmore','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB68','ALL_CA','Hargrave','Hargrave','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB69','ALL_CA','Marius','Marius','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB70','ALL_CA','South Junction','South Junction','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB71','ALL_CA','Lockport','Lockport','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB72','ALL_CA','Oak Bluff','Oak Bluff','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB73','ALL_CA','Russell','Russell','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB74','ALL_CA','Waywayseecappo','Waywayseecappo','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB75','ALL_CA','Springstein','Springstein','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB76','ALL_CA','Cartwright','Cartwright','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB77','ALL_CA','Oakburn','Oakburn','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB78','ALL_CA','Green Ridge','Green Ridge','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB79','ALL_CA','Holmfield','Holmfield','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB80','ALL_CA','Pansy','Pansy','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB81','ALL_CA','Beaconia','Beaconia','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB82','ALL_CA','Mather','Mather','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB83','ALL_CA','Laurier','Laurier','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB84','ALL_CA','La Broquerie','La Broquerie','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB85','ALL_CA','Channing','Channing','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB86','ALL_CA','St Eustache','St Eustache','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB87','ALL_CA','River Hills','River Hills','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB88','ALL_CA','Amaranth','Amaranth','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB89','ALL_CA','Dunrea','Dunrea','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB90','ALL_CA','Gods River','Gods River','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB91','ALL_CA','Elma','Elma','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB92','ALL_CA','Glenboro','Glenboro','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB93','ALL_CA','Reinfeld','Reinfeld','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB94','ALL_CA','St Laurent','St Laurent','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB95','ALL_CA','St Leon','St Leon','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB96','ALL_CA','Medora','Medora','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB97','ALL_CA','Altamont','Altamont','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB98','ALL_CA','Glenora','Glenora','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB99','ALL_CA','Red Sucker Lake','Red Sucker Lake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB108','ALL_CA','Great Falls','Great Falls','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB109','ALL_CA','Meleb','Meleb','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB110','ALL_CA','Mountain Road','Mountain Road','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB111','ALL_CA','Ochre River','Ochre River','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB112','ALL_CA','Roseau River','Roseau River','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB113','ALL_CA','Sarto','Sarto','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB114','ALL_CA','Scanterbury','Scanterbury','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB115','ALL_CA','Shamattawa','Shamattawa','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB116','ALL_CA','Shellmouth','Shellmouth','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB117','ALL_CA','Sinclair','Sinclair','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB118','ALL_CA','Ste Agathe','Ste Agathe','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB119','ALL_CA','Woodlands','Woodlands','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB120','ALL_CA','Little Grand Rapids','Little Grand Rapids','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB121','ALL_CA','Plum Coulee','Plum Coulee','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB122','ALL_CA','Crystal City','Crystal City','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB123','ALL_CA','Ebb and Flow','Ebb and Flow','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB124','ALL_CA','Dominion City','Dominion City','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB125','ALL_CA','Winkler','Winkler','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB126','ALL_CA','Grunthal','Grunthal','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB127','ALL_CA','Beausejour','Beausejour','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB128','ALL_CA','Inwood','Inwood','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB129','ALL_CA','St Theresa Point','St Theresa Point','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB130','ALL_CA','Oxford House','Oxford House','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB131','ALL_CA','Cardale','Cardale','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB132','ALL_CA','Douglas','Douglas','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB133','ALL_CA','Polonia','Polonia','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB134','ALL_CA','Harding','Harding','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB135','ALL_CA','Wellwood','Wellwood','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB136','ALL_CA','Lac Brochet','Lac Brochet','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB137','ALL_CA','Clanwilliam','Clanwilliam','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB138','ALL_CA','Lorette','Lorette','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB139','ALL_CA','Mafeking','Mafeking','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB140','ALL_CA','Hartney','Hartney','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB141','ALL_CA','Tyndall','Tyndall','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB142','ALL_CA','Renwer','Renwer','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB143','ALL_CA','Alexander','Alexander','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB144','ALL_CA','Belleview','Belleview','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB145','ALL_CA','Grande Pointe','Grande Pointe','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB146','ALL_CA','Matlock','Matlock','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB147','ALL_CA','Pipestone','Pipestone','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB148','ALL_CA','Shoal Lake','Shoal Lake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB149','ALL_CA','Lavenham','Lavenham','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB150','ALL_CA','Vassar','Vassar','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB151','ALL_CA','Rosenfeld','Rosenfeld','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB152','ALL_CA','Justice','Justice','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB153','ALL_CA','Bissett','Bissett','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB154','ALL_CA','Durban','Durban','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB155','ALL_CA','Schanzenfeld','Schanzenfeld','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB156','ALL_CA','Garson','Garson','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB157','ALL_CA','Winnipegosis','Winnipegosis','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB158','ALL_CA','Stephenfield','Stephenfield','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB159','ALL_CA','Wanipigow','Wanipigow','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB160','ALL_CA','Moosehorn','Moosehorn','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB161','ALL_CA','Meadow Portage','Meadow Portage','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB162','ALL_CA','Crane River','Crane River','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB163','ALL_CA','Arnes','Arnes','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB164','ALL_CA','Camp Morton','Camp Morton','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB165','ALL_CA','Cowan','Cowan','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB166','ALL_CA','Elphinstone','Elphinstone','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB167','ALL_CA','Fannystelle','Fannystelle','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB168','ALL_CA','Gardenton','Gardenton','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB169','ALL_CA','Ile-des-Chenes','Ile-des-Chenes','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB170','ALL_CA','Island Lake','Island Lake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB171','ALL_CA','Koostatak','Koostatak','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB172','ALL_CA','Menisino','Menisino','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB173','ALL_CA','Minnedosa','Minnedosa','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB174','ALL_CA','Minto','Minto','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB175','ALL_CA','Narol','Narol','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB176','ALL_CA','Onanole','Onanole','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB177','ALL_CA','Peguis','Peguis','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB178','ALL_CA','Skownan','Skownan','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB179','ALL_CA','Snowflake','Snowflake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB180','ALL_CA','Sperling','Sperling','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB181','ALL_CA','St Ambroise','St Ambroise','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB182','ALL_CA','Sundown','Sundown','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB183','ALL_CA','Wawanesa','Wawanesa','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB184','ALL_CA','West St Paul','West St Paul','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB185','ALL_CA','Plumas','Plumas','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB186','ALL_CA','Hazelridge','Hazelridge','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB187','ALL_CA','Kenville','Kenville','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB188','ALL_CA','Kenton','Kenton','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB189','ALL_CA','Grand Rapids','Grand Rapids','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB190','ALL_CA','Reston','Reston','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB191','ALL_CA','Stuartburn','Stuartburn','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB192','ALL_CA','Lyleton','Lyleton','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB193','ALL_CA','Wabowden','Wabowden','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB194','ALL_CA','Horndean','Horndean','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB195','ALL_CA','Rathwell','Rathwell','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB196','ALL_CA','Morris','Morris','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB197','ALL_CA','Letellier','Letellier','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB198','ALL_CA','Oak Point','Oak Point','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB199','ALL_CA','Oak River','Oak River','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB200','ALL_CA','Oakbank','Oakbank','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB201','ALL_CA','Fairford','Fairford','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB202','ALL_CA','Erickson','Erickson','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB203','ALL_CA','Berens River','Berens River','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB204','ALL_CA','Carman','Carman','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB205','ALL_CA','East Braintree','East Braintree','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB206','ALL_CA','Stonewall','Stonewall','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB207','ALL_CA','Faulkner','Faulkner','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB208','ALL_CA','Pilot Mound','Pilot Mound','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB209','ALL_CA','Tourond','Tourond','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB210','ALL_CA','Gods Lake Narrows','Gods Lake Narrows','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB211','ALL_CA','St Pierre Jolys','St Pierre Jolys','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB212','ALL_CA','Winnipeg Beach','Winnipeg Beach','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB213','ALL_CA','Opaskwayak','Opaskwayak','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB214','ALL_CA','Morden','Morden','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB215','ALL_CA','Wanless','Wanless','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB216','ALL_CA','St Jean Baptiste','St Jean Baptiste','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB217','ALL_CA','St. Georges','St. Georges','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB218','ALL_CA','Argyle','Argyle','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB219','ALL_CA','Bloodvein','Bloodvein','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB220','ALL_CA','Traverse Bay','Traverse Bay','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB221','ALL_CA','Westbourne','Westbourne','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB222','ALL_CA','Sifton','Sifton','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB223','ALL_CA','Aubigny','Aubigny','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB224','ALL_CA','Brookdale','Brookdale','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB225','ALL_CA','Carberry','Carberry','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB226','ALL_CA','Eddystone','Eddystone','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB227','ALL_CA','Goodlands','Goodlands','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB228','ALL_CA','Ilford','Ilford','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB229','ALL_CA','Isabella','Isabella','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB230','ALL_CA','Manigotagan','Manigotagan','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB231','ALL_CA','Miniota','Miniota','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB232','ALL_CA','Newton Siding','Newton Siding','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB233','ALL_CA','Riding Mountain','Riding Mountain','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB234','ALL_CA','Sandy Hook','Sandy Hook','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB235','ALL_CA','Silver','Silver','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB236','ALL_CA','Silver Ridge','Silver Ridge','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB237','ALL_CA','Thompson','Thompson','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB238','ALL_CA','Pine Falls','Pine Falls','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB239','ALL_CA','Rivers','Rivers','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB240','ALL_CA','Lenore','Lenore','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB241','ALL_CA','Churchill','Churchill','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB242','ALL_CA','Sherridon','Sherridon','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB243','ALL_CA','Rock Ridge','Rock Ridge','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB244','ALL_CA','Pointe du Bois','Pointe du Bois','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB245','ALL_CA','Selkirk','Selkirk','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB246','ALL_CA','Warren','Warren','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB247','ALL_CA','Southport','Southport','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB248','ALL_CA','The Pas','The Pas','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB249','ALL_CA','Mariapolis','Mariapolis','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB250','ALL_CA','Notre Dame de Lourdes','Notre Dame de Lourdes','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB251','ALL_CA','Kinosota','Kinosota','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB252','ALL_CA','Rosa','Rosa','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB263','ALL_CA','Richer','Richer','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB264','ALL_CA','Arden','Arden','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB265','ALL_CA','Bowsman','Bowsman','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB266','ALL_CA','St Francois Xavier','St Francois Xavier','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB267','ALL_CA','Wasagamack','Wasagamack','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB268','ALL_CA','Graysville','Graysville','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB269','ALL_CA','Marchand','Marchand','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB270','ALL_CA','Woodridge','Woodridge','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB271','ALL_CA','St Germain South','St Germain South','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB272','ALL_CA','Bruxelles','Bruxelles','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB273','ALL_CA','Cormorant','Cormorant','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB274','ALL_CA','Seven Sisters Falls','Seven Sisters Falls','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB275','ALL_CA','Somerset','Somerset','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB276','ALL_CA','Kelwood','Kelwood','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB253','ALL_CA','Lake Francis','Lake Francis','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB254','ALL_CA','Arborg','Arborg','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB255','ALL_CA','Grahamdale','Grahamdale','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB256','ALL_CA','Stony Mountain','Stony Mountain','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB257','ALL_CA','Hadashville','Hadashville','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB258','ALL_CA','Grand Marais','Grand Marais','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB259','ALL_CA','Matheson Island','Matheson Island','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB260','ALL_CA','Thicket Portage','Thicket Portage','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB261','ALL_CA','La Barriere','La Barriere','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB262','ALL_CA','Elie','Elie','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB277','ALL_CA','Barrows','Barrows','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB278','ALL_CA','Birnie','Birnie','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB279','ALL_CA','Coulter','Coulter','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB280','ALL_CA','Cypress River','Cypress River','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB281','ALL_CA','Falcon Beach','Falcon Beach','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB282','ALL_CA','Gilbert Plains','Gilbert Plains','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB283','ALL_CA','Gimli','Gimli','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB284','ALL_CA','Giroux','Giroux','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB285','ALL_CA','Gypsumville','Gypsumville','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB286','ALL_CA','High Bluff','High Bluff','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB287','ALL_CA','Holland','Holland','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB288','ALL_CA','Landmark','Landmark','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB289','ALL_CA','Leaf Rapids','Leaf Rapids','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB290','ALL_CA','Malonton','Malonton','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB291','ALL_CA','Minitonas','Minitonas','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB292','ALL_CA','O''Hanly','O''Hanly','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB293','ALL_CA','Roseisle','Roseisle','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB294','ALL_CA','Snow Lake','Snow Lake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB295','ALL_CA','Stevenson Island','Stevenson Island','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB296','ALL_CA','Strathclair','Strathclair','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB297','ALL_CA','Teulon','Teulon','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB298','ALL_CA','Anola','Anola','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB299','ALL_CA','East Selkirk','East Selkirk','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB300','ALL_CA','Flin Flon','Flin Flon','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB301','ALL_CA','Sanford','Sanford','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB302','ALL_CA','Norway House','Norway House','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB303','ALL_CA','Cranberry Portage','Cranberry Portage','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB341','ALL_CA','Binscarth','Binscarth','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB342','ALL_CA','Blumenort','Blumenort','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB343','ALL_CA','Darlingford','Darlingford','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB344','ALL_CA','Eriksdale','Eriksdale','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB345','ALL_CA','La Salle','La Salle','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB346','ALL_CA','Lynn Lake','Lynn Lake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB347','ALL_CA','Melita','Melita','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB348','ALL_CA','Miami','Miami','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB349','ALL_CA','Pine River','Pine River','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB350','ALL_CA','Poplarfield','Poplarfield','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB351','ALL_CA','Shilo','Shilo','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB352','ALL_CA','Sprague','Sprague','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB353','ALL_CA','Tolstoi','Tolstoi','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB354','ALL_CA','Vita','Vita','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB355','ALL_CA','Waskada','Waskada','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB356','ALL_CA','Winnipeg','Winnipeg','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB357','ALL_CA','Belmont','Belmont','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB358','ALL_CA','Franklin','Franklin','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB359','ALL_CA','Steinbach','Steinbach','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB360','ALL_CA','Easterville','Easterville','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB361','ALL_CA','Cayer','Cayer','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB362','ALL_CA','Gillam','Gillam','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB363','ALL_CA','Edwin','Edwin','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB364','ALL_CA','Cross Lake','Cross Lake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB365','ALL_CA','St Marks','St Marks','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB366','ALL_CA','Margaret','Margaret','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB367','ALL_CA','New Bothwell','New Bothwell','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB368','ALL_CA','Newdale','Newdale','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB369','ALL_CA','Makinak','Makinak','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB370','ALL_CA','Mulvihill','Mulvihill','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB371','ALL_CA','Emerson','Emerson','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB372','ALL_CA','Rorketon','Rorketon','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB373','ALL_CA','Lac du Bonnet','Lac du Bonnet','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB374','ALL_CA','Starbuck','Starbuck','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB375','ALL_CA','Dallas','Dallas','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB376','ALL_CA','Gretna','Gretna','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB377','ALL_CA','Ridgeville','Ridgeville','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB378','ALL_CA','Lake Audy','Lake Audy','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB379','ALL_CA','Piney','Piney','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB380','ALL_CA','Portage La Prairie','Portage La Prairie','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB381','ALL_CA','Lauder','Lauder','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB382','ALL_CA','Stead','Stead','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB383','ALL_CA','Ashern','Ashern','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB384','ALL_CA','Deleau','Deleau','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB385','ALL_CA','Split Lake','Split Lake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB386','ALL_CA','Petersfield','Petersfield','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB387','ALL_CA','Rennie','Rennie','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB388','ALL_CA','Griswold','Griswold','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB389','ALL_CA','Austin','Austin','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB390','ALL_CA','Birch River','Birch River','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB391','ALL_CA','Tilston','Tilston','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB392','ALL_CA','Ste Rose du Lac','Ste Rose du Lac','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB393','ALL_CA','Rosser','Rosser','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB394','ALL_CA','Woodside','Woodside','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB395','ALL_CA','St Joseph','St Joseph','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB396','ALL_CA','Princess Harbour','Princess Harbour','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB397','ALL_CA','Moose Lake','Moose Lake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB398','ALL_CA','Solsgirth','Solsgirth','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB399','ALL_CA','Langruth','Langruth','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB400','ALL_CA','Thornhill','Thornhill','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB401','ALL_CA','Haywood','Haywood','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB402','ALL_CA','Alonsa','Alonsa','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB403','ALL_CA','Brochet','Brochet','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB404','ALL_CA','Buffalo Point','Buffalo Point','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB405','ALL_CA','Cromer','Cromer','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB406','ALL_CA','Eden','Eden','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB407','ALL_CA','Elgin','Elgin','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB408','ALL_CA','Valley River','Valley River','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB409','ALL_CA','Glenella','Glenella','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB410','ALL_CA','Gonor','Gonor','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB411','ALL_CA','Homewood','Homewood','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB412','ALL_CA','Killarney','Killarney','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB413','ALL_CA','Narcisse','Narcisse','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB414','ALL_CA','San Clara','San Clara','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB415','ALL_CA','Sandilands','Sandilands','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB416','ALL_CA','Springfield','Springfield','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB417','ALL_CA','St Alphonse','St Alphonse','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB418','ALL_CA','St Andrews','St Andrews','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB419','ALL_CA','Halbstadt','Halbstadt','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB420','ALL_CA','Benito','Benito','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB421','ALL_CA','Lake Manitoba First Nation','Lake Manitoba First Nation','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB422','ALL_CA','Dauphin','Dauphin','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB423','ALL_CA','Ninette','Ninette','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB424','ALL_CA','Bethany','Bethany','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB425','ALL_CA','Dacotah','Dacotah','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB426','ALL_CA','Garland','Garland','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB427','ALL_CA','Waterhen','Waterhen','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB428','ALL_CA','Swan Lake','Swan Lake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB429','ALL_CA','Nesbitt','Nesbitt','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB430','ALL_CA','Roland','Roland','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB431','ALL_CA','Angusville','Angusville','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB432','ALL_CA','Zhoda','Zhoda','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB433','ALL_CA','Clandeboye','Clandeboye','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB434','ALL_CA','York Landing','York Landing','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB435','ALL_CA','Decker','Decker','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB304','ALL_CA','West Pine Ridge','West Pine Ridge','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB305','ALL_CA','South Indian Lake','South Indian Lake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB306','ALL_CA','Middlebro','Middlebro','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB307','ALL_CA','Boggy Creek','Boggy Creek','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB308','ALL_CA','Steep Rock','Steep Rock','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB309','ALL_CA','Grandview','Grandview','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB310','ALL_CA','Overstoneville','Overstoneville','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB311','ALL_CA','St Malo','St Malo','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB312','ALL_CA','Camperville','Camperville','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB313','ALL_CA','Kola','Kola','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB314','ALL_CA','Riverton','Riverton','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB315','ALL_CA','Swan River','Swan River','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB316','ALL_CA','Pelican Rapids','Pelican Rapids','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB317','ALL_CA','Balmoral','Balmoral','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB318','ALL_CA','Clearwater','Clearwater','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB319','ALL_CA','Belair','Belair','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB320','ALL_CA','Arrow River','Arrow River','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB321','ALL_CA','Tadoule Lake','Tadoule Lake','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB322','ALL_CA','Dufresne','Dufresne','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB323','ALL_CA','Dufrost','Dufrost','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB324','ALL_CA','Virden','Virden','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB325','ALL_CA','Broad Valley','Broad Valley','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB326','ALL_CA','Otterburne','Otterburne','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB327','ALL_CA','Manitou','Manitou','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB328','ALL_CA','Bradwardine','Bradwardine','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB329','ALL_CA','Inglis','Inglis','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB330','ALL_CA','Bagot','Bagot','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB331','ALL_CA','Little Bullhead','Little Bullhead','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB332','ALL_CA','Deloraine','Deloraine','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB333','ALL_CA','Elm Creek','Elm Creek','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB334','ALL_CA','Mitchell','Mitchell','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB335','ALL_CA','Duck Bay','Duck Bay','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB336','ALL_CA','St Lazare','St Lazare','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB337','ALL_CA','Hodgson','Hodgson','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB338','ALL_CA','Randolph','Randolph','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB339','ALL_CA','Treherne','Treherne','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
 ('MB340','ALL_CA','Powerview','Powerview','MB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0);
 commit;