insert into YFS_REGION (REGION_KEY,REGION_SCHEMA_KEY,REGION_NAME,REGION_DESCRIPTION,PARENT_REGION_KEY,REGION_LEVEL_NAME,CAN_AGGREGATE,CREATEUSERID, MODIFYUSERID, CREATEPROGID, MODIFYPROGID, LOCKID) VALUES
('NS','ALL_CA','NS','NS','CAN','State','Y','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS389','ALL_CA','Shelburne','Shelburne','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS390','ALL_CA','Black Brook','Black Brook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS391','ALL_CA','Smithsville','Smithsville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS392','ALL_CA','Belliveau Cove','Belliveau Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS393','ALL_CA','River Hebert','River Hebert','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS394','ALL_CA','Guysborough','Guysborough','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS395','ALL_CA','Meaghers Grant','Meaghers Grant','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS396','ALL_CA','Stellarton','Stellarton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS397','ALL_CA','Thorburn','Thorburn','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS398','ALL_CA','Port Malcolm','Port Malcolm','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS399','ALL_CA','Askilton','Askilton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS400','ALL_CA','Barrio Lake','Barrio Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS401','ALL_CA','Chester','Chester','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS402','ALL_CA','Crouses Settlement','Crouses Settlement','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS403','ALL_CA','East Clifford','East Clifford','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS404','ALL_CA','Valley','Valley','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS405','ALL_CA','Gabarus Lake','Gabarus Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS406','ALL_CA','Glen Haven','Glen Haven','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS407','ALL_CA','Grimms Settlement','Grimms Settlement','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS408','ALL_CA','Heatherton','Heatherton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS409','ALL_CA','Hebbs Cross','Hebbs Cross','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS410','ALL_CA','Huntington','Huntington','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS411','ALL_CA','Irish Cove','Irish Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS412','ALL_CA','Lake Uist','Lake Uist','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS413','ALL_CA','Millville','Millville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS414','ALL_CA','Moser River','Moser River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS415','ALL_CA','Mount Uniacke','Mount Uniacke','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS416','ALL_CA','Little Narrows','Little Narrows','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS417','ALL_CA','Little Pond','Little Pond','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS418','ALL_CA','Upper Port la Tour','Upper Port la Tour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS419','ALL_CA','Stewiacke','Stewiacke','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS420','ALL_CA','Head of St Margarets Bay','Head of St Margarets Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS421','ALL_CA','Sambro Head','Sambro Head','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS422','ALL_CA','Hammonds Plains','Hammonds Plains','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS423','ALL_CA','Amherst','Amherst','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS424','ALL_CA','West Clifford','West Clifford','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS425','ALL_CA','Beaver Brook','Beaver Brook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS426','ALL_CA','New Minas','New Minas','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS427','ALL_CA','Port Maitland','Port Maitland','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS428','ALL_CA','Coldbrook','Coldbrook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS429','ALL_CA','Lingan Road','Lingan Road','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS430','ALL_CA','Sydney Forks','Sydney Forks','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS431','ALL_CA','Sydney Mines','Sydney Mines','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS432','ALL_CA','Melville','Melville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS433','ALL_CA','Grand Lake Road','Grand Lake Road','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS434','ALL_CA','West Pennant','West Pennant','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS435','ALL_CA','Donkin','Donkin','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS436','ALL_CA','Scotsville','Scotsville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS437','ALL_CA','Dutch Settlement','Dutch Settlement','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS438','ALL_CA','Hillside Boularderie','Hillside Boularderie','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS439','ALL_CA','Georges River','Georges River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS440','ALL_CA','Balls Creek','Balls Creek','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS441','ALL_CA','Diligent River','Diligent River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS442','ALL_CA','Pleasant Hill','Pleasant Hill','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS443','ALL_CA','Little Tancook','Little Tancook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS444','ALL_CA','Rock Elm','Rock Elm','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS445','ALL_CA','Salmon River','Salmon River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS446','ALL_CA','Waterville','Waterville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS447','ALL_CA','Pictou','Pictou','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS448','ALL_CA','Long Island','Long Island','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS449','ALL_CA','Rockville','Rockville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS450','ALL_CA','Sable River','Sable River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS451','ALL_CA','Hubbards','Hubbards','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS452','ALL_CA','Barneys River Station','Barneys River Station','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS453','ALL_CA','Lakeside','Lakeside','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS454','ALL_CA','Lower Prospect','Lower Prospect','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS455','ALL_CA','Summerville','Summerville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS456','ALL_CA','Cleveland','Cleveland','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS457','ALL_CA','Hebron','Hebron','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS458','ALL_CA','Mahone Bay','Mahone Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS459','ALL_CA','Louisdale','Louisdale','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS460','ALL_CA','Ottawa Brook','Ottawa Brook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS461','ALL_CA','Cornwallis','Cornwallis','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS462','ALL_CA','Port Howe','Port Howe','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS463','ALL_CA','Ingramport','Ingramport','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS464','ALL_CA','Eureka','Eureka','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS465','ALL_CA','Goffs','Goffs','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS466','ALL_CA','Sugar Camp','Sugar Camp','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS467','ALL_CA','Framboise Intervale','Framboise Intervale','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS468','ALL_CA','Crandall Road','Crandall Road','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS469','ALL_CA','Port Medway','Port Medway','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS470','ALL_CA','Baccaro','Baccaro','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS471','ALL_CA','Benacadie','Benacadie','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS472','ALL_CA','Big Lake','Big Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS473','ALL_CA','Brookfield','Brookfield','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS474','ALL_CA','Catalone','Catalone','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS475','ALL_CA','Chester Basin','Chester Basin','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS476','ALL_CA','Clementsvale','Clementsvale','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS477','ALL_CA','Crowes Mills','Crowes Mills','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS478','ALL_CA','Gabarus','Gabarus','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS479','ALL_CA','Hunts Point','Hunts Point','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS480','ALL_CA','Kennetcook','Kennetcook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS481','ALL_CA','Lucasville','Lucasville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS482','ALL_CA','Lunenburg','Lunenburg','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS483','ALL_CA','New Haven','New Haven','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS484','ALL_CA','Newtown','Newtown','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS486','ALL_CA','North East Margaree','North East Margaree','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS487','ALL_CA','Peggys Cove','Peggys Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS488','ALL_CA','Pleasant Valley','Pleasant Valley','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS489','ALL_CA','Point Edward','Point Edward','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS490','ALL_CA','Rose Bay','Rose Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS491','ALL_CA','Sandford','Sandford','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS492','ALL_CA','Wagmatcook','Wagmatcook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS493','ALL_CA','West Northfield','West Northfield','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS494','ALL_CA','Whycocomagh','Whycocomagh','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS495','ALL_CA','Wilmot Station','Wilmot Station','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS496','ALL_CA','Upper Rawdon','Upper Rawdon','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS497','ALL_CA','Timberlea','Timberlea','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS498','ALL_CA','Williamswood','Williamswood','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS499','ALL_CA','Sambro','Sambro','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS500','ALL_CA','Lower Woods Harbour','Lower Woods Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS501','ALL_CA','Middle Lahave','Middle Lahave','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS502','ALL_CA','Wileville','Wileville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS503','ALL_CA','Hebbville','Hebbville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS504','ALL_CA','Richmond','Richmond','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS505','ALL_CA','Auburn','Auburn','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS506','ALL_CA','River Ryan','River Ryan','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS507','ALL_CA','South Bar','South Bar','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS508','ALL_CA','Membertou','Membertou','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS509','ALL_CA','Belmont','Belmont','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS510','ALL_CA','Belnan','Belnan','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS511','ALL_CA','Mineville','Mineville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS512','ALL_CA','Dartmouth','Dartmouth','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS513','ALL_CA','Waverley','Waverley','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS514','ALL_CA','Round Island','Round Island','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS515','ALL_CA','Portuguese Cove','Portuguese Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS516','ALL_CA','Elmsdale','Elmsdale','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS517','ALL_CA','East Lawrencetown','East Lawrencetown','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS518','ALL_CA','Groves Point','Groves Point','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS519','ALL_CA','Alder Point','Alder Point','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS520','ALL_CA','Belle Cote','Belle Cote','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS521','ALL_CA','Oxford Junction','Oxford Junction','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS522','ALL_CA','Parrsboro','Parrsboro','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS523','ALL_CA','Stillwater Lake','Stillwater Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS524','ALL_CA','Indian Path','Indian Path','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS525','ALL_CA','Blacketts Lake','Blacketts Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS526','ALL_CA','French Road','French Road','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS527','ALL_CA','French Village','French Village','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS528','ALL_CA','Southside Boularderie','Southside Boularderie','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS529','ALL_CA','Mill Creek','Mill Creek','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS530','ALL_CA','Newcombville','Newcombville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS531','ALL_CA','Boularderie East','Boularderie East','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS532','ALL_CA','Capstick','Capstick','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS533','ALL_CA','Kingston','Kingston','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS534','ALL_CA','Grand Etang','Grand Etang','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS535','ALL_CA','Musquodoboit Harbour','Musquodoboit Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS536','ALL_CA','Tower Road','Tower Road','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS537','ALL_CA','Mabou','Mabou','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS538','ALL_CA','Barr Settlement','Barr Settlement','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS539','ALL_CA','Salt Springs','Salt Springs','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS540','ALL_CA','Hampton','Hampton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS541','ALL_CA','Lower l''Ardoise','Lower l''Ardoise','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS542','ALL_CA','East Preston','East Preston','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS543','ALL_CA','Avonport','Avonport','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS544','ALL_CA','Lower Five Islands','Lower Five Islands','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS545','ALL_CA','St Andrews Channel','St Andrews Channel','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS546','ALL_CA','Meteghan','Meteghan','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS547','ALL_CA','Coxheath','Coxheath','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS548','ALL_CA','Boisdale','Boisdale','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS549','ALL_CA','Juniper Mountain','Juniper Mountain','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS550','ALL_CA','Ste Croix','Ste Croix','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS551','ALL_CA','Fishermans Harbour','Fishermans Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS552','ALL_CA','Princeport','Princeport','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS553','ALL_CA','Ellershouse','Ellershouse','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS554','ALL_CA','Port Dufferin','Port Dufferin','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS555','ALL_CA','Afton Station','Afton Station','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS556','ALL_CA','Aspen','Aspen','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS557','ALL_CA','Blandford','Blandford','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS558','ALL_CA','Crousetown','Crousetown','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS559','ALL_CA','East Dover','East Dover','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS560','ALL_CA','Lower Sackville','Lower Sackville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS561','ALL_CA','Truro Heights','Truro Heights','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS562','ALL_CA','Freeport','Freeport','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS563','ALL_CA','Frenchvale','Frenchvale','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS564','ALL_CA','Great Village','Great Village','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS565','ALL_CA','Homeville','Homeville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS566','ALL_CA','Lexington','Lexington','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS567','ALL_CA','Newport','Newport','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS568','ALL_CA','Northside East Bay','Northside East Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS569','ALL_CA','Upper North River','Upper North River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS570','ALL_CA','Pleasant Lake','Pleasant Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS571','ALL_CA','Prospect Bay','Prospect Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS572','ALL_CA','Springfield','Springfield','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS573','ALL_CA','Tangier','Tangier','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS574','ALL_CA','Tiverton','Tiverton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS575','ALL_CA','Trenton','Trenton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS576','ALL_CA','Wellington','Wellington','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS577','ALL_CA','Windsor','Windsor','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS578','ALL_CA','Port la Tour','Port la Tour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS579','ALL_CA','Pubnico','Pubnico','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS580','ALL_CA','Middle Sackville','Middle Sackville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS581','ALL_CA','Kentville','Kentville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS582','ALL_CA','Middle West Pubnico','Middle West Pubnico','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS583','ALL_CA','Middle Porters Lake','Middle Porters Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS584','ALL_CA','Upper Hammonds Plains','Upper Hammonds Plains','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS585','ALL_CA','Midville Branch','Midville Branch','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS586','ALL_CA','Lower Northfield','Lower Northfield','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS587','ALL_CA','Dayton','Dayton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS588','ALL_CA','East Baccaro','East Baccaro','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS589','ALL_CA','East Bay','East Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS590','ALL_CA','Albert Bridge','Albert Bridge','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS591','ALL_CA','Truro','Truro','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS592','ALL_CA','Antigonish','Antigonish','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS593','ALL_CA','New Waterford','New Waterford','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS594','ALL_CA','Lower Branch','Lower Branch','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS595','ALL_CA','South Head','South Head','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS596','ALL_CA','Port Morien','Port Morien','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS597','ALL_CA','Scotsburn','Scotsburn','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS598','ALL_CA','Lake Loon','Lake Loon','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS599','ALL_CA','North Sydney','North Sydney','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS600','ALL_CA','Port Hastings','Port Hastings','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS601','ALL_CA','St Margaret Village','St Margaret Village','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS602','ALL_CA','Fourchu','Fourchu','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS603','ALL_CA','Margaree Forks','Margaree Forks','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS604','ALL_CA','Clyde River','Clyde River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS605','ALL_CA','Digby','Digby','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS606','ALL_CA','Bras d''Or','Bras d''Or','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS607','ALL_CA','Green Oaks','Green Oaks','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS608','ALL_CA','Centreville','Centreville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS609','ALL_CA','Northport','Northport','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS610','ALL_CA','Beaver River','Beaver River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS611','ALL_CA','St Andrews','St Andrews','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS612','ALL_CA','Shearwater','Shearwater','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS613','ALL_CA','Broughton','Broughton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS614','ALL_CA','Merigomish','Merigomish','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS615','ALL_CA','Western Shore','Western Shore','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS616','ALL_CA','Petit Etang','Petit Etang','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS617','ALL_CA','Port Clyde','Port Clyde','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS618','ALL_CA','Stoney Island','Stoney Island','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS619','ALL_CA','Milton Highlands','Milton Highlands','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS620','ALL_CA','Londonderry','Londonderry','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS621','ALL_CA','Hantsport','Hantsport','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS622','ALL_CA','Port Williams','Port Williams','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS623','ALL_CA','Saulnierville','Saulnierville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS624','ALL_CA','Laconia','Laconia','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS625','ALL_CA','Blockhouse','Blockhouse','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS626','ALL_CA','Cole Harbour','Cole Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS1','ALL_CA','Advocate Harbour','Advocate Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS2','ALL_CA','Bear Cove','Bear Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS3','ALL_CA','Big Pond','Big Pond','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS4','ALL_CA','Black Point','Black Point','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS5','ALL_CA','Boylston','Boylston','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS6','ALL_CA','Chelsea','Chelsea','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS7','ALL_CA','Conquerall Bank','Conquerall Bank','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS8','ALL_CA','Economy','Economy','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS9','ALL_CA','Falmouth','Falmouth','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS10','ALL_CA','Florence','Florence','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS11','ALL_CA','Granville Ferry','Granville Ferry','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS12','ALL_CA','Grass Cove','Grass Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS13','ALL_CA','Halifax','Halifax','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS14','ALL_CA','Hatchet Lake','Hatchet Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS15','ALL_CA','Jeddore Oyster Ponds','Jeddore Oyster Ponds','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS16','ALL_CA','Kemptown','Kemptown','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS17','ALL_CA','Lantz','Lantz','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS18','ALL_CA','Larrys River','Larrys River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS19','ALL_CA','Millbrook','Millbrook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS20','ALL_CA','New Canada','New Canada','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS21','ALL_CA','Oldham','Oldham','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS22','ALL_CA','Scotch Lake','Scotch Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS23','ALL_CA','South Ohio','South Ohio','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS24','ALL_CA','Sydney','Sydney','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS25','ALL_CA','Thomasville','Thomasville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS26','ALL_CA','Wedgeport','Wedgeport','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS27','ALL_CA','West Arichat','West Arichat','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS28','ALL_CA','West Bay Road','West Bay Road','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS29','ALL_CA','Tantallon','Tantallon','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS30','ALL_CA','Indian Harbour','Indian Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS31','ALL_CA','Branch Lahave','Branch Lahave','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS32','ALL_CA','Auburndale','Auburndale','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS33','ALL_CA','Grand Narrows','Grand Narrows','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS34','ALL_CA','Grand Pre','Grand Pre','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS35','ALL_CA','New Glasgow','New Glasgow','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS36','ALL_CA','Lawrencetown','Lawrencetown','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS37','ALL_CA','Troy','Troy','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS38','ALL_CA','Grand Lake','Grand Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS39','ALL_CA','Cape Negro','Cape Negro','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS40','ALL_CA','Main-A-Dieu','Main-A-Dieu','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS41','ALL_CA','Reserve Mines','Reserve Mines','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS42','ALL_CA','Fall River','Fall River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS43','ALL_CA','East Kemptville','East Kemptville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS44','ALL_CA','Upper Leitches Creek','Upper Leitches Creek','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS45','ALL_CA','Upper Musquodoboit','Upper Musquodoboit','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS46','ALL_CA','Upper Nine Mile River','Upper Nine Mile River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS47','ALL_CA','North West ARM','North West ARM','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS48','ALL_CA','Port Hood','Port Hood','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS49','ALL_CA','Port Hawkesbury','Port Hawkesbury','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS50','ALL_CA','Upper Chelsea','Upper Chelsea','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS51','ALL_CA','Overton','Overton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS52','ALL_CA','Cross Roads Country Harbour','Cross Roads Country Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS53','ALL_CA','Head of Jeddore','Head of Jeddore','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS54','ALL_CA','Margaree Centre','Margaree Centre','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS55','ALL_CA','Camden','Camden','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS56','ALL_CA','D''Escousse','D''Escousse','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS57','ALL_CA','Bayside','Bayside','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS58','ALL_CA','South West Margaree','South West Margaree','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS59','ALL_CA','McGraths Cove','McGraths Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS60','ALL_CA','McGray','McGray','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS61','ALL_CA','Central North River','Central North River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS62','ALL_CA','Deep Brook','Deep Brook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS63','ALL_CA','Upper Branch','Upper Branch','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS64','ALL_CA','Upper Brookside','Upper Brookside','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS65','ALL_CA','East Pennant','East Pennant','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS66','ALL_CA','Sunnybrae','Sunnybrae','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS67','ALL_CA','Shad Bay','Shad Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS68','ALL_CA','Upper Lahave','Upper Lahave','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS69','ALL_CA','Summerville.','Summerville.','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS70','ALL_CA','Pleasantville','Pleasantville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS71','ALL_CA','Pipers Cove','Pipers Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS72','ALL_CA','Port Caledonia','Port Caledonia','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS73','ALL_CA','River Philip','River Philip','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS74','ALL_CA','Ingonish','Ingonish','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS75','ALL_CA','Ingonish Beach','Ingonish Beach','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS76','ALL_CA','Little Brook','Little Brook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS77','ALL_CA','Liverpool','Liverpool','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS78','ALL_CA','Deerfield','Deerfield','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS79','ALL_CA','Weymouth','Weymouth','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS80','ALL_CA','Five Islands','Five Islands','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS81','ALL_CA','Loch Lomond','Loch Lomond','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS82','ALL_CA','Lockeport','Lockeport','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS83','ALL_CA','Prospect Village','Prospect Village','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS84','ALL_CA','Westchester Station','Westchester Station','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS85','ALL_CA','Barrington','Barrington','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS86','ALL_CA','Barton','Barton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS87','ALL_CA','Blind Bay','Blind Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS88','ALL_CA','Cedar Lake','Cedar Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS89','ALL_CA','Clementsport','Clementsport','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS90','ALL_CA','Crowell','Crowell','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS91','ALL_CA','Debert','Debert','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS92','ALL_CA','Old Barns','Old Barns','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS93','ALL_CA','Grand River','Grand River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS94','ALL_CA','Howie Center','Howie Center','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS95','ALL_CA','Middlewood','Middlewood','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS96','ALL_CA','Molega Lake','Molega Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS97','ALL_CA','Mulgrave','Mulgrave','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS98','ALL_CA','North East Point','North East Point','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS99','ALL_CA','Upper North Sydney','Upper North Sydney','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS100','ALL_CA','Upper Northfield','Upper Northfield','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS101','ALL_CA','Oakfield','Oakfield','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS102','ALL_CA','Sandfield','Sandfield','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS103','ALL_CA','Sandy Cove','Sandy Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS104','ALL_CA','Smiths Cove','Smiths Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS105','ALL_CA','Spectacle Lakes','Spectacle Lakes','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS106','ALL_CA','West Bay','West Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS107','ALL_CA','Westville','Westville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS108','ALL_CA','Little Lorraine','Little Lorraine','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS109','ALL_CA','Herring Cove','Herring Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS110','ALL_CA','Sampson Cove','Sampson Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS111','ALL_CA','Lower Wedgeport','Lower Wedgeport','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS112','ALL_CA','Bedford','Bedford','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS113','ALL_CA','Beaver Cove','Beaver Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS114','ALL_CA','Waterloo','Waterloo','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS115','ALL_CA','Rhodes Corner','Rhodes Corner','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS116','ALL_CA','Green Bay','Green Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS117','ALL_CA','Grand Mira South','Grand Mira South','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS118','ALL_CA','Gardiner Mines','Gardiner Mines','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS119','ALL_CA','Big Ridge','Big Ridge','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS120','ALL_CA','Marion Bridge','Marion Bridge','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS121','ALL_CA','Craigmore','Craigmore','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS122','ALL_CA','Ironville','Ironville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS123','ALL_CA','Carleton','Carleton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS124','ALL_CA','Porters Lake','Porters Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS125','ALL_CA','West River Station','West River Station','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS126','ALL_CA','Dominion','Dominion','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS127','ALL_CA','Scotchtown','Scotchtown','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS128','ALL_CA','Riversdale','Riversdale','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS129','ALL_CA','Paradise','Paradise','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS130','ALL_CA','Enfield','Enfield','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS131','ALL_CA','Nine Mile River','Nine Mile River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS132','ALL_CA','Hillview','Hillview','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS133','ALL_CA','Beechmont','Beechmont','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS134','ALL_CA','Beechville','Beechville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS135','ALL_CA','Milford Station','Milford Station','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS136','ALL_CA','North Preston','North Preston','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS137','ALL_CA','Bass River','Bass River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS138','ALL_CA','Petite Riviere','Petite Riviere','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS139','ALL_CA','Black Rock','Black Rock','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS140','ALL_CA','Springhill','Springhill','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS141','ALL_CA','Camperdown','Camperdown','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS142','ALL_CA','Malagash','Malagash','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS143','ALL_CA','Hubley','Hubley','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS144','ALL_CA','Mackinnons Harbour','Mackinnons Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS145','ALL_CA','River Bourgeois','River Bourgeois','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS146','ALL_CA','Southampton','Southampton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS147','ALL_CA','Upper Sackville','Upper Sackville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS148','ALL_CA','Clam Point','Clam Point','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS149','ALL_CA','Barra Glen','Barra Glen','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS150','ALL_CA','Goodwood','Goodwood','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS151','ALL_CA','Lake Charlotte','Lake Charlotte','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS152','ALL_CA','Cheverie','Cheverie','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS153','ALL_CA','Maitland','Maitland','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS154','ALL_CA','Victoria Mines','Victoria Mines','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS155','ALL_CA','Meteghan Centre','Meteghan Centre','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS156','ALL_CA','Petit de Grat','Petit de Grat','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS157','ALL_CA','East Gore','East Gore','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS158','ALL_CA','Wallace','Wallace','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS159','ALL_CA','Point Tupper','Point Tupper','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS160','ALL_CA','Little Bras d''Or','Little Bras d''Or','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS161','ALL_CA','Aylesford','Aylesford','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS162','ALL_CA','St Peters','St Peters','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS163','ALL_CA','Ste-Anne-du-Ruisseau','Ste-Anne-du-Ruisseau','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS164','ALL_CA','Framboise','Framboise','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS165','ALL_CA','Arichat','Arichat','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS166','ALL_CA','Darlings Lake','Darlings Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS167','ALL_CA','Bear River','Bear River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS168','ALL_CA','Ben Eoin','Ben Eoin','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS169','ALL_CA','Clifton','Clifton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS170','ALL_CA','Cow Bay','Cow Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS171','ALL_CA','Lower Truro','Lower Truro','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS172','ALL_CA','Fortress of Louisbourg','Fortress of Louisbourg','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS173','ALL_CA','Frankville','Frankville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS174','ALL_CA','Goshen','Goshen','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS175','ALL_CA','Halibut Bay','Halibut Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS176','ALL_CA','Isaacs Harbour','Isaacs Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS177','ALL_CA','Kempt Head','Kempt Head','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS178','ALL_CA','Kemptville','Kemptville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS179','ALL_CA','Lahave','Lahave','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS180','ALL_CA','Liscomb','Liscomb','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS181','ALL_CA','Macadams Lake','Macadams Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS182','ALL_CA','Manganese Mines','Manganese Mines','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS183','ALL_CA','New Campbellton','New Campbellton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS184','ALL_CA','Newport Station','Newport Station','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS185','ALL_CA','Onslow Mountain','Onslow Mountain','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS186','ALL_CA','Prime Brook','Prime Brook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS187','ALL_CA','Pugwash','Pugwash','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS188','ALL_CA','Pugwash Junction','Pugwash Junction','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS189','ALL_CA','Shenacadie','Shenacadie','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS190','ALL_CA','Tancook Island','Tancook Island','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS191','ALL_CA','Wolfville','Wolfville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS192','ALL_CA','Yarmouth','Yarmouth','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS193','ALL_CA','West Dover','West Dover','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS194','ALL_CA','Boutiliers Point','Boutiliers Point','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS195','ALL_CA','Upper Grand Mira','Upper Grand Mira','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS196','ALL_CA','Upper Kennetcook','Upper Kennetcook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS197','ALL_CA','Monastery','Monastery','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS198','ALL_CA','Dayspring','Dayspring','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS199','ALL_CA','Cherry Brook','Cherry Brook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS200','ALL_CA','Big Pond Centre','Big Pond Centre','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS201','ALL_CA','Louisbourg','Louisbourg','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS202','ALL_CA','Port Greville','Port Greville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS203','ALL_CA','Lapland','Lapland','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS204','ALL_CA','New Germany','New Germany','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS205','ALL_CA','Bible Hill','Bible Hill','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS206','ALL_CA','Big Beach','Big Beach','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS207','ALL_CA','Jamesville','Jamesville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS208','ALL_CA','Sydney River','Sydney River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS209','ALL_CA','Inverness','Inverness','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS210','ALL_CA','Pleasant Bay','Pleasant Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS211','ALL_CA','Whites Lake','Whites Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS212','ALL_CA','Mira Road','Mira Road','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS213','ALL_CA','Cape Dauphin','Cape Dauphin','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS214','ALL_CA','Sheet Harbour','Sheet Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS215','ALL_CA','Scotch Village','Scotch Village','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS216','ALL_CA','Highland Hill','Highland Hill','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS217','ALL_CA','Hopewell','Hopewell','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS218','ALL_CA','Margaree','Margaree','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS219','ALL_CA','Margaree Valley','Margaree Valley','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS220','ALL_CA','Sherbrooke','Sherbrooke','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS221','ALL_CA','Danesville','Danesville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS222','ALL_CA','Upper Stewiacke','Upper Stewiacke','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS223','ALL_CA','Central Onslow','Central Onslow','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS224','ALL_CA','Lakeview','Lakeview','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS225','ALL_CA','Lower Onslow','Lower Onslow','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS226','ALL_CA','Neils Harbour','Neils Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS227','ALL_CA','Berwick','Berwick','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS228','ALL_CA','Queensville','Queensville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS229','ALL_CA','Judique','Judique','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS230','ALL_CA','Meteghan River','Meteghan River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS231','ALL_CA','Annapolis Royal','Annapolis Royal','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS232','ALL_CA','Caribou Marsh','Caribou Marsh','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS233','ALL_CA','Wentzells Lake','Wentzells Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS234','ALL_CA','L''Ardoise','L''Ardoise','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS235','ALL_CA','Nappan','Nappan','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS236','ALL_CA','Ingomar','Ingomar','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS237','ALL_CA','New Harris','New Harris','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS238','ALL_CA','Tatamagouche','Tatamagouche','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS239','ALL_CA','Walton','Walton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS240','ALL_CA','Islandview','Islandview','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS241','ALL_CA','Red Point','Red Point','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS242','ALL_CA','Christmas Island','Christmas Island','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS243','ALL_CA','Duncans Cove','Duncans Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS244','ALL_CA','Barrington Passage','Barrington Passage','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS245','ALL_CA','Bateston','Bateston','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS246','ALL_CA','Birch Grove','Birch Grove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS247','ALL_CA','Brooklyn','Brooklyn','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS248','ALL_CA','Cambridge','Cambridge','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS249','ALL_CA','Clarks Harbour','Clarks Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS250','ALL_CA','Cookville','Cookville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS251','ALL_CA','Dalem Lake','Dalem Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS252','ALL_CA','Densmores Mills','Densmores Mills','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS253','ALL_CA','East Mountain','East Mountain','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS254','ALL_CA','Hacketts Cove','Hacketts Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS255','ALL_CA','Harrietsfield','Harrietsfield','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS256','ALL_CA','Joggins','Joggins','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS257','ALL_CA','Brookside','Brookside','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS258','ALL_CA','Big Bras d''Or','Big Bras d''Or','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS259','ALL_CA','Leitches Creek','Leitches Creek','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS260','ALL_CA','Greenfield','Greenfield','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS261','ALL_CA','Maccan','Maccan','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS262','ALL_CA','Micmac','Micmac','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS263','ALL_CA','North River','North River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS264','ALL_CA','Upper Onslow','Upper Onslow','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS265','ALL_CA','Nuttby','Nuttby','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS266','ALL_CA','Orangedale','Orangedale','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS267','ALL_CA','Osborne Harbour','Osborne Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS268','ALL_CA','Pinehurst','Pinehurst','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS269','ALL_CA','Point Aconi','Point Aconi','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS270','ALL_CA','Ross Ferry','Ross Ferry','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS271','ALL_CA','Fergusons Cove','Fergusons Cove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS272','ALL_CA','Glen Margaret','Glen Margaret','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS273','ALL_CA','Upper Tantallon','Upper Tantallon','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS274','ALL_CA','Lower West Pubnico','Lower West Pubnico','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS275','ALL_CA','Middle Musquodoboit','Middle Musquodoboit','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS276','ALL_CA','Pine Grove','Pine Grove','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS277','ALL_CA','Bridgewater','Bridgewater','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS278','ALL_CA','Bridgetown','Bridgetown','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS279','ALL_CA','Westmount','Westmount','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS280','ALL_CA','Eastern Passage','Eastern Passage','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS281','ALL_CA','West Porters Lake','West Porters Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS282','ALL_CA','Riverport','Riverport','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS283','ALL_CA','East Lahave','East Lahave','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS284','ALL_CA','Gillis Point','Gillis Point','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS285','ALL_CA','Bickerton West','Bickerton West','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS286','ALL_CA','Mavillette','Mavillette','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS287','ALL_CA','Salmon River.','Salmon River.','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS288','ALL_CA','Buckfield','Buckfield','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS289','ALL_CA','New Ross','New Ross','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS290','ALL_CA','Lydgate','Lydgate','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS291','ALL_CA','Little River','Little River','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS292','ALL_CA','Mill Village','Mill Village','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS293','ALL_CA','Marie Joseph','Marie Joseph','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS294','ALL_CA','Murray Siding','Murray Siding','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS295','ALL_CA','Upper Washabuck','Upper Washabuck','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS296','ALL_CA','McCallum Settlement','McCallum Settlement','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS297','ALL_CA','Dutch Brook','Dutch Brook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS298','ALL_CA','Ketch Harbour','Ketch Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS299','ALL_CA','Maitland Bridge','Maitland Bridge','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS300','ALL_CA','Portage','Portage','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS301','ALL_CA','Montague Gold Mines','Montague Gold Mines','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS302','ALL_CA','Lewis Lake','Lewis Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS303','ALL_CA','Jordan Falls','Jordan Falls','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS304','ALL_CA','Westphal','Westphal','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS305','ALL_CA','St-Joseph-du-Moine','St-Joseph-du-Moine','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS306','ALL_CA','Windsor Junction','Windsor Junction','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS307','ALL_CA','Port Joli','Port Joli','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS308','ALL_CA','St Columba','St Columba','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS309','ALL_CA','Washabuck Centre','Washabuck Centre','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS310','ALL_CA','River Hebert East','River Hebert East','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS311','ALL_CA','River John','River John','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS312','ALL_CA','Collingwood Corner','Collingwood Corner','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS313','ALL_CA','Caledonia','Caledonia','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS314','ALL_CA','Goldboro','Goldboro','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS315','ALL_CA','Oxford','Oxford','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS316','ALL_CA','Mooseland','Mooseland','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS317','ALL_CA','Irishvale','Irishvale','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS318','ALL_CA','Canning','Canning','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS319','ALL_CA','Iona','Iona','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS320','ALL_CA','Arcadia','Arcadia','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS321','ALL_CA','Barss Corner','Barss Corner','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS322','ALL_CA','Brooklyn.','Brooklyn.','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS323','ALL_CA','Creignish','Creignish','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS324','ALL_CA','Elderbank','Elderbank','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS325','ALL_CA','Enon','Enon','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS326','ALL_CA','Eskasoni','Eskasoni','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS327','ALL_CA','Glace Bay','Glace Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS328','ALL_CA','Greenwood','Greenwood','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS329','ALL_CA','Middle Cape','Middle Cape','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS330','ALL_CA','New Victoria','New Victoria','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS331','ALL_CA','Oakhill','Oakhill','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS332','ALL_CA','Prospect','Prospect','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS333','ALL_CA','Shag Harbour','Shag Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS334','ALL_CA','Shubenacadie','Shubenacadie','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS335','ALL_CA','Stirling','Stirling','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS336','ALL_CA','Wellington.','Wellington.','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS337','ALL_CA','Westport','Westport','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS338','ALL_CA','Whynotts Settlement','Whynotts Settlement','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS339','ALL_CA','Harmony','Harmony','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS340','ALL_CA','Little Dover','Little Dover','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS341','ALL_CA','Plympton','Plympton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS342','ALL_CA','Terence Bay','Terence Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS343','ALL_CA','Seabright','Seabright','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS344','ALL_CA','Beaver Bank','Beaver Bank','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS345','ALL_CA','Lower Washabuck','Lower Washabuck','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS346','ALL_CA','Italy Cross','Italy Cross','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS347','ALL_CA','Conquerall Mills','Conquerall Mills','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS348','ALL_CA','Fletchers Lake','Fletchers Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS349','ALL_CA','Lingan','Lingan','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS350','ALL_CA','West Pubnico','West Pubnico','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS351','ALL_CA','Port Mouton','Port Mouton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS352','ALL_CA','Cape North','Cape North','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS353','ALL_CA','Catalone Gut','Catalone Gut','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS354','ALL_CA','Middleton','Middleton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS355','ALL_CA','Wentworth','Wentworth','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS356','ALL_CA','Englishtown','Englishtown','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS357','ALL_CA','Gillis Lake','Gillis Lake','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS358','ALL_CA','Long Point','Long Point','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS359','ALL_CA','Edwardsville','Edwardsville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS360','ALL_CA','Church Point','Church Point','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS361','ALL_CA','Alder Plains','Alder Plains','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS362','ALL_CA','Milton','Milton','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS363','ALL_CA','Dingwall','Dingwall','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS364','ALL_CA','Glenwood','Glenwood','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS365','ALL_CA','Mira Gut','Mira Gut','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS366','ALL_CA','Tusket','Tusket','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS367','ALL_CA','Castle Bay','Castle Bay','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS368','ALL_CA','Head of Chezzetcook','Head of Chezzetcook','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS369','ALL_CA','Pictou Island','Pictou Island','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS370','ALL_CA','Margaree Harbour','Margaree Harbour','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS371','ALL_CA','Margaretsville','Margaretsville','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS372','ALL_CA','Currys Corner','Currys Corner','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS373','ALL_CA','Boularderie Center','Boularderie Center','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS374','ALL_CA','Centre Burlington','Centre Burlington','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS375','ALL_CA','Mackdale','Mackdale','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS376','ALL_CA','Kinsac','Kinsac','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS377','ALL_CA','Grand Mira North','Grand Mira North','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS378','ALL_CA','River Denys','River Denys','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS379','ALL_CA','South Brookfield','South Brookfield','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS380','ALL_CA','Havre Boucher','Havre Boucher','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS381','ALL_CA','Canso','Canso','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS382','ALL_CA','Lake Echo','Lake Echo','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS383','ALL_CA','Barrachois','Barrachois','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS384','ALL_CA','Baker Settlement','Baker Settlement','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS385','ALL_CA','Cheticamp','Cheticamp','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS386','ALL_CA','Lower East Pubnico','Lower East Pubnico','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS387','ALL_CA','Baddeck','Baddeck','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS388','ALL_CA','Labelle','Labelle','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('NS485','ALL_CA','Noel','Noel','NS','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0);
commit;