insert into YFS_REGION (REGION_KEY,REGION_SCHEMA_KEY,REGION_NAME,REGION_DESCRIPTION,PARENT_REGION_KEY,REGION_LEVEL_NAME,CAN_AGGREGATE,CREATEUSERID, MODIFYUSERID, CREATEPROGID, MODIFYPROGID, LOCKID)VALUES

('AB','ALL_CA','AB','AB','CAN','State','Y','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB50','ALL_CA','Musidora','Musidora','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB51','ALL_CA','Nestow','Nestow','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB52','ALL_CA','Wimborne','Wimborne','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB53','ALL_CA','Mundare','Mundare','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB54','ALL_CA','Brazeau County','Brazeau County','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB55','ALL_CA','Lac des Arcs','Lac des Arcs','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB56','ALL_CA','Dead Man''s Flats','Dead Man''s Flats','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB57','ALL_CA','Barnwell','Barnwell','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB58','ALL_CA','Barons','Barons','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB59','ALL_CA','Rivercourse','Rivercourse','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB60','ALL_CA','Ohaton','Ohaton','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB61','ALL_CA','Arrowwood','Arrowwood','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB62','ALL_CA','Tiger Lily','Tiger Lily','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB63','ALL_CA','Sunnybrook','Sunnybrook','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB64','ALL_CA','Donnelly','Donnelly','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB65','ALL_CA','Joussard','Joussard','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB66','ALL_CA','Purple Springs','Purple Springs','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB67','ALL_CA','Bellevue','Bellevue','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB68','ALL_CA','Gundy','Gundy','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB69','ALL_CA','St Vincent','St Vincent','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB70','ALL_CA','Opal','Opal','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB390','ALL_CA','Devon','Devon','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB391','ALL_CA','Vimy','Vimy','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB392','ALL_CA','Vilna','Vilna','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB393','ALL_CA','Bittern Lake','Bittern Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB394','ALL_CA','Grouard','Grouard','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB395','ALL_CA','Penhold','Penhold','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB396','ALL_CA','Bluffton','Bluffton','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB397','ALL_CA','Innisfail','Innisfail','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB398','ALL_CA','Lone Pine','Lone Pine','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB399','ALL_CA','Nanton','Nanton','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB400','ALL_CA','Meander River','Meander River','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB401','ALL_CA','St Lina','St Lina','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB402','ALL_CA','Gem','Gem','B','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB403','ALL_CA','Lomond','Lomond','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB404','ALL_CA','Youngstown','Youngstown','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB405','ALL_CA','Edmonton International Airport','Edmonton International Airport','','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB406','ALL_CA','Bonnyville','Bonnyville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB407','ALL_CA','Dewberry','Dewberry','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB408','ALL_CA','Sputinow','Sputinow','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB409','ALL_CA','Brocket','Brocket','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB410','ALL_CA','Dapp','Dapp','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB411','ALL_CA','Elmworth','Elmworth','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB412','ALL_CA','Valleyview','Valleyview','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB413','ALL_CA','Frog Lake','Frog Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB414','ALL_CA','Glenevis','Glenevis','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB415','ALL_CA','High Level','High Level','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB416','ALL_CA','Hinton','Hinton','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB417','ALL_CA','Killam','Killam','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB418','ALL_CA','La Glace','La Glace','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB419','ALL_CA','Lloydminster','Lloydminster','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB420','ALL_CA','Onefour','Onefour','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB421','ALL_CA','Ranfurly','Ranfurly','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB422','ALL_CA','Seba Beach','Seba Beach','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB423','ALL_CA','Stavely','Stavely','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB424','ALL_CA','Twin Butte','Twin Butte','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB425','ALL_CA','Walsh','Walsh','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB426','ALL_CA','Warburg','Warburg','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB427','ALL_CA','Waskatenau','Waskatenau','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB428','ALL_CA','Bowden','Bowden','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB429','ALL_CA','Heinsburg','Heinsburg','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB430','ALL_CA','New Norway','New Norway','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB431','ALL_CA','Cherry Grove','Cherry Grove','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB432','ALL_CA','South Baptiste','South Baptiste','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB433','ALL_CA','Irricana','Irricana','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB434','ALL_CA','Round Hill','Round Hill','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB435','ALL_CA','Burdett','Burdett','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB436','ALL_CA','Fort Chipewyan','Fort Chipewyan','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB437','ALL_CA','Cardston','Cardston','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB438','ALL_CA','Bassano','Bassano','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB584','ALL_CA','Calais','Calais','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB585','ALL_CA','Sunnynook','Sunnynook','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB586','ALL_CA','Exshaw','Exshaw','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB587','ALL_CA','McRae','McRae','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB588','ALL_CA','Pincher Creek','Pincher Creek','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB589','ALL_CA','Leslieville','Leslieville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB590','ALL_CA','Ardrossan','Ardrossan','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB591','ALL_CA','Amisk','Amisk','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB592','ALL_CA','Egremont','Egremont','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB593','ALL_CA','Grimshaw','Grimshaw','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB594','ALL_CA','Orion','Orion','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB595','ALL_CA','Blue Ridge','Blue Ridge','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB596','ALL_CA','Gunn','Gunn','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB597','ALL_CA','Guy','Guy','B','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB598','ALL_CA','Calgary','Calgary','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB599','ALL_CA','St Paul','St Paul','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB600','ALL_CA','Ellscott','Ellscott','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB601','ALL_CA','Wandering River','Wandering River','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB602','ALL_CA','Red Earth Creek','Red Earth Creek','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB603','ALL_CA','Rocky Rapids','Rocky Rapids','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB604','ALL_CA','Whitecourt','Whitecourt','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB605','ALL_CA','Fort Vermilion','Fort Vermilion','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB606','ALL_CA','Hotchkiss','Hotchkiss','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB607','ALL_CA','Kananaskis','Kananaskis','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB608','ALL_CA','Kelsey','Kelsey','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB609','ALL_CA','Hayter','Hayter','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB245','ALL_CA','Rocky View County','Rocky View County','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB246','ALL_CA','Tees','Tees','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB247','ALL_CA','Red Willow','Red Willow','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB248','ALL_CA','Drayton Valley','Drayton Valley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB249','ALL_CA','Cranford','Cranford','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB250','ALL_CA','Clairmont','Clairmont','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB251','ALL_CA','Veinerville','Veinerville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB252','ALL_CA','North Star','North Star','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB253','ALL_CA','Breton','Breton','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB254','ALL_CA','Compeer','Compeer','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB255','ALL_CA','Armena','Armena','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB256','ALL_CA','Benalto','Benalto','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB257','ALL_CA','Bentley','Bentley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB258','ALL_CA','Breynat','Breynat','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB259','ALL_CA','Castor','Castor','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB260','ALL_CA','Coaldale','Coaldale','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB261','ALL_CA','Cypress County','Cypress County','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB262','ALL_CA','Edberg','Edberg','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB263','ALL_CA','Entwistle','Entwistle','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB264','ALL_CA','Fairview','Fairview','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB265','ALL_CA','Foisy','Foisy','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB266','ALL_CA','Forestburg','Forestburg','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB267','ALL_CA','Grassy Lake','Grassy Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB268','ALL_CA','Halfmoon Bay','Halfmoon Bay','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB269','ALL_CA','Huxley','Huxley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB270','ALL_CA','Island Lake','Island Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB271','ALL_CA','Nevis','Nevis','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB272','ALL_CA','Newbrook','Newbrook','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB273','ALL_CA','Radway','Radway','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB274','ALL_CA','Raymond','Raymond','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB275','ALL_CA','Redwater','Redwater','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB276','ALL_CA','Rochon Sands','Rochon Sands','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB277','ALL_CA','Rolling Hills','Rolling Hills','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB278','ALL_CA','Rycroft','Rycroft','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB279','ALL_CA','Spring Coulee','Spring Coulee','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB280','ALL_CA','Tulliby Lake','Tulliby Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB281','ALL_CA','Worsley','Worsley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB282','ALL_CA','Yellowhead County','Yellowhead County','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB283','ALL_CA','Gainford','Gainford','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB284','ALL_CA','Botha','Botha','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB285','ALL_CA','Milk River','Milk River','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB286','ALL_CA','Little Smoky','Little Smoky','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB287','ALL_CA','Crooked Creek','Crooked Creek','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB288','ALL_CA','Nordegg','Nordegg','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB289','ALL_CA','Wabasca','Wabasca','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB290','ALL_CA','Edgerton','Edgerton','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB291','ALL_CA','Hill Spring','Hill Spring','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB292','ALL_CA','Carvel','Carvel','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB439','ALL_CA','Blackfalds','Blackfalds','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB440','ALL_CA','Camrose','Camrose','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB441','ALL_CA','Hillcrest Mines','Hillcrest Mines','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB442','ALL_CA','Sunset Beach','Sunset Beach','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB443','ALL_CA','Wrentham','Wrentham','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB444','ALL_CA','Maleb','Maleb','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB445','ALL_CA','Lethbridge','Lethbridge','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB446','ALL_CA','Ma-Me-O Beach','Ma-Me-O Beach','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB447','ALL_CA','Lac La Biche','Lac La Biche','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB448','ALL_CA','Foremost','Foremost','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB449','ALL_CA','New Dayton','New Dayton','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB450','ALL_CA','Keg River','Keg River','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB451','ALL_CA','Balzac','Balzac','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB452','ALL_CA','Banff','Banff','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB453','ALL_CA','Tofield','Tofield','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB454','ALL_CA','Gleichen','Gleichen','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB455','ALL_CA','Busby','Busby','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB456','ALL_CA','Grande Cache','Grande Cache','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB457','ALL_CA','Mirror','Mirror','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB458','ALL_CA','La Corey','La Corey','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB459','ALL_CA','Metiskow','Metiskow','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB460','ALL_CA','Harvie Heights','Harvie Heights','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB461','ALL_CA','Bellis','Bellis','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB462','ALL_CA','Airdrie','Airdrie','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB463','ALL_CA','Eureka River','Eureka River','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB464','ALL_CA','Streamstown','Streamstown','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB465','ALL_CA','Rainier','Rainier','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB466','ALL_CA','Thorhild','Thorhild','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB467','ALL_CA','St Isidore','St Isidore','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB468','ALL_CA','Hobbema','Hobbema','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB469','ALL_CA','Morinville','Morinville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB470','ALL_CA','Morley','Morley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB471','ALL_CA','Peace River','Peace River','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB472','ALL_CA','Vega','Vega','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB473','ALL_CA','Vegreville','Vegreville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB474','ALL_CA','Elkwater','Elkwater','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB475','ALL_CA','Athabasca','Athabasca','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB476','ALL_CA','Kitscoty','Kitscoty','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB477','ALL_CA','Anzac','Anzac','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB478','ALL_CA','Ashmont','Ashmont','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB479','ALL_CA','Boyle','Boyle','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB480','ALL_CA','Caslan','Caslan','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB481','ALL_CA','Cremona','Cremona','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB482','ALL_CA','Driftpile','Driftpile','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB483','ALL_CA','Eden Valley','Eden Valley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB484','ALL_CA','Edmonton','Edmonton','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB485','ALL_CA','Elk Point','Elk Point','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB486','ALL_CA','Enoch','Enoch','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB487','ALL_CA','Evansburg','Evansburg','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB2','ALL_CA','Bawlf','Bawlf','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB3','ALL_CA','Bindloss','Bindloss','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB4','ALL_CA','Boyne Lake','Boyne Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB5','ALL_CA','Brant','Brant','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB6','ALL_CA','Buck Creek','Buck Creek','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB7','ALL_CA','Carrot Creek','Carrot Creek','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB8','ALL_CA','Debolt','Debolt','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB9','ALL_CA','Drumheller','Drumheller','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB10','ALL_CA','East Coulee','East Coulee','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB11','ALL_CA','Enchant','Enchant','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB12','ALL_CA','Falher','Falher','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB13','ALL_CA','Falun','Falun','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB14','ALL_CA','Fenn','Fenn','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB15','ALL_CA','Fort McMurray','Fort McMurray','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB16','ALL_CA','Galahad','Galahad','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB17','ALL_CA','Glendon','Glendon','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB18','ALL_CA','Granum','Granum','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB19','ALL_CA','High Prairie','High Prairie','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB20','ALL_CA','Holden','Holden','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB21','ALL_CA','Hughenden','Hughenden','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB22','ALL_CA','John d''or Prairie','John d''or Prairie','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB23','ALL_CA','Millicent','Millicent','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB24','ALL_CA','Lancaster Park','Lancaster Park','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB25','ALL_CA','Meeting Creek','Meeting Creek','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB26','ALL_CA','Norglenwold','Norglenwold','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB27','ALL_CA','Onoway','Onoway','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB28','ALL_CA','Spedden','Spedden','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB29','ALL_CA','Stettler','Stettler','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB30','ALL_CA','Strathmore','Strathmore','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB31','ALL_CA','Tangent','Tangent','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB32','ALL_CA','Valhalla Centre','Valhalla Centre','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB33','ALL_CA','Wainwright','Wainwright','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB34','ALL_CA','Donalda','Donalda','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB35','ALL_CA','Lougheed','Lougheed','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB36','ALL_CA','Lake Louise','Lake Louise','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB37','ALL_CA','Lake Newell Resort','Lake Newell Resort','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB38','ALL_CA','Hines Creek','Hines Creek','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB39','ALL_CA','Alix','Alix','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB40','ALL_CA','Fort Assiniboine','Fort Assiniboine','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB41','ALL_CA','Colinton','Colinton','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB42','ALL_CA','Ponoka','Ponoka','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB43','ALL_CA','Derwent','Derwent','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB44','ALL_CA','Lyalta','Lyalta','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB45','ALL_CA','Smoky Lake','Smoky Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB46','ALL_CA','Calmar','Calmar','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB47','ALL_CA','Cluny','Cluny','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB48','ALL_CA','Morrin','Morrin','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB49','ALL_CA','Aden','Aden','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB71','ALL_CA','Daysland','Daysland','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB72','ALL_CA','Wanham','Wanham','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB73','ALL_CA','Duchess','Duchess','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB74','ALL_CA','Fitzgerald','Fitzgerald','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB75','ALL_CA','Spring Lake','Spring Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB76','ALL_CA','Lacombe County','Lacombe County','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB77','ALL_CA','Leduc County','Leduc County','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB78','ALL_CA','Edson','Edson','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB79','ALL_CA','Niton Junction','Niton Junction','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB80','ALL_CA','Abee','Abee','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB81','ALL_CA','Spruce View','Spruce View','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB82','ALL_CA','Black Diamond','Black Diamond','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB83','ALL_CA','Whitelaw','Whitelaw','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB84','ALL_CA','Aetna','Aetna','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB85','ALL_CA','Brownvale','Brownvale','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB86','ALL_CA','Bruce','Bruce','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB87','ALL_CA','Bruderheim','Bruderheim','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB88','ALL_CA','Carbon','Carbon','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB89','ALL_CA','Carseland','Carseland','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB90','ALL_CA','Carstairs','Carstairs','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB91','ALL_CA','Cleardale','Cleardale','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB92','ALL_CA','Cynthia','Cynthia','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB93','ALL_CA','Empress','Empress','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB94','ALL_CA','Fort Macleod','Fort Macleod','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB95','ALL_CA','Fox Creek','Fox Creek','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB96','ALL_CA','Hilliard','Hilliard','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB97','ALL_CA','Island Lake South','Island Lake South','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB98','ALL_CA','Lindbergh','Lindbergh','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB99','ALL_CA','Marwayne','Marwayne','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB100','ALL_CA','Mossleigh','Mossleigh','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB101','ALL_CA','Mountain View','Mountain View','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB102','ALL_CA','Red Deer','Red Deer','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB103','ALL_CA','Robb','Robb','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB104','ALL_CA','Rosedale Valley','Rosedale Valley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB105','ALL_CA','Rumsey','Rumsey','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB106','ALL_CA','Ryley','Ryley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB107','ALL_CA','Saddle Lake','Saddle Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB108','ALL_CA','Tawatinaw','Tawatinaw','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB109','ALL_CA','Vermilion','Vermilion','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB110','ALL_CA','Wostok','Wostok','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB111','ALL_CA','Stand Off','Stand Off','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB112','ALL_CA','Willingdon','Willingdon','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB113','ALL_CA','Cooking Lake','Cooking Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB114','ALL_CA','Big Valley','Big Valley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB115','ALL_CA','Craigmyle','Craigmyle','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB116','ALL_CA','Winfield','Winfield','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB117','ALL_CA','Alder Flats','Alder Flats','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB118','ALL_CA','Redcliff','Redcliff','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB119','ALL_CA','Pine Lake','Pine Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB120','ALL_CA','Legal','Legal','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB121','ALL_CA','Trout Lake','Trout Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB122','ALL_CA','Alliance','Alliance','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB123','ALL_CA','Pollockville','Pollockville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB124','ALL_CA','Alberta Beach','Alberta Beach','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB125','ALL_CA','Zama City','Zama City','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB126','ALL_CA','Millarville','Millarville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB127','ALL_CA','Hardisty','Hardisty','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB128','ALL_CA','Mallaig','Mallaig','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB129','ALL_CA','Cadotte Lake','Cadotte Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB130','ALL_CA','Woking','Woking','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB131','ALL_CA','Myrnam','Myrnam','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB132','ALL_CA','Jarvie','Jarvie','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB133','ALL_CA','Jasper','Jasper','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB134','ALL_CA','St Brides','St Brides','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB135','ALL_CA','Bodo','Bodo','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB136','ALL_CA','MD Of Bonnyville','MD Of Bonnyville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB137','ALL_CA','Namao','Namao','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB138','ALL_CA','Nampa','Nampa','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB139','ALL_CA','Milo','Milo','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB140','ALL_CA','Watino','Watino','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB141','ALL_CA','Dunmore','Dunmore','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB142','ALL_CA','Tilley','Tilley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB143','ALL_CA','Gordondale','Gordondale','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB144','ALL_CA','Sexsmith','Sexsmith','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB145','ALL_CA','Sedgewick','Sedgewick','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB146','ALL_CA','Berwyn','Berwyn','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB147','ALL_CA','Grovedale','Grovedale','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB148','ALL_CA','Fawcett','Fawcett','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB149','ALL_CA','Delburne','Delburne','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB150','ALL_CA','Magrath','Magrath','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB151','ALL_CA','Longview','Longview','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB152','ALL_CA','Blairmore','Blairmore','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB153','ALL_CA','Innisfree','Innisfree','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB154','ALL_CA','St Michael','St Michael','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB155','ALL_CA','Hussar','Hussar','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB156','ALL_CA','Sibbald','Sibbald','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB157','ALL_CA','Buffalo Head Prairie','Buffalo Head Prairie','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB158','ALL_CA','Canmore','Canmore','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB159','ALL_CA','Fort Kent','Fort Kent','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB160','ALL_CA','Iron River','Iron River','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB161','ALL_CA','Chestermere','Chestermere','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB162','ALL_CA','Alsike','Alsike','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB163','ALL_CA','Slave Lake','Slave Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB164','ALL_CA','Red Deer County','Red Deer County','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB165','ALL_CA','Sherwood Park','Sherwood Park','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB166','ALL_CA','Springbrook','Springbrook','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB167','ALL_CA','Nisku','Nisku','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB168','ALL_CA','Bear Canyon','Bear Canyon','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB169','ALL_CA','Bloomsbury','Bloomsbury','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB170','ALL_CA','Brooks','Brooks','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB171','ALL_CA','Camp Creek','Camp Creek','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB172','ALL_CA','Cold Lake','Cold Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB173','ALL_CA','Dickson','Dickson','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB174','ALL_CA','Enilda','Enilda','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB175','ALL_CA','Flatbush','Flatbush','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB176','ALL_CA','Fort Mackay','Fort Mackay','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB177','ALL_CA','Gift Lake','Gift Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB178','ALL_CA','Goodridge','Goodridge','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB179','ALL_CA','Gwynne','Gwynne','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB180','ALL_CA','Kinuso','Kinuso','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB181','ALL_CA','Lindale','Lindale','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB182','ALL_CA','Lundbreck','Lundbreck','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB183','ALL_CA','Olds','Olds','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB184','ALL_CA','Plamondon','Plamondon','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB185','ALL_CA','Rocky Mountain House','Rocky Mountain House','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB186','ALL_CA','Scandia','Scandia','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB187','ALL_CA','Sundre','Sundre','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB188','ALL_CA','Tomahawk','Tomahawk','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB189','ALL_CA','Trochu','Trochu','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB190','ALL_CA','Two Hills','Two Hills','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB191','ALL_CA','Water Valley','Water Valley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB192','ALL_CA','Westlock','Westlock','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB193','ALL_CA','Wetaskiwin','Wetaskiwin','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB194','ALL_CA','Standard','Standard','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB195','ALL_CA','St. Albert','St. Albert','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB196','ALL_CA','Bow Island','Bow Island','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB197','ALL_CA','Keoma','Keoma','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB198','ALL_CA','Heisler','Heisler','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB199','ALL_CA','Cherry Point','Cherry Point','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB200','ALL_CA','Sangudo','Sangudo','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB201','ALL_CA','Irvine','Irvine','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB202','ALL_CA','Fallis','Fallis','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB203','ALL_CA','Coleman','Coleman','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB204','ALL_CA','Viking','Viking','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB205','ALL_CA','Alhambra','Alhambra','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB206','ALL_CA','College Heights','College Heights','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB207','ALL_CA','Monitor','Monitor','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB208','ALL_CA','Blackfoot','Blackfoot','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB209','ALL_CA','Rochester','Rochester','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB210','ALL_CA','Mayerthorpe','Mayerthorpe','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB211','ALL_CA','Gibbons','Gibbons','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB212','ALL_CA','Hilda','Hilda','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB213','ALL_CA','Swan Hills','Swan Hills','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB214','ALL_CA','Calling Lake','Calling Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB215','ALL_CA','Kinsella','Kinsella','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB216','ALL_CA','Deadwood','Deadwood','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB217','ALL_CA','Star','Star','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB218','ALL_CA','Beiseker','Beiseker','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB219','ALL_CA','Rosemary','Rosemary','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB220','ALL_CA','Calahoo','Calahoo','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB221','ALL_CA','Rolly View','Rolly View','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB222','ALL_CA','Sedalia','Sedalia','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB223','ALL_CA','Lamont','Lamont','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB224','ALL_CA','Del Bonita','Del Bonita','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB225','ALL_CA','Dorothy','Dorothy','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB226','ALL_CA','Lavoy','Lavoy','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB227','ALL_CA','Brosseau','Brosseau','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB228','ALL_CA','Brownfield','Brownfield','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB229','ALL_CA','Westerose','Westerose','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB230','ALL_CA','Welling','Welling','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB231','ALL_CA','Condor','Condor','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB232','ALL_CA','Bon Accord','Bon Accord','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB233','ALL_CA','Etzikom','Etzikom','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB234','ALL_CA','Torrington','Torrington','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB235','ALL_CA','Delia','Delia','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB236','ALL_CA','Sturgeon County','Sturgeon County','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB237','ALL_CA','Consort','Consort','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB238','ALL_CA','Esther','Esther','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB239','ALL_CA','White Gull','White Gull','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB240','ALL_CA','Lodgepole','Lodgepole','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB241','ALL_CA','Lousana','Lousana','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB242','ALL_CA','Taber','Taber','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB243','ALL_CA','Coalhurst','Coalhurst','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB244','ALL_CA','Altario','Altario','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB293','ALL_CA','Waterton Park','Waterton Park','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB294','ALL_CA','Acadia Valley','Acadia Valley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB295','ALL_CA','Rosalind','Rosalind','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB296','ALL_CA','Champion','Champion','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB297','ALL_CA','Bay Tree','Bay Tree','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB298','ALL_CA','Widewater','Widewater','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB299','ALL_CA','Cereal','Cereal','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB300','ALL_CA','Acheson','Acheson','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB301','ALL_CA','Kathyrn','Kathyrn','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB302','ALL_CA','Grande Prairie','Grande Prairie','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB303','ALL_CA','Rimbey','Rimbey','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB304','ALL_CA','Cowley','Cowley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB305','ALL_CA','Chard','Chard','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB306','ALL_CA','Spirit River','Spirit River','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB307','ALL_CA','Ardmore','Ardmore','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB308','ALL_CA','Desert Blume','Desert Blume','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB309','ALL_CA','County of Grande Prairie No. 1','County of Grande Prairie No. 1','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB310','ALL_CA','Coutts','Coutts','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB311','ALL_CA','Three Hills','Three Hills','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB312','ALL_CA','Thorsby','Thorsby','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB313','ALL_CA','Bragg Creek','Bragg Creek','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB314','ALL_CA','Cherhill','Cherhill','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB315','ALL_CA','Strome','Strome','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB316','ALL_CA','Silver Valley','Silver Valley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB317','ALL_CA','Kirriemuir','Kirriemuir','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB318','ALL_CA','Hanna','Hanna','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB319','ALL_CA','Rainbow Lake','Rainbow Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB320','ALL_CA','Islay','Islay','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB321','ALL_CA','Irma','Irma','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB322','ALL_CA','Iron Springs','Iron Springs','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB323','ALL_CA','Camrose County','Camrose County','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB324','ALL_CA','Barrhead','Barrhead','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB325','ALL_CA','Seven Persons','Seven Persons','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB326','ALL_CA','Demmitt','Demmitt','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB327','ALL_CA','Aldersyde','Aldersyde','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB328','ALL_CA','Siksika','Siksika','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB329','ALL_CA','Hays','Hays','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB330','ALL_CA','Brule','Brule','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB331','ALL_CA','Buffalo','Buffalo','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB332','ALL_CA','Byemoor','Byemoor','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB333','ALL_CA','Carnwood','Carnwood','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB334','ALL_CA','Caroline','Caroline','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB335','ALL_CA','Clive','Clive','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB336','ALL_CA','Dixonville','Dixonville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB337','ALL_CA','Eckville','Eckville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB338','ALL_CA','Elnora','Elnora','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB339','ALL_CA','Endiang','Endiang','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB340','ALL_CA','Erskine','Erskine','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB488','ALL_CA','Finnegan','Finnegan','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB489','ALL_CA','Grassland','Grassland','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB490','ALL_CA','Hondo','Hondo','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB491','ALL_CA','Millet','Millet','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB492','ALL_CA','Manyberries','Manyberries','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB493','ALL_CA','Neerlandia','Neerlandia','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB494','ALL_CA','Parkland','Parkland','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB495','ALL_CA','Priddis','Priddis','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB496','ALL_CA','Rowley','Rowley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB497','ALL_CA','Stauffer','Stauffer','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB498','ALL_CA','Turner Valley','Turner Valley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB499','ALL_CA','Wardlow','Wardlow','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB500','ALL_CA','Ferintosh','Ferintosh','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB501','ALL_CA','Hairy Hill','Hairy Hill','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB502','ALL_CA','Cayley','Cayley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB503','ALL_CA','Alcomdale','Alcomdale','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB504','ALL_CA','Oyen','Oyen','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB505','ALL_CA','New Sarepta','New Sarepta','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB506','ALL_CA','Riviere Qui Barre','Riviere Qui Barre','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB507','ALL_CA','Crossfield','Crossfield','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB508','ALL_CA','Bashaw','Bashaw','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB509','ALL_CA','Mannville','Mannville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB510','ALL_CA','Medicine Hat','Medicine Hat','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB511','ALL_CA','Clyde','Clyde','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB512','ALL_CA','Notikewin','Notikewin','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB513','ALL_CA','Cadomin','Cadomin','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB514','ALL_CA','Wembley','Wembley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB515','ALL_CA','Carmangay','Carmangay','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB516','ALL_CA','Perryvale','Perryvale','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB517','ALL_CA','Acme','Acme','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB518','ALL_CA','Langdon','Langdon','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB519','ALL_CA','Coronation','Coronation','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB520','ALL_CA','Pickardville','Pickardville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB521','ALL_CA','Markerville','Markerville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB522','ALL_CA','Blueberry Mountain','Blueberry Mountain','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB523','ALL_CA','Bluesky','Bluesky','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB524','ALL_CA','Schuler','Schuler','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB525','ALL_CA','Bonanza','Bonanza','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB526','ALL_CA','Leduc','Leduc','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB527','ALL_CA','Madden','Madden','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB528','ALL_CA','Rockyford','Rockyford','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB529','ALL_CA','Fort Saskatchewan','Fort Saskatchewan','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB530','ALL_CA','Vauxhall','Vauxhall','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB531','ALL_CA','Beaverlodge','Beaverlodge','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB532','ALL_CA','Buck Lake','Buck Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB533','ALL_CA','Chisholm Mills','Chisholm Mills','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB534','ALL_CA','Conklin','Conklin','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB535','ALL_CA','Czar','Czar','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB341','ALL_CA','Fox Lake','Fox Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB342','ALL_CA','Hay Lakes','Hay Lakes','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB343','ALL_CA','High River','High River','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB344','ALL_CA','Hylo','Hylo','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB345','ALL_CA','Hythe','Hythe','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB346','ALL_CA','Kikino','Kikino','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB347','ALL_CA','Kingman','Kingman','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB348','ALL_CA','Lafond','Lafond','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB349','ALL_CA','Linden','Linden','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB350','ALL_CA','Marlboro','Marlboro','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB351','ALL_CA','Minburn','Minburn','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB352','ALL_CA','Nobleford','Nobleford','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB353','ALL_CA','Okotoks','Okotoks','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB354','ALL_CA','Paddle Prairie','Paddle Prairie','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB355','ALL_CA','Peers','Peers','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB356','ALL_CA','Ralston','Ralston','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB357','ALL_CA','Rosedale Station','Rosedale Station','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB358','ALL_CA','Smith','Smith','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB359','ALL_CA','Stirling','Stirling','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB360','ALL_CA','Whispering Hills','Whispering Hills','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB361','ALL_CA','Claresholm','Claresholm','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB362','ALL_CA','Lacombe','Lacombe','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB363','ALL_CA','Halkirk','Halkirk','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB364','ALL_CA','Paradise Valley','Paradise Valley','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB365','ALL_CA','Beauvallon','Beauvallon','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB366','ALL_CA','Chauvin','Chauvin','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB367','ALL_CA','Glenwood','Glenwood','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB368','ALL_CA','Jenner','Jenner','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB369','ALL_CA','Cochrane','Cochrane','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB370','ALL_CA','Spruce Grove','Spruce Grove','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB371','ALL_CA','Warner','Warner','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB372','ALL_CA','Gadsby','Gadsby','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB373','ALL_CA','Swalwell','Swalwell','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB374','ALL_CA','Marie Reine','Marie Reine','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB375','ALL_CA','Chipman','Chipman','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB376','ALL_CA','Veteran','Veteran','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB377','ALL_CA','Andrew','Andrew','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB378','ALL_CA','Shaughnessy','Shaughnessy','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB379','ALL_CA','Patricia','Patricia','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB380','ALL_CA','Lake Isle','Lake Isle','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB381','ALL_CA','McLaughlin','McLaughlin','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB382','ALL_CA','McLennan','McLennan','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB383','ALL_CA','Stony Plain','Stony Plain','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB384','ALL_CA','Duffield','Duffield','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB385','ALL_CA','Faust','Faust','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB386','ALL_CA','Delacour','Delacour','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB387','ALL_CA','La Crete','La Crete','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB388','ALL_CA','Beaumont','Beaumont','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB389','ALL_CA','Chateh','Chateh','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB536','ALL_CA','Dalemead','Dalemead','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB537','ALL_CA','Denwood','Denwood','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB538','ALL_CA','Diamond City','Diamond City','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB539','ALL_CA','Didsbury','Didsbury','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB540','ALL_CA','Eaglesham','Eaglesham','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB541','ALL_CA','Garden River','Garden River','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB542','ALL_CA','Girouxville','Girouxville','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB543','ALL_CA','Goodfare','Goodfare','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB544','ALL_CA','Goodfish Lake','Goodfish Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB545','ALL_CA','Iddesleigh','Iddesleigh','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB546','ALL_CA','Indus','Indus','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB547','ALL_CA','James River Bridge','James River Bridge','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB548','ALL_CA','Jean Cote','Jean Cote','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB549','ALL_CA','Kapasiwin','Kapasiwin','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB550','ALL_CA','Mulhurst Bay','Mulhurst Bay','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB551','ALL_CA','Parkland County','Parkland County','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB552','ALL_CA','Peerless Lake','Peerless Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB553','ALL_CA','Redwood Meadows','Redwood Meadows','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB554','ALL_CA','Rochfort Bridge','Rochfort Bridge','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB555','ALL_CA','Rosebud','Rosebud','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB556','ALL_CA','Skiff','Skiff','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB557','ALL_CA','Tsuu T''Ina','Tsuu T''Ina','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB558','ALL_CA','Turin','Turin','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB559','ALL_CA','Vulcan','Vulcan','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB560','ALL_CA','Warspite','Warspite','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB561','ALL_CA','West Baptiste','West Baptiste','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB562','ALL_CA','Provost','Provost','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB563','ALL_CA','Monarch','Monarch','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB564','ALL_CA','Big Stone','Big Stone','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB565','ALL_CA','Darwell','Darwell','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB566','ALL_CA','Bezanson','Bezanson','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB567','ALL_CA','Sylvan Lake','Sylvan Lake','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB568','ALL_CA','Atikameg','Atikameg','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB569','ALL_CA','Blackie','Blackie','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB570','ALL_CA','Manning','Manning','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB571','ALL_CA','Wabamun','Wabamun','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB572','ALL_CA','Picture Butte','Picture Butte','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB573','ALL_CA','New Brigden','New Brigden','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB574','ALL_CA','Chinook','Chinook','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB575','ALL_CA','Sunset House','Sunset House','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB576','ALL_CA','Canyon Creek','Canyon Creek','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB577','ALL_CA','Cadogan','Cadogan','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB578','ALL_CA','Munson','Munson','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB579','ALL_CA','Clandonald','Clandonald','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB580','ALL_CA','De Winton','De Winton','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB581','ALL_CA','Wildwood','Wildwood','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB582','ALL_CA','Kehewin','Kehewin','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB583','ALL_CA','Cessford','Cessford','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('AB1','ALL_CA','Atmore','Atmore','AB','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0);
commit;
