insert into YFS_REGION (REGION_KEY,REGION_SCHEMA_KEY,REGION_NAME,REGION_DESCRIPTION,PARENT_REGION_KEY,REGION_LEVEL_NAME,CAN_AGGREGATE,CREATEUSERID, MODIFYUSERID, CREATEPROGID, MODIFYPROGID, LOCKID) VALUES
('BC','ALL_CA','BC','BC','CAN','State','Y','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC1','ALL_CA','Agassiz','Agassiz','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC2','ALL_CA','Crawford Bay','Crawford Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC3','ALL_CA','Elko','Elko','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC4','ALL_CA','Gitanmaax','Gitanmaax','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC5','ALL_CA','Lund','Lund','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC6','ALL_CA','Mansons Landing','Mansons Landing','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC7','ALL_CA','Mica Creek','Mica Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC8','ALL_CA','Minstrel Island','Minstrel Island','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC9','ALL_CA','Pavilion','Pavilion','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC10','ALL_CA','Prespatou','Prespatou','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC11','ALL_CA','Sinclair Mills','Sinclair Mills','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC12','ALL_CA','Sointula','Sointula','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC13','ALL_CA','Tomslake','Tomslake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC14','ALL_CA','Van Anda','Van Anda','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC15','ALL_CA','Whistler','Whistler','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC16','ALL_CA','Wynndel','Wynndel','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC17','ALL_CA','Yahk','Yahk','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC18','ALL_CA','Midway','Midway','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC19','ALL_CA','Yale','Yale','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC20','ALL_CA','Wonowon','Wonowon','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC21','ALL_CA','Mill Bay','Mill Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC22','ALL_CA','Quilchena','Quilchena','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC23','ALL_CA','Cedarvale','Cedarvale','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC24','ALL_CA','Malahat','Malahat','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC25','ALL_CA','Malakwa','Malakwa','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC26','ALL_CA','Muncho Lake','Muncho Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC27','ALL_CA','Rolla','Rolla','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC28','ALL_CA','Lac La Hache','Lac La Hache','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC29','ALL_CA','Sidney','Sidney','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC30','ALL_CA','Slocan Park','Slocan Park','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC31','ALL_CA','Charlie Lake','Charlie Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC32','ALL_CA','Belcarra','Belcarra','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC33','ALL_CA','Tofino','Tofino','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC34','ALL_CA','Tahsis','Tahsis','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC35','ALL_CA','Burnaby','Burnaby','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC36','ALL_CA','Nelson','Nelson','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC37','ALL_CA','Monte Lake','Monte Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC38','ALL_CA','Oona River','Oona River','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC39','ALL_CA','Mara','Mara','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC40','ALL_CA','Sirdar','Sirdar','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC41','ALL_CA','Ta Ta Creek','Ta Ta Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC42','ALL_CA','Ymir','Ymir','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC43','ALL_CA','Courtenay','Courtenay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC44','ALL_CA','Christina Lake','Christina Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC45','ALL_CA','Kitimat','Kitimat','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC46','ALL_CA','Tulameen','Tulameen','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC47','ALL_CA','Westbridge','Westbridge','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC48','ALL_CA','Kleena Kleene','Kleena Kleene','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC49','ALL_CA','Campbell River','Campbell River','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC50','ALL_CA','Port Alice','Port Alice','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC51','ALL_CA','70 Mile House','70 Mile House','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC52','ALL_CA','Bear Lake','Bear Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC53','ALL_CA','Blind Bay','Blind Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC54','ALL_CA','Celista','Celista','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC55','ALL_CA','Horsefly','Horsefly','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC56','ALL_CA','Salmon Arm','Salmon Arm','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC57','ALL_CA','Manson Creek','Manson Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC58','ALL_CA','Pitt Meadows','Pitt Meadows','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC59','ALL_CA','Powell River','Powell River','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC60','ALL_CA','Qualicum Beach','Qualicum Beach','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC61','ALL_CA','Rosedale','Rosedale','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC62','ALL_CA','Squirrel Cove','Squirrel Cove','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC63','ALL_CA','Topley','Topley','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC64','ALL_CA','White Rock','White Rock','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC65','ALL_CA','Little Fort','Little Fort','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC66','ALL_CA','Golden','Golden','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC67','ALL_CA','Eagle Creek','Eagle Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC68','ALL_CA','Invermere','Invermere','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC69','ALL_CA','Edgewater','Edgewater','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC70','ALL_CA','Koksilah','Koksilah','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC71','ALL_CA','Gabriola','Gabriola','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC72','ALL_CA','Sunset Prairie','Sunset Prairie','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC73','ALL_CA','D''Arcy','D''Arcy','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC74','ALL_CA','Westbank','Westbank','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC75','ALL_CA','Nanaimo','Nanaimo','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC76','ALL_CA','Nass Camp','Nass Camp','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC77','ALL_CA','Lower Post','Lower Post','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC78','ALL_CA','Summerland','Summerland','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC79','ALL_CA','McLeese Lake','McLeese Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC80','ALL_CA','Clinton','Clinton','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC81','ALL_CA','Fruitvale','Fruitvale','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC82','ALL_CA','Ashcroft','Ashcroft','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC83','ALL_CA','Brisco','Brisco','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC84','ALL_CA','Juskatla','Juskatla','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC85','ALL_CA','Spillimacheen','Spillimacheen','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC86','ALL_CA','Black Creek','Black Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC87','ALL_CA','Vancouver','Vancouver','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC88','ALL_CA','Terrace','Terrace','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC89','ALL_CA','Gold Bridge','Gold Bridge','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC90','ALL_CA','Telegraph Creek','Telegraph Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC91','ALL_CA','Coal Harbour','Coal Harbour','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC92','ALL_CA','Ladysmith','Ladysmith','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC93','ALL_CA','Vernon','Vernon','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC94','ALL_CA','Union Bay','Union Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC95','ALL_CA','Kingsgate','Kingsgate','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC96','ALL_CA','Dewdney','Dewdney','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC97','ALL_CA','Nemaiah Valley','Nemaiah Valley','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC98','ALL_CA','Quesnel','Quesnel','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC99','ALL_CA','Port Coquitlam','Port Coquitlam','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC100','ALL_CA','Port Moody','Port Moody','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC101','ALL_CA','Brentwood Bay','Brentwood Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC102','ALL_CA','Sooke','Sooke','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC103','ALL_CA','108 Mile Ranch','108 Mile Ranch','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC104','ALL_CA','150 Mile House','150 Mile House','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC105','ALL_CA','Ahousat','Ahousat','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC106','ALL_CA','Beaverdell','Beaverdell','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC107','ALL_CA','Cecil Lake','Cecil Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC108','ALL_CA','Dawson Creek','Dawson Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC109','ALL_CA','Endako','Endako','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC110','ALL_CA','Farmington','Farmington','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC111','ALL_CA','Fort St. James','Fort St. James','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC112','ALL_CA','Galiano','Galiano','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC113','ALL_CA','Greenville','Greenville','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC114','ALL_CA','Hanceville','Hanceville','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC115','ALL_CA','Lake Country','Lake Country','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC116','ALL_CA','Lumby','Lumby','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC117','ALL_CA','Penticton','Penticton','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC118','ALL_CA','Sechelt','Sechelt','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC119','ALL_CA','Victoria','Victoria','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC120','ALL_CA','Haisla','Haisla','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC121','ALL_CA','Hazelton','Hazelton','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC122','ALL_CA','Bowen Island','Bowen Island','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC123','ALL_CA','Harrison Hot Springs','Harrison Hot Springs','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC124','ALL_CA','Tappen','Tappen','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC125','ALL_CA','Lions Bay','Lions Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC126','ALL_CA','Grand Forks','Grand Forks','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC127','ALL_CA','Boswell','Boswell','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC128','ALL_CA','Crescent Spur','Crescent Spur','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC129','ALL_CA','Mount Currie','Mount Currie','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC130','ALL_CA','Alkali Lake','Alkali Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC131','ALL_CA','Mesachie Lake','Mesachie Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC132','ALL_CA','Maple Ridge','Maple Ridge','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC133','ALL_CA','Canoe','Canoe','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC134','ALL_CA','Mayne Island','Mayne Island','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC135','ALL_CA','Surge Narrows','Surge Narrows','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC136','ALL_CA','Granisle','Granisle','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC137','ALL_CA','Parksville','Parksville','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC138','ALL_CA','Alert Bay','Alert Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC139','ALL_CA','Thetis Island','Thetis Island','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC140','ALL_CA','Hedley','Hedley','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC141','ALL_CA','Jordan River','Jordan River','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC142','ALL_CA','Delta','Delta','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC143','ALL_CA','Pinantan Lake','Pinantan Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC144','ALL_CA','Groundbirch','Groundbirch','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC145','ALL_CA','Chemainus','Chemainus','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC146','ALL_CA','Kincolith','Kincolith','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC147','ALL_CA','Gold River','Gold River','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC148','ALL_CA','Silverton','Silverton','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC149','ALL_CA','Dawsons Landing','Dawsons Landing','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC150','ALL_CA','Fort Nelson','Fort Nelson','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC151','ALL_CA','Vavenby','Vavenby','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC152','ALL_CA','Peace River Regional District','Peace River Regional District','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC153','ALL_CA','Chilliwack','Chilliwack','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC154','ALL_CA','Port McNeill','Port McNeill','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC155','ALL_CA','Saanichton','Saanichton','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC156','ALL_CA','Kitwanga','Kitwanga','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC157','ALL_CA','Klemtu','Klemtu','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC158','ALL_CA','Cassidy','Cassidy','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC159','ALL_CA','Cultus Lake','Cultus Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC160','ALL_CA','Dease Lake','Dease Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC161','ALL_CA','Enderby','Enderby','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC162','ALL_CA','Falkland','Falkland','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC163','ALL_CA','Fanny Bay','Fanny Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC164','ALL_CA','Garden Bay','Garden Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC165','ALL_CA','Gitsegukla','Gitsegukla','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC166','ALL_CA','Halfmoon Bay','Halfmoon Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC167','ALL_CA','Honeymoon Bay','Honeymoon Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC168','ALL_CA','Hudson''s Hope','Hudson''s Hope','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC169','ALL_CA','Salmo','Salmo','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC170','ALL_CA','Likely','Likely','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC171','ALL_CA','Logan Lake','Logan Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC172','ALL_CA','Port Alberni','Port Alberni','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC173','ALL_CA','Procter','Procter','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC174','ALL_CA','Rose Prairie','Rose Prairie','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC175','ALL_CA','Salt Spring Island','Salt Spring Island','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC176','ALL_CA','Shalalth','Shalalth','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC177','ALL_CA','Sparwood','Sparwood','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC178','ALL_CA','Wells','Wells','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC179','ALL_CA','Westholme','Westholme','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC180','ALL_CA','Woss','Woss','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC181','ALL_CA','Fernie','Fernie','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC182','ALL_CA','Harrison Mills','Harrison Mills','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC183','ALL_CA','Coquitlam','Coquitlam','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC184','ALL_CA','Baynes Lake','Baynes Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC185','ALL_CA','Trail','Trail','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC186','ALL_CA','Port Edward','Port Edward','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC187','ALL_CA','Nimpo Lake','Nimpo Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC188','ALL_CA','Boston Bar','Boston Bar','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC189','ALL_CA','Summit Lake','Summit Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC190','ALL_CA','Creston','Creston','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC191','ALL_CA','Alexis Creek','Alexis Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC192','ALL_CA','Stuart Island','Stuart Island','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC193','ALL_CA','Rock Creek','Rock Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC194','ALL_CA','Nakusp','Nakusp','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC195','ALL_CA','Ware','Ware','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC196','ALL_CA','Erickson','Erickson','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC197','ALL_CA','Hartley Bay','Hartley Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC198','ALL_CA','Bamfield','Bamfield','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC199','ALL_CA','Dog Creek','Dog Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC200','ALL_CA','McLure','McLure','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC201','ALL_CA','Montrose','Montrose','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC202','ALL_CA','Lavington','Lavington','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC203','ALL_CA','Sorrento','Sorrento','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC204','ALL_CA','Kingcome Inlet','Kingcome Inlet','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC205','ALL_CA','Parson','Parson','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC206','ALL_CA','Winlaw','Winlaw','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC207','ALL_CA','Tatlayoko Lake','Tatlayoko Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC208','ALL_CA','Youbou','Youbou','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC209','ALL_CA','Fort Fraser','Fort Fraser','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC210','ALL_CA','Telkwa','Telkwa','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC211','ALL_CA','Argenta','Argenta','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC212','ALL_CA','Prince George','Prince George','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC213','ALL_CA','Quathiaski Cove','Quathiaski Cove','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC214','ALL_CA','Quatsino','Quatsino','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC215','ALL_CA','Baldonnel','Baldonnel','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC216','ALL_CA','Barkerville','Barkerville','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC217','ALL_CA','Coombs','Coombs','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC218','ALL_CA','Darfield','Darfield','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC219','ALL_CA','Elkford','Elkford','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC220','ALL_CA','Grasmere','Grasmere','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC221','ALL_CA','Greenwood','Greenwood','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC222','ALL_CA','Hope','Hope','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC223','ALL_CA','Okanagan Falls','Okanagan Falls','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC224','ALL_CA','Progress','Progress','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC225','ALL_CA','Tlell','Tlell','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC226','ALL_CA','Tsay Keh Dene','Tsay Keh Dene','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC227','ALL_CA','Williams Lake','Williams Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC228','ALL_CA','Windermere','Windermere','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC229','ALL_CA','Stewart','Stewart','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC230','ALL_CA','Heffley Creek','Heffley Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC231','ALL_CA','Lower Nicola','Lower Nicola','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC232','ALL_CA','Kamloops','Kamloops','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC233','ALL_CA','Lax Kw''Alaams','Lax Kw''Alaams','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC234','ALL_CA','Cawston','Cawston','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC235','ALL_CA','Gang Ranch','Gang Ranch','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC236','ALL_CA','Eagle Bay','Eagle Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC237','ALL_CA','Willow River','Willow River','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC238','ALL_CA','Deroche','Deroche','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC239','ALL_CA','Garibaldi Highlands','Garibaldi Highlands','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC240','ALL_CA','Royston','Royston','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC241','ALL_CA','Penny','Penny','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC242','ALL_CA','Knutsford','Knutsford','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC243','ALL_CA','Anglemont','Anglemont','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC244','ALL_CA','Southbank','Southbank','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC245','ALL_CA','Slocan','Slocan','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC246','ALL_CA','Kelowna','Kelowna','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC247','ALL_CA','Takla Landing','Takla Landing','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC248','ALL_CA','Upper Fraser','Upper Fraser','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC249','ALL_CA','Chilanko Forks','Chilanko Forks','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC250','ALL_CA','Masset','Masset','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC251','ALL_CA','Cobble Hill','Cobble Hill','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC252','ALL_CA','Blue River','Blue River','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC253','ALL_CA','Port Renfrew','Port Renfrew','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC254','ALL_CA','Gold Creek','Gold Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC255','ALL_CA','Coalmont','Coalmont','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC256','ALL_CA','Hixon','Hixon','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC257','ALL_CA','Cranbrook','Cranbrook','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC258','ALL_CA','Merritt','Merritt','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC259','ALL_CA','West Kelowna','West Kelowna','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC260','ALL_CA','Prince Rupert','Prince Rupert','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC261','ALL_CA','Kitkatla','Kitkatla','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC262','ALL_CA','Duncan','Duncan','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC263','ALL_CA','100 Mile House','100 Mile House','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC264','ALL_CA','Abbotsford','Abbotsford','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC265','ALL_CA','Armstrong','Armstrong','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC266','ALL_CA','Balfour','Balfour','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC267','ALL_CA','Bonnington','Bonnington','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC268','ALL_CA','Burton','Burton','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC269','ALL_CA','Errington','Errington','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC270','ALL_CA','Fort St. John','Fort St. John','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC271','ALL_CA','Good Hope Lake','Good Hope Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC272','ALL_CA','Iskut','Iskut','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC273','ALL_CA','Keremeos','Keremeos','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC274','ALL_CA','Lillooet','Lillooet','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC275','ALL_CA','Moberly Lake','Moberly Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC276','ALL_CA','Pritchard','Pritchard','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC277','ALL_CA','Smithers','Smithers','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC278','ALL_CA','Spences Bridge','Spences Bridge','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC279','ALL_CA','Sun Peaks','Sun Peaks','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC280','ALL_CA','Walhachin','Walhachin','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC281','ALL_CA','Wardner','Wardner','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC282','ALL_CA','Zeballos','Zeballos','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC283','ALL_CA','Kitchener','Kitchener','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC284','ALL_CA','New Westminster','New Westminster','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC285','ALL_CA','Revelstoke','Revelstoke','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC286','ALL_CA','Pouce Coupe','Pouce Coupe','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC287','ALL_CA','South Slocan','South Slocan','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC288','ALL_CA','Lantzville','Lantzville','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC289','ALL_CA','Savona','Savona','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC290','ALL_CA','Gibsons','Gibsons','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC291','ALL_CA','Hornby Island','Hornby Island','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC292','ALL_CA','Castlegar','Castlegar','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC293','ALL_CA','Mackenzie','Mackenzie','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC294','ALL_CA','Galloway','Galloway','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC295','ALL_CA','Lytton','Lytton','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC296','ALL_CA','Lake Errock','Lake Errock','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC297','ALL_CA','Fairmont Hot Springs','Fairmont Hot Springs','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC298','ALL_CA','Clearwater','Clearwater','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC299','ALL_CA','Beasley','Beasley','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC300','ALL_CA','Panorama','Panorama','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC301','ALL_CA','Chetwynd','Chetwynd','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC302','ALL_CA','Pink Mountain','Pink Mountain','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC303','ALL_CA','Chase','Chase','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC304','ALL_CA','Fauquier','Fauquier','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC305','ALL_CA','Shawnigan Lake','Shawnigan Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC306','ALL_CA','Osoyoos','Osoyoos','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC307','ALL_CA','Bowser','Bowser','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC308','ALL_CA','Egmont','Egmont','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC309','ALL_CA','Ainsworth Hot Springs','Ainsworth Hot Springs','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC310','ALL_CA','Port Clements','Port Clements','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC311','ALL_CA','Grindrod','Grindrod','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC312','ALL_CA','Dunster','Dunster','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC313','ALL_CA','Canim Lake','Canim Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC314','ALL_CA','Jade City','Jade City','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC315','ALL_CA','Jaffray','Jaffray','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC316','ALL_CA','Langley','Langley','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC317','ALL_CA','Peachland','Peachland','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC318','ALL_CA','Houston','Houston','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC319','ALL_CA','Port Mellon','Port Mellon','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC320','ALL_CA','Squamish','Squamish','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC321','ALL_CA','Atlin','Atlin','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC322','ALL_CA','Avola','Avola','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC323','ALL_CA','Bella Bella','Bella Bella','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC324','ALL_CA','Blind Channel','Blind Channel','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC325','ALL_CA','Blubber Bay','Blubber Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC326','ALL_CA','Bridesville','Bridesville','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC327','ALL_CA','Cache Creek','Cache Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC328','ALL_CA','Canal Flats','Canal Flats','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC329','ALL_CA','Crofton','Crofton','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC330','ALL_CA','Gitwinksihlkw','Gitwinksihlkw','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC331','ALL_CA','Goodlow','Goodlow','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC332','ALL_CA','Harrogate','Harrogate','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC333','ALL_CA','Heriot Bay','Heriot Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC334','ALL_CA','Kootenay Bay','Kootenay Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC335','ALL_CA','Longworth','Longworth','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC336','ALL_CA','Moyie','Moyie','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC337','ALL_CA','Naramata','Naramata','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC338','ALL_CA','Prophet River','Prophet River','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC339','ALL_CA','Redstone','Redstone','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC340','ALL_CA','Refuge Cove','Refuge Cove','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC341','ALL_CA','Roberts Creek','Roberts Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC342','ALL_CA','North Saanich','North Saanich','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC343','ALL_CA','Sandspit','Sandspit','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC344','ALL_CA','Scotch Creek','Scotch Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC345','ALL_CA','Skookumchuck','Skookumchuck','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC346','ALL_CA','Tsawwassen','Tsawwassen','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC347','ALL_CA','Tumbler Ridge','Tumbler Ridge','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC348','ALL_CA','Field','Field','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC349','ALL_CA','Hagensborg','Hagensborg','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC350','ALL_CA','Louis Creek','Louis Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC351','ALL_CA','Gillies Bay','Gillies Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC352','ALL_CA','Richmond','Richmond','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC353','ALL_CA','Anahim Lake','Anahim Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC354','ALL_CA','Kimberley','Kimberley','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC355','ALL_CA','Port Hardy','Port Hardy','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC356','ALL_CA','Canyon','Canyon','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC357','ALL_CA','Kyuquot','Kyuquot','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC358','ALL_CA','Riske Creek','Riske Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC359','ALL_CA','Princeton','Princeton','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC360','ALL_CA','Milner','Milner','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC361','ALL_CA','Robson','Robson','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC362','ALL_CA','Mission','Mission','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC363','ALL_CA','McBride','McBride','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC364','ALL_CA','Monte Creek','Monte Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC365','ALL_CA','Montney','Montney','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC366','ALL_CA','Lasqueti','Lasqueti','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC367','ALL_CA','Pender Island','Pender Island','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC368','ALL_CA','Thornhill','Thornhill','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC369','ALL_CA','Barriere','Barriere','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC370','ALL_CA','Lone Butte','Lone Butte','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC371','ALL_CA','Brackendale','Brackendale','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC372','ALL_CA','Sicamous','Sicamous','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC373','ALL_CA','Whaletown','Whaletown','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC374','ALL_CA','Tatla Lake','Tatla Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC375','ALL_CA','Francois Lake','Francois Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC376','ALL_CA','Genelle','Genelle','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC377','ALL_CA','Telegraph Cove','Telegraph Cove','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC378','ALL_CA','Seton Portage','Seton Portage','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC379','ALL_CA','Valemount','Valemount','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC380','ALL_CA','Fort Steele','Fort Steele','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC381','ALL_CA','Surrey','Surrey','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC382','ALL_CA','Aldergrove','Aldergrove','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC383','ALL_CA','Vanderhoof','Vanderhoof','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC384','ALL_CA','Anmore','Anmore','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC385','ALL_CA','Bella Coola','Bella Coola','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC386','ALL_CA','Big Lake Ranch','Big Lake Ranch','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC387','ALL_CA','Bridge Lake','Bridge Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC388','ALL_CA','Buick','Buick','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC389','ALL_CA','Clayhurst','Clayhurst','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC390','ALL_CA','Comox','Comox','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC391','ALL_CA','Cumberland','Cumberland','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC392','ALL_CA','Denny Island','Denny Island','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC393','ALL_CA','Fraser Lake','Fraser Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC394','ALL_CA','Furry Creek','Furry Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC395','ALL_CA','Kildonan','Kildonan','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC396','ALL_CA','Lindell Beach','Lindell Beach','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC397','ALL_CA','Meadow Creek','Meadow Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC398','ALL_CA','New Hazelton','New Hazelton','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC399','ALL_CA','Ocean Falls','Ocean Falls','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC400','ALL_CA','Radium Hot Springs','Radium Hot Springs','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC401','ALL_CA','Sayward','Sayward','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC402','ALL_CA','Simoom Sound','Simoom Sound','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC403','ALL_CA','Toad River','Toad River','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC404','ALL_CA','Westwold','Westwold','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC405','ALL_CA','Coldstream','Coldstream','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC406','ALL_CA','Cherryville','Cherryville','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC407','ALL_CA','Kaleden','Kaleden','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC408','ALL_CA','Lazo','Lazo','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC409','ALL_CA','Crescent Valley','Crescent Valley','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC410','ALL_CA','Merville','Merville','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC411','ALL_CA','North Pine','North Pine','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC412','ALL_CA','McLeod Lake','McLeod Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC413','ALL_CA','Edgewood','Edgewood','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC414','ALL_CA','Douglas Lake','Douglas Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC415','ALL_CA','Pemberton','Pemberton','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC416','ALL_CA','Forest Grove','Forest Grove','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC417','ALL_CA','Tobiano','Tobiano','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC418','ALL_CA','Taylor','Taylor','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC419','ALL_CA','Riondel','Riondel','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC420','ALL_CA','Arras','Arras','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC421','ALL_CA','Wasa','Wasa','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC422','ALL_CA','Kaslo','Kaslo','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC423','ALL_CA','New Denver','New Denver','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC424','ALL_CA','Queen Charlotte','Queen Charlotte','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC425','ALL_CA','Ucluelet','Ucluelet','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC426','ALL_CA','Meziadin Lake','Meziadin Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC427','ALL_CA','Dome Creek','Dome Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC428','ALL_CA','Shirley','Shirley','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC429','ALL_CA','Britannia Beach','Britannia Beach','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC430','ALL_CA','Cowichan Bay','Cowichan Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC431','ALL_CA','Denman Island','Denman Island','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC432','ALL_CA','East Gate','East Gate','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC443','ALL_CA','Holberg','Holberg','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC444','ALL_CA','Oliver','Oliver','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC445','ALL_CA','Lake Cowichan','Lake Cowichan','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC446','ALL_CA','Burns Lake','Burns Lake','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC447','ALL_CA','Nanoose Bay','Nanoose Bay','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC448','ALL_CA','North Vancouver','North Vancouver','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC433','ALL_CA','Altona','Altona','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC434','ALL_CA','Germansen Landing','Germansen Landing','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC435','ALL_CA','Gray Creek','Gray Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC436','ALL_CA','Buffalo Creek','Buffalo Creek','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC437','ALL_CA','West Vancouver','West Vancouver','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC438','ALL_CA','Rossland','Rossland','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC439','ALL_CA','Winter Harbour','Winter Harbour','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC440','ALL_CA','Saturna','Saturna','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC441','ALL_CA','Aiyansh','Aiyansh','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('BC442','ALL_CA','Madeira Park','Madeira Park','BC','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0);
commit;