insert into YFS_REGION_SCHEMA (REGION_SCHEMA_KEY,ORGANIZATION_CODE,REGION_SCHEMA_NAME,REGION_SCHEMA_DESCRIPTION,COUNTRY,CREATEUSERID, MODIFYUSERID, CREATEPROGID, MODIFYPROGID, LOCKID) VALUES 
('ALL_CA ','DEFAULT','ALL_CA','All of the Canada States','CA','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0);
commit;
