insert into YFS_REGION (REGION_KEY,REGION_SCHEMA_KEY,REGION_NAME,REGION_DESCRIPTION,PARENT_REGION_KEY,REGION_LEVEL_NAME,CAN_AGGREGATE,CREATEUSERID, MODIFYUSERID, CREATEPROGID, MODIFYPROGID, LOCKID)VALUES
('SK','ALL_CA','SK','SK','CAN','State','Y','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK4','ALL_CA','Elrose','Elrose','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK5','ALL_CA','Evesham','Evesham','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK6','ALL_CA','Fenwood','Fenwood','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK7','ALL_CA','Fleming','Fleming','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK8','ALL_CA','Fond du Lac','Fond du Lac','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK9','ALL_CA','Frobisher','Frobisher','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK10','ALL_CA','Imperial','Imperial','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK11','ALL_CA','Kendal','Kendal','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK12','ALL_CA','Luseland','Luseland','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK13','ALL_CA','Meota','Meota','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK14','ALL_CA','Morse','Morse','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK15','ALL_CA','Mossbank','Mossbank','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK16','ALL_CA','Nokomis','Nokomis','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK17','ALL_CA','Onion Lake','Onion Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK18','ALL_CA','Paddockwood','Paddockwood','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK19','ALL_CA','Redvers','Redvers','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK20','ALL_CA','Rose Valley','Rose Valley','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK21','ALL_CA','Runnymede','Runnymede','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK22','ALL_CA','Southend','Southend','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK23','ALL_CA','Southey','Southey','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK24','ALL_CA','Tompkins','Tompkins','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK25','ALL_CA','Vonda','Vonda','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK26','ALL_CA','Wynyard','Wynyard','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK27','ALL_CA','Plunkett','Plunkett','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK28','ALL_CA','Tantallon','Tantallon','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK29','ALL_CA','Ituna','Ituna','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK30','ALL_CA','Wilkie','Wilkie','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK31','ALL_CA','Richard','Richard','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK32','ALL_CA','Crystal Springs','Crystal Springs','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK33','ALL_CA','Lipton','Lipton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK34','ALL_CA','Bengough','Bengough','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK35','ALL_CA','Regina','Regina','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK36','ALL_CA','Outlook','Outlook','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK37','ALL_CA','Govan','Govan','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK38','ALL_CA','Big Beaver','Big Beaver','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK39','ALL_CA','Beauval','Beauval','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK40','ALL_CA','Rabbit Lake','Rabbit Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK41','ALL_CA','Weirdale','Weirdale','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK42','ALL_CA','Alida','Alida','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK43','ALL_CA','Cochin','Cochin','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK44','ALL_CA','Pakwaw Lake','Pakwaw Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK45','ALL_CA','Quill Lake','Quill Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK46','ALL_CA','Quinton','Quinton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK47','ALL_CA','Crooked River','Crooked River','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK48','ALL_CA','Springside','Springside','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK49','ALL_CA','Casa Rio','Casa Rio','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK50','ALL_CA','Verwood','Verwood','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK51','ALL_CA','Canwood','Canwood','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK52','ALL_CA','Central Butte','Central Butte','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK1','ALL_CA','Burr','Burr','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK2','ALL_CA','Carmel','Carmel','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK3','ALL_CA','Dalmeny','Dalmeny','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK199','ALL_CA','Coleville','Coleville','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK347','ALL_CA','Buchanan','Buchanan','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK348','ALL_CA','Carrot River','Carrot River','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK349','ALL_CA','Craven','Craven','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK350','ALL_CA','Elfros','Elfros','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK351','ALL_CA','Findlater','Findlater','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK352','ALL_CA','Fir Mountain','Fir Mountain','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK353','ALL_CA','Fox Valley','Fox Valley','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK354','ALL_CA','Foxford','Foxford','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK355','ALL_CA','Goodsoil','Goodsoil','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK356','ALL_CA','Grasswood','Grasswood','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK357','ALL_CA','Herschel','Herschel','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK358','ALL_CA','Hyas','Hyas','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK359','ALL_CA','Ile-a-la-Crosse','Ile-a-la-Crosse','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK360','ALL_CA','Kerrobert','Kerrobert','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK361','ALL_CA','Lemberg','Lemberg','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK362','ALL_CA','Macdowall','Macdowall','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK363','ALL_CA','Marsden','Marsden','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK364','ALL_CA','Nut Mountain','Nut Mountain','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK365','ALL_CA','Osage','Osage','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK366','ALL_CA','Pasqua','Pasqua','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK367','ALL_CA','Pense','Pense','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK368','ALL_CA','Radville','Radville','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK369','ALL_CA','Sandy Bay','Sandy Bay','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK370','ALL_CA','Senlac','Senlac','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK371','ALL_CA','Speers','Speers','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK372','ALL_CA','Victoire','Victoire','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK373','ALL_CA','Wawota','Wawota','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK374','ALL_CA','Weekes','Weekes','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK375','ALL_CA','Halbrite','Halbrite','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK376','ALL_CA','Middle Lake','Middle Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK377','ALL_CA','Yellow Creek','Yellow Creek','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK378','ALL_CA','Wollaston Lake','Wollaston Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK379','ALL_CA','Wolseley','Wolseley','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK380','ALL_CA','Craik','Craik','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK381','ALL_CA','Domremy','Domremy','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK382','ALL_CA','Scott','Scott','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK383','ALL_CA','Riverhurst','Riverhurst','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK384','ALL_CA','Main Centre','Main Centre','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK385','ALL_CA','Gouldtown','Gouldtown','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK386','ALL_CA','Laporte','Laporte','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK387','ALL_CA','Blaine Lake','Blaine Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK388','ALL_CA','Invermay','Invermay','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK389','ALL_CA','North Portal','North Portal','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK390','ALL_CA','Weyakwin','Weyakwin','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK391','ALL_CA','Glidden','Glidden','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK392','ALL_CA','Scout Lake','Scout Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK393','ALL_CA','Grandora','Grandora','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK394','ALL_CA','Battleford','Battleford','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK395','ALL_CA','Waterhen Lake','Waterhen Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK396','ALL_CA','Riverside Estates','Riverside Estates','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK397','ALL_CA','Pierceland','Pierceland','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK398','ALL_CA','Marengo','Marengo','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK399','ALL_CA','Cupar','Cupar','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK400','ALL_CA','Maryfield','Maryfield','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK401','ALL_CA','Wiseton','Wiseton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK402','ALL_CA','Canora','Canora','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK403','ALL_CA','Fairlight','Fairlight','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK404','ALL_CA','Tyner','Tyner','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK405','ALL_CA','Tyvan','Tyvan','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK406','ALL_CA','Clearwater River','Clearwater River','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK407','ALL_CA','Wakaw','Wakaw','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK408','ALL_CA','Togo','Togo','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK409','ALL_CA','Carragana','Carragana','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK410','ALL_CA','Shackleton','Shackleton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK411','ALL_CA','Neidpath','Neidpath','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK412','ALL_CA','Bushell Park','Bushell Park','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK413','ALL_CA','Bladworth','Bladworth','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK414','ALL_CA','Bateman','Bateman','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK415','ALL_CA','Henribourg','Henribourg','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK416','ALL_CA','Broderick','Broderick','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK417','ALL_CA','Courval','Courval','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK418','ALL_CA','Gronlid','Gronlid','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK419','ALL_CA','Bradwell','Bradwell','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK420','ALL_CA','Eastend','Eastend','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK421','ALL_CA','St Victor','St Victor','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK422','ALL_CA','St Walburg','St Walburg','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK423','ALL_CA','Meath Park','Meath Park','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK424','ALL_CA','Wapella','Wapella','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK425','ALL_CA','Candle Lake','Candle Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK426','ALL_CA','Semans','Semans','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK427','ALL_CA','St Gregor','St Gregor','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK575','ALL_CA','Orkney','Orkney','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK576','ALL_CA','Richmound','Richmound','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK577','ALL_CA','Pennant Station','Pennant Station','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK578','ALL_CA','Torquay','Torquay','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK579','ALL_CA','Sceptre','Sceptre','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK580','ALL_CA','Birch Hills','Birch Hills','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK581','ALL_CA','Gray','Gray','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK582','ALL_CA','White Bear','White Bear','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK583','ALL_CA','Parkbeg','Parkbeg','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK584','ALL_CA','Woodrow','Woodrow','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK585','ALL_CA','Fiske','Fiske','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK586','ALL_CA','Regina Beach','Regina Beach','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK587','ALL_CA','Red Earth','Red Earth','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK588','ALL_CA','Stony Rapids','Stony Rapids','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK589','ALL_CA','Storthoaks','Storthoaks','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK590','ALL_CA','Crane Valley','Crane Valley','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK591','ALL_CA','Vawn','Vawn','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK592','ALL_CA','Tramping Lake','Tramping Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK593','ALL_CA','Penzance','Penzance','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK594','ALL_CA','Tugaske','Tugaske','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK595','ALL_CA','Brock','Brock','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK596','ALL_CA','Creighton','Creighton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK597','ALL_CA','Debden','Debden','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK598','ALL_CA','Denzil','Denzil','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK599','ALL_CA','Drinkwater','Drinkwater','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK600','ALL_CA','Fairy Glen','Fairy Glen','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK601','ALL_CA','Gallivan','Gallivan','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK602','ALL_CA','Jedburgh','Jedburgh','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK603','ALL_CA','Kennedy','Kennedy','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK604','ALL_CA','La Loche','La Loche','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK605','ALL_CA','Lewvan','Lewvan','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK606','ALL_CA','Limerick','Limerick','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK607','ALL_CA','Loverna','Loverna','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK608','ALL_CA','Mortlach','Mortlach','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK609','ALL_CA','Pinehouse Lake','Pinehouse Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK610','ALL_CA','Porcupine Plain','Porcupine Plain','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK611','ALL_CA','Punnichy','Punnichy','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK612','ALL_CA','Rapid View','Rapid View','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK613','ALL_CA','Ruthilda','Ruthilda','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK614','ALL_CA','Saskatoon','Saskatoon','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK615','ALL_CA','Simpson','Simpson','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK616','ALL_CA','Summerberry','Summerberry','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK617','ALL_CA','Turtleford','Turtleford','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK618','ALL_CA','Uranium City','Uranium City','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK619','ALL_CA','West Bend','West Bend','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK620','ALL_CA','Ferland','Ferland','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK621','ALL_CA','Lucky Lake','Lucky Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK622','ALL_CA','Yarbo','Yarbo','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK623','ALL_CA','Stalwart','Stalwart','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK673','ALL_CA','Spruce Home','Spruce Home','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK674','ALL_CA','Kincaid','Kincaid','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK675','ALL_CA','Christopher Lake','Christopher Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK676','ALL_CA','Cole Bay','Cole Bay','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK677','ALL_CA','Abernethy','Abernethy','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK624','ALL_CA','Antler','Antler','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK625','ALL_CA','Mont Nebo','Mont Nebo','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK626','ALL_CA','Dysart','Dysart','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK627','ALL_CA','Duval','Duval','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK628','ALL_CA','Bienfait','Bienfait','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK629','ALL_CA','Willowbrook','Willowbrook','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK630','ALL_CA','Dinsmore','Dinsmore','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK631','ALL_CA','Meskanaw','Meskanaw','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK632','ALL_CA','Colgate','Colgate','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK633','ALL_CA','Stump Lake','Stump Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK634','ALL_CA','Cumberland House','Cumberland House','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK635','ALL_CA','Parry','Parry','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK636','ALL_CA','Manor','Manor','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK637','ALL_CA','Wadena','Wadena','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK638','ALL_CA','Coderre','Coderre','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK639','ALL_CA','Codette','Codette','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK640','ALL_CA','Spalding','Spalding','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK641','ALL_CA','Margo','Margo','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK642','ALL_CA','Wroxton','Wroxton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK643','ALL_CA','Pelly','Pelly','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK644','ALL_CA','Netherhill','Netherhill','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK645','ALL_CA','Emerald Park','Emerald Park','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK646','ALL_CA','Rokeby','Rokeby','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK647','ALL_CA','Smiley','Smiley','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK648','ALL_CA','Warman','Warman','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK649','ALL_CA','Watson','Watson','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK650','ALL_CA','Griffin','Griffin','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK651','ALL_CA','Avonhurst','Avonhurst','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK652','ALL_CA','Beatty','Beatty','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK653','ALL_CA','Truax','Truax','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK654','ALL_CA','Hafford','Hafford','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK655','ALL_CA','Langenburg','Langenburg','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK656','ALL_CA','Preeceville','Preeceville','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK657','ALL_CA','Bright Sand','Bright Sand','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK658','ALL_CA','Carievale','Carievale','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK659','ALL_CA','Candiac','Candiac','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK660','ALL_CA','Denholm','Denholm','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK661','ALL_CA','Stoughton','Stoughton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK662','ALL_CA','Waseca','Waseca','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK663','ALL_CA','Alvena','Alvena','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK664','ALL_CA','Kindersley','Kindersley','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK665','ALL_CA','Lebret','Lebret','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK666','ALL_CA','Delisle','Delisle','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK667','ALL_CA','Val Marie','Val Marie','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK668','ALL_CA','Glenbush','Glenbush','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK669','ALL_CA','Mendham','Mendham','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK670','ALL_CA','White Fox','White Fox','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK671','ALL_CA','Love','Love','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK672','ALL_CA','Glentworth','Glentworth','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK428','ALL_CA','Holbein','Holbein','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK429','ALL_CA','Arelee','Arelee','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK430','ALL_CA','Paynton','Paynton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK431','ALL_CA','Lanigan','Lanigan','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK432','ALL_CA','Barthel','Barthel','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK433','ALL_CA','Bethune','Bethune','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK434','ALL_CA','Birsay','Birsay','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK435','ALL_CA','Black Lake','Black Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK436','ALL_CA','Broadview','Broadview','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK437','ALL_CA','Brockington','Brockington','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK438','ALL_CA','Caronport','Caronport','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK439','ALL_CA','Chitek Lake','Chitek Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK440','ALL_CA','Edam','Edam','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK441','ALL_CA','Ernfold','Ernfold','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK442','ALL_CA','Eston','Eston','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK443','ALL_CA','Frontier','Frontier','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK444','ALL_CA','Killaly','Killaly','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK445','ALL_CA','Marquis','Marquis','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK446','ALL_CA','Pleasantdale','Pleasantdale','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK447','ALL_CA','Shell Lake','Shell Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK448','ALL_CA','Simmie','Simmie','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK449','ALL_CA','Success','Success','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK450','ALL_CA','Tisdale','Tisdale','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK451','ALL_CA','Vibank','Vibank','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK452','ALL_CA','Viceroy','Viceroy','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK453','ALL_CA','Willow Bunch','Willow Bunch','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK454','ALL_CA','Wymark','Wymark','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK455','ALL_CA','Meacham','Meacham','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK456','ALL_CA','Mikado','Mikado','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK457','ALL_CA','Cudworth','Cudworth','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK458','ALL_CA','Biggar','Biggar','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK459','ALL_CA','Melville','Melville','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK460','ALL_CA','Eatonia','Eatonia','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK461','ALL_CA','Oungre','Oungre','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK462','ALL_CA','Golden Prairie','Golden Prairie','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK463','ALL_CA','Lake Lenore','Lake Lenore','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK464','ALL_CA','Churchbridge','Churchbridge','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK465','ALL_CA','North Weyburn','North Weyburn','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK466','ALL_CA','Vidora','Vidora','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK467','ALL_CA','Dafoe','Dafoe','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK468','ALL_CA','Tuxford','Tuxford','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK469','ALL_CA','Big River','Big River','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK470','ALL_CA','Springwater','Springwater','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK471','ALL_CA','Mayfair','Mayfair','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK472','ALL_CA','Clavet','Clavet','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK473','ALL_CA','Hubbard','Hubbard','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK474','ALL_CA','Neudorf','Neudorf','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK475','ALL_CA','Moose Jaw','Moose Jaw','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK476','ALL_CA','Corning','Corning','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK477','ALL_CA','Drake','Drake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK478','ALL_CA','Pathlow','Pathlow','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK479','ALL_CA','Leross','Leross','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK480','ALL_CA','Dundurn','Dundurn','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK481','ALL_CA','Robsart','Robsart','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK482','ALL_CA','Grenfell','Grenfell','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK483','ALL_CA','Waldeck','Waldeck','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK484','ALL_CA','Waldheim','Waldheim','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK485','ALL_CA','Lake Alma','Lake Alma','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK486','ALL_CA','Climax','Climax','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK487','ALL_CA','Langbank','Langbank','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK488','ALL_CA','Fulda','Fulda','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK489','ALL_CA','Hendon','Hendon','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK490','ALL_CA','Prairie River','Prairie River','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK491','ALL_CA','Weldon','Weldon','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK492','ALL_CA','Unity','Unity','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK493','ALL_CA','Leask','Leask','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK494','ALL_CA','Esterhazy','Esterhazy','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK495','ALL_CA','Aylsham','Aylsham','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK496','ALL_CA','Oxbow','Oxbow','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK497','ALL_CA','Glenbain','Glenbain','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK498','ALL_CA','Portreeve','Portreeve','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK499','ALL_CA','St Isidore de Bellevue','St Isidore de Bellevue','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK500','ALL_CA','St Louis','St Louis','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK501','ALL_CA','Moosomin','Moosomin','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK502','ALL_CA','Lloydminster','Lloydminster','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK503','ALL_CA','Hoey','Hoey','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK504','ALL_CA','Fort Qu''Appelle','Fort Qu''Appelle','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK505','ALL_CA','Burstall','Burstall','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK506','ALL_CA','Congress','Congress','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK507','ALL_CA','Cymric','Cymric','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK508','ALL_CA','Davin','Davin','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK509','ALL_CA','Endeavour','Endeavour','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK510','ALL_CA','Flaxcombe','Flaxcombe','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK511','ALL_CA','Furdale','Furdale','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK512','ALL_CA','Kipling','Kipling','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK513','ALL_CA','Leader','Leader','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK514','ALL_CA','Leoville','Leoville','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK515','ALL_CA','Liebenthal','Liebenthal','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK516','ALL_CA','Loon Lake','Loon Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK517','ALL_CA','Madison','Madison','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK518','ALL_CA','Mantario','Mantario','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK519','ALL_CA','Milestone','Milestone','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK520','ALL_CA','Mozart','Mozart','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK521','ALL_CA','Mullingar','Mullingar','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK522','ALL_CA','Patuanak','Patuanak','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK523','ALL_CA','Phippen','Phippen','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK524','ALL_CA','Snowden','Snowden','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK525','ALL_CA','Webb','Webb','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK526','ALL_CA','Hazenmore','Hazenmore','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK527','ALL_CA','Hazlet','Hazlet','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK528','ALL_CA','Stewart Valley','Stewart Valley','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK529','ALL_CA','Prud''Homme','Prud''Homme','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK530','ALL_CA','Coppersands','Coppersands','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK531','ALL_CA','Lintlaw','Lintlaw','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK532','ALL_CA','Ebenezer','Ebenezer','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK533','ALL_CA','Glasnevin','Glasnevin','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK534','ALL_CA','Richlea','Richlea','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK535','ALL_CA','Rush Lake','Rush Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK536','ALL_CA','Allan','Allan','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK537','ALL_CA','Mervin','Mervin','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK538','ALL_CA','Tway','Tway','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK539','ALL_CA','Trossachs','Trossachs','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK540','ALL_CA','Canoe Narrows','Canoe Narrows','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK541','ALL_CA','Rocanville','Rocanville','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK542','ALL_CA','Beaver Creek','Beaver Creek','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK543','ALL_CA','Mankota','Mankota','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK544','ALL_CA','Swift Current','Swift Current','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK545','ALL_CA','Albertville','Albertville','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK546','ALL_CA','D''Arcy Station','D''Arcy Station','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK547','ALL_CA','Admiral','Admiral','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK548','ALL_CA','Livelong','Livelong','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK549','ALL_CA','Cadillac','Cadillac','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK550','ALL_CA','Macklin','Macklin','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK551','ALL_CA','St Brieux','St Brieux','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK552','ALL_CA','Aneroid','Aneroid','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK553','ALL_CA','Naicam','Naicam','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK554','ALL_CA','Green Lake','Green Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK555','ALL_CA','Kelliher','Kelliher','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK556','ALL_CA','Carlyle','Carlyle','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK557','ALL_CA','Ceylon','Ceylon','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK558','ALL_CA','Goodwater','Goodwater','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK559','ALL_CA','Beaubier','Beaubier','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK560','ALL_CA','Pangman','Pangman','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK561','ALL_CA','Neilburg','Neilburg','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK562','ALL_CA','Elstow','Elstow','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK563','ALL_CA','Lang','Lang','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK564','ALL_CA','Ponteix','Ponteix','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK565','ALL_CA','Annaheim','Annaheim','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK566','ALL_CA','Veregin','Veregin','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK567','ALL_CA','Maidstone','Maidstone','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK568','ALL_CA','Cowessess','Cowessess','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK569','ALL_CA','Pilger','Pilger','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK570','ALL_CA','Leslie','Leslie','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK571','ALL_CA','Ardill','Ardill','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK572','ALL_CA','Rockglen','Rockglen','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK573','ALL_CA','Rockhaven','Rockhaven','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK574','ALL_CA','Coronach','Coronach','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK200','ALL_CA','Colfax','Colfax','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK201','ALL_CA','Cardross','Cardross','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK202','ALL_CA','Chaplin','Chaplin','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK203','ALL_CA','Minton','Minton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK204','ALL_CA','Ruddell','Ruddell','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK205','ALL_CA','Dummer','Dummer','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK206','ALL_CA','Sovereign','Sovereign','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK207','ALL_CA','Claybank','Claybank','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK208','ALL_CA','Briercrest','Briercrest','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK209','ALL_CA','Lestock','Lestock','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK210','ALL_CA','Macnutt','Macnutt','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK211','ALL_CA','Kinistino','Kinistino','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK212','ALL_CA','Kinoosao','Kinoosao','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK213','ALL_CA','Smeaton','Smeaton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK214','ALL_CA','Parkside','Parkside','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK215','ALL_CA','Wilcox','Wilcox','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK216','ALL_CA','Loreburn','Loreburn','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK217','ALL_CA','Keeler','Keeler','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK218','ALL_CA','Ogema','Ogema','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK219','ALL_CA','Stony Beach','Stony Beach','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK220','ALL_CA','Lajord','Lajord','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK221','ALL_CA','McCord','McCord','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK222','ALL_CA','Langham','Langham','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK223','ALL_CA','Plenty','Plenty','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK224','ALL_CA','Dollard','Dollard','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK225','ALL_CA','Lacadena','Lacadena','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK226','ALL_CA','Steelman','Steelman','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK227','ALL_CA','Windthorst','Windthorst','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK228','ALL_CA','Pilot Butte','Pilot Butte','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK229','ALL_CA','Spiritwood','Spiritwood','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK230','ALL_CA','Ardath','Ardath','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK231','ALL_CA','Bjorkdale','Bjorkdale','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK232','ALL_CA','Markinch','Markinch','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK233','ALL_CA','Lone Rock','Lone Rock','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK234','ALL_CA','Estevan','Estevan','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK235','ALL_CA','Delmas','Delmas','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK236','ALL_CA','Sturgeon Landing','Sturgeon Landing','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK237','ALL_CA','Glenavon','Glenavon','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK238','ALL_CA','Stenen','Stenen','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK239','ALL_CA','Davidson','Davidson','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK240','ALL_CA','Deer Valley','Deer Valley','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK241','ALL_CA','Kenosee Lake','Kenosee Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK242','ALL_CA','Dubuc','Dubuc','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK243','ALL_CA','Krydor','Krydor','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK244','ALL_CA','Lockwood','Lockwood','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK245','ALL_CA','Medstead','Medstead','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK246','ALL_CA','Glenside','Glenside','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK247','ALL_CA','Sylvania','Sylvania','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK248','ALL_CA','Demaine','Demaine','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK249','ALL_CA','Vanguard','Vanguard','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK250','ALL_CA','Tuffnell','Tuffnell','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK251','ALL_CA','Balcarres','Balcarres','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK252','ALL_CA','Baldwinton','Baldwinton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK253','ALL_CA','Cut Knife','Cut Knife','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK254','ALL_CA','Danbury','Danbury','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK255','ALL_CA','Earl Grey','Earl Grey','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK256','ALL_CA','Edenwold','Edenwold','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK257','ALL_CA','Fillmore','Fillmore','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK258','ALL_CA','Foam Lake','Foam Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK259','ALL_CA','Goodeve','Goodeve','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK260','ALL_CA','Handel','Handel','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK261','ALL_CA','Herbert','Herbert','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK262','ALL_CA','Island Lake','Island Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK263','ALL_CA','La Ronge','La Ronge','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK264','ALL_CA','Lancer','Lancer','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK265','ALL_CA','Lisieux','Lisieux','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK266','ALL_CA','Meadow Lake','Meadow Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK267','ALL_CA','Melfort','Melfort','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK268','ALL_CA','Milden','Milden','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK269','ALL_CA','Mildred','Mildred','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK270','ALL_CA','Muenster','Muenster','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK271','ALL_CA','Chamberlain','Chamberlain','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK272','ALL_CA','Pambrun','Pambrun','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK273','ALL_CA','Primate','Primate','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK274','ALL_CA','Raymore','Raymore','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK275','ALL_CA','Shipman','Shipman','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK276','ALL_CA','Silton','Silton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK277','ALL_CA','Sintaluta','Sintaluta','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK278','ALL_CA','Sonningdale','Sonningdale','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK279','ALL_CA','Tessier','Tessier','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK280','ALL_CA','Vanscoy','Vanscoy','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK281','ALL_CA','Viscount','Viscount','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK282','ALL_CA','Waldron','Waldron','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK283','ALL_CA','Waskesiu Lake','Waskesiu Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK284','ALL_CA','Hague','Hague','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK285','ALL_CA','Hazel Dell','Hazel Dell','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK286','ALL_CA','Indian Head','Indian Head','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK287','ALL_CA','Riceton','Riceton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK288','ALL_CA','Paradise Hill','Paradise Hill','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK289','ALL_CA','Englefeld','Englefeld','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK290','ALL_CA','Nipawin','Nipawin','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK291','ALL_CA','Bredenbury','Bredenbury','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK292','ALL_CA','Macoun','Macoun','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK293','ALL_CA','Strasbourg','Strasbourg','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK294','ALL_CA','Belle Plaine','Belle Plaine','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK295','ALL_CA','Rosthern','Rosthern','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK296','ALL_CA','Edgeley','Edgeley','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK297','ALL_CA','Claydon','Claydon','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK298','ALL_CA','Beechy','Beechy','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK299','ALL_CA','Pelican Narrows','Pelican Narrows','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK300','ALL_CA','Makwa','Makwa','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK301','ALL_CA','Jansen','Jansen','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK302','ALL_CA','St Benedict','St Benedict','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK303','ALL_CA','Colonsay','Colonsay','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK304','ALL_CA','Lac Vert','Lac Vert','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK305','ALL_CA','Yorkton','Yorkton','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK306','ALL_CA','Khedive','Khedive','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK307','ALL_CA','Parkman','Parkman','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK308','ALL_CA','Leroy','Leroy','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK309','ALL_CA','Watrous','Watrous','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK310','ALL_CA','Gravelbourg','Gravelbourg','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK311','ALL_CA','Ridgedale','Ridgedale','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK312','ALL_CA','Avonlea','Avonlea','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK313','ALL_CA','Dodsland','Dodsland','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK314','ALL_CA','Sedley','Sedley','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK315','ALL_CA','Stanley Mission','Stanley Mission','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK316','ALL_CA','Bellegarde','Bellegarde','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK317','ALL_CA','Hawarden','Hawarden','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK318','ALL_CA','North Battleford','North Battleford','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK319','ALL_CA','Norquay','Norquay','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK320','ALL_CA','Dorintosh','Dorintosh','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK321','ALL_CA','Eyebrow','Eyebrow','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK322','ALL_CA','Prairie View','Prairie View','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK323','ALL_CA','Bromhead','Bromhead','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK324','ALL_CA','Rosetown','Rosetown','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK325','ALL_CA','Manitou Beach','Manitou Beach','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK326','ALL_CA','Ormiston','Ormiston','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK327','ALL_CA','Stockholm','Stockholm','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK328','ALL_CA','Osler','Osler','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK329','ALL_CA','Air Ronge','Air Ronge','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK330','ALL_CA','Maple Creek','Maple Creek','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK331','ALL_CA','Duperow','Duperow','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK332','ALL_CA','Guernsey','Guernsey','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK333','ALL_CA','Aylesbury','Aylesbury','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK334','ALL_CA','Bracken','Bracken','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK335','ALL_CA','Sturgis','Sturgis','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK336','ALL_CA','Consul','Consul','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK337','ALL_CA','Duck Lake','Duck Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK338','ALL_CA','Bankend','Bankend','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK339','ALL_CA','Spring Valley','Spring Valley','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK340','ALL_CA','Clair','Clair','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK341','ALL_CA','Perdue','Perdue','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK342','ALL_CA','Spy Hill','Spy Hill','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK343','ALL_CA','Abbey','Abbey','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK344','ALL_CA','Alameda','Alameda','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK345','ALL_CA','Archerwill','Archerwill','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK346','ALL_CA','Blumenhof','Blumenhof','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK53','ALL_CA','Welwyn','Welwyn','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK54','ALL_CA','Kuroki','Kuroki','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK55','ALL_CA','Kylemore','Kylemore','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK56','ALL_CA','Kelfield','Kelfield','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK57','ALL_CA','Arran','Arran','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK58','ALL_CA','Laird','Laird','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK59','ALL_CA','Rhein','Rhein','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK60','ALL_CA','Kayville','Kayville','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK61','ALL_CA','Major','Major','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK62','ALL_CA','Lampman','Lampman','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK63','ALL_CA','Montmartre','Montmartre','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK64','ALL_CA','Meyronne','Meyronne','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK65','ALL_CA','Lashburn','Lashburn','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK66','ALL_CA','Prelate','Prelate','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK67','ALL_CA','Richardson','Richardson','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK68','ALL_CA','Deschambault Lake','Deschambault Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK69','ALL_CA','St Denis','St Denis','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK70','ALL_CA','Palmer','Palmer','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK71','ALL_CA','Hanley','Hanley','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK72','ALL_CA','Mistatim','Mistatim','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK73','ALL_CA','Theodore','Theodore','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK74','ALL_CA','White City','White City','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK75','ALL_CA','Flintoft','Flintoft','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK76','ALL_CA','Cando','Cando','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK77','ALL_CA','Francis','Francis','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK78','ALL_CA','Bruno','Bruno','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK79','ALL_CA','Bangor','Bangor','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK80','ALL_CA','Alticane','Alticane','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK81','ALL_CA','Stornoway','Stornoway','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK82','ALL_CA','Denare Beach','Denare Beach','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK83','ALL_CA','Whitecap','Whitecap','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK84','ALL_CA','Kelvington','Kelvington','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK85','ALL_CA','Aberdeen','Aberdeen','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK86','ALL_CA','Assiniboia','Assiniboia','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK87','ALL_CA','Atwater','Atwater','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK88','ALL_CA','Balgonie','Balgonie','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK89','ALL_CA','Buena Vista','Buena Vista','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK90','ALL_CA','Buffalo Narrows','Buffalo Narrows','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK91','ALL_CA','Bulyea','Bulyea','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK92','ALL_CA','Cactus Lake','Cactus Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK93','ALL_CA','Carnduff','Carnduff','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK94','ALL_CA','Creelman','Creelman','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK95','ALL_CA','Duff','Duff','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK96','ALL_CA','Elbow','Elbow','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK97','ALL_CA','Fife Lake','Fife Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK98','ALL_CA','Forget','Forget','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK99','ALL_CA','Prince Albert','Prince Albert','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK100','ALL_CA','Glen Ewen','Glen Ewen','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK101','ALL_CA','Harris','Harris','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK102','ALL_CA','Hearne','Hearne','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK103','ALL_CA','Heward','Heward','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK104','ALL_CA','Hoosier','Hoosier','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK105','ALL_CA','Kenaston','Kenaston','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK106','ALL_CA','Landis','Landis','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK107','ALL_CA','Liberty','Liberty','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK108','ALL_CA','Lumsden','Lumsden','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK109','ALL_CA','Mayview','Mayview','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK110','ALL_CA','Mazenod','Mazenod','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK111','ALL_CA','Midale','Midale','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK112','ALL_CA','Neville','Neville','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK113','ALL_CA','Reward','Reward','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK114','ALL_CA','Shamrock','Shamrock','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK115','ALL_CA','Whelan','Whelan','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK116','ALL_CA','Zealandia','Zealandia','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK117','ALL_CA','Zehner','Zehner','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK118','ALL_CA','Fertile','Fertile','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK119','ALL_CA','Hagen','Hagen','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK120','ALL_CA','Yellow Grass','Yellow Grass','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK121','ALL_CA','Yellow Quill','Yellow Quill','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK122','ALL_CA','Wood Mountain','Wood Mountain','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK123','ALL_CA','Benson','Benson','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK124','ALL_CA','Kisbey','Kisbey','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK125','ALL_CA','Glaslyn','Glaslyn','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK126','ALL_CA','Gladmar','Gladmar','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK127','ALL_CA','Corman Park','Corman Park','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK128','ALL_CA','Borden','Borden','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK129','ALL_CA','Stranraer','Stranraer','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK130','ALL_CA','Weyburn','Weyburn','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK131','ALL_CA','Martensville','Martensville','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK132','ALL_CA','Strongfield','Strongfield','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK133','ALL_CA','Maymont','Maymont','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK134','ALL_CA','Wishart','Wishart','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK135','ALL_CA','Kinley','Kinley','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK136','ALL_CA','Kyle','Kyle','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK137','ALL_CA','Zenon Park','Zenon Park','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK138','ALL_CA','Saltcoats','Saltcoats','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK139','ALL_CA','Shaunavon','Shaunavon','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK140','ALL_CA','Star City','Star City','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK141','ALL_CA','Arborfield','Arborfield','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK142','ALL_CA','Wauchope','Wauchope','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK143','ALL_CA','McLean','McLean','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK144','ALL_CA','Tribune','Tribune','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK145','ALL_CA','Plato','Plato','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK146','ALL_CA','McMahon','McMahon','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK147','ALL_CA','Fosston','Fosston','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK148','ALL_CA','Montreal Lake','Montreal Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK149','ALL_CA','Qu''Appelle','Qu''Appelle','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK150','ALL_CA','Sheho','Sheho','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK151','ALL_CA','McTaggart','McTaggart','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK152','ALL_CA','Brownlee','Brownlee','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK153','ALL_CA','Insinger','Insinger','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK154','ALL_CA','Gerald','Gerald','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK155','ALL_CA','Gull Lake','Gull Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK156','ALL_CA','Grayson','Grayson','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK157','ALL_CA','Garrick','Garrick','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK158','ALL_CA','Humboldt','Humboldt','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK159','ALL_CA','Conquest','Conquest','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK160','ALL_CA','Marcelin','Marcelin','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK161','ALL_CA','Young','Young','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK162','ALL_CA','Kronau','Kronau','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK163','ALL_CA','Alsask','Alsask','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK164','ALL_CA','Hodgeville','Hodgeville','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK165','ALL_CA','Brooksby','Brooksby','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK166','ALL_CA','Okla','Okla','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK167','ALL_CA','Kamsack','Kamsack','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK168','ALL_CA','Spruce Lake','Spruce Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK169','ALL_CA','Arcola','Arcola','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK170','ALL_CA','Asquith','Asquith','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK171','ALL_CA','Cabri','Cabri','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK172','ALL_CA','Calder','Calder','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK173','ALL_CA','Caron','Caron','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK174','ALL_CA','Chelan','Chelan','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK175','ALL_CA','Choiceland','Choiceland','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK176','ALL_CA','Eagle Ridge','Eagle Ridge','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK177','ALL_CA','Frenchman Butte','Frenchman Butte','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK178','ALL_CA','Hepburn','Hepburn','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK179','ALL_CA','Holdfast','Holdfast','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK180','ALL_CA','Hudson Bay','Hudson Bay','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK181','ALL_CA','Jackfish Lake','Jackfish Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK182','ALL_CA','Muskoday','Muskoday','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK183','ALL_CA','Lafleche','Lafleche','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK184','ALL_CA','Marshall','Marshall','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK185','ALL_CA','Odessa','Odessa','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK186','ALL_CA','Peebles','Peebles','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK187','ALL_CA','Piapot','Piapot','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK188','ALL_CA','Radisson','Radisson','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK189','ALL_CA','Rama','Rama','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK190','ALL_CA','Shellbrook','Shellbrook','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK191','ALL_CA','Turnor Lake','Turnor Lake','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK192','ALL_CA','Timber Bay','Timber Bay','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK193','ALL_CA','Whitewood','Whitewood','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK194','ALL_CA','Gainsborough','Gainsborough','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK195','ALL_CA','Rouleau','Rouleau','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK196','ALL_CA','Macrorie','Macrorie','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK197','ALL_CA','Dilke','Dilke','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('SK198','ALL_CA','Dillon','Dillon','SK','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0);
commit;
