insert into YFS_REGION (REGION_KEY,REGION_SCHEMA_KEY,REGION_NAME,REGION_DESCRIPTION,PARENT_REGION_KEY,REGION_LEVEL_NAME,CAN_AGGREGATE,CREATEUSERID, MODIFYUSERID, CREATEPROGID, MODIFYPROGID, LOCKID) VALUES
('YT','ALL_CA','YT','YT','CAN','State','Y','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT1','ALL_CA','Teslin','Teslin','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT2','ALL_CA','Carmacks','Carmacks','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT3','ALL_CA','Tagish','Tagish','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT4','ALL_CA','Old Crow','Old Crow','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT5','ALL_CA','Marsh Lake','Marsh Lake','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT6','ALL_CA','Whitehorse','Whitehorse','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT7','ALL_CA','Mayo','Mayo','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT8','ALL_CA','Dawson','Dawson','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT9','ALL_CA','Ross River','Ross River','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT10','ALL_CA','Faro','Faro','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT11','ALL_CA','Elsa','Elsa','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT12','ALL_CA','Pelly Crossing','Pelly Crossing','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT13','ALL_CA','Watson Lake','Watson Lake','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT14','ALL_CA','Destruction Bay','Destruction Bay','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT15','ALL_CA','Haines Junction','Haines Junction','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT16','ALL_CA','Carcross','Carcross','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT17','ALL_CA','Beaver Creek','Beaver Creek','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0),
('YT18','ALL_CA','Burwash Landing','Burwash Landing','YT','City','N','SYSTEM','SYSTEM','SYSTEM','SYSTEM',0);
commit;