
##CROCS MQ property
yfs.AGENT_QCF=AGENT_QCF
yfs.PROVIDER_URL=file:///opt/ssfs/jndi

#CROCS  Sprint 1 related queues

yfs.CROCS_IN_CREATE_ORDER_QUEUE = CROCS_IN_CREATE_ORDER_QUEUE
yfs.CROCS_INT_CATALOG_INDEX_QUEUE = CROCS_INT_CATALOG_INDEX_QUEUE
yfs.CROCS_IN_REMORSE_HOLD_QUEUE = CROCS_IN_REMORSE_HOLD_QUEUE
yfs.CROCS_IN_ITEM_FEED_QUEUE = CROCS_IN_ITEM_FEED_QUEUE
yfs.CROCS_IN_DUPLICATE_ORDER_QUEUE =CROCS_IN_DUPLICATE_ORDER_QUEUE




##EOMS-1009 Item sync to IV
yfs.CROCS_INT_ITEM_DTLS_IV_SYNC_QUEUE = CROCS_INT_ITEM_DTLS_IV_SYNC_QUEUE

##EOMS-555 Store Queues
yfs.CROCS_IN_CREATE_STORE_ORG_QUEUE = CROCS_IN_CREATE_STORE_ORG_QUEUE
yfs.CROCS_INT_POST_CREATE_STORE_ORG_MSG_TO_IV = CROCS_INT_POST_CREATE_STORE_ORG_MSG_TO_IV

#EOMS-598 Send SFCC Notification
yfs.CROCS_OUT_CREATE_ORD_MSG_QUEUE = CROCS_OUT_CREATE_ORD_MSG_QUEUE

#EOMS-608 Cancel Order Notification
yfs.CROCS_OUT_CANCEL_ORD_MSG_QUEUE = CROCS_OUT_CANCEL_ORD_MSG_QUEUE
yfs.CROCS_INT_UPDATE_ORD_DTLS_QUEUE = CROCS_INT_UPDATE_ORD_DTLS_QUEUE


#CROCS DATA EXTRACTION
yfs.CROCS_DATA_EXTRACTION_QUEUE = CROCS_DATA_EXTRACTION_QUEUE

#EOMS-690 Send OrderPriority No to WMS
yfs.CROCS_OUT_SHIPMENT_RELEASE_MSG_QUEUE = CROCS_OUT_SHIPMENT_RELEASE_MSG_QUEUE

#EOMS-721 OMS Invoice Creation
yfs.CROCS_INT_SHIPMENT_INVOICE_QUEUE = CROCS_INT_SHIPMENT_INVOICE_QUEUE

#EOMS-560 OMS Invoice Creation
yfs.CROCS_IN_SUPPLY_FEED_QUEUE = CROCS_IN_SUPPLY_FEED_QUEUE

#EOMS-656 Adyen Webhooks Async
yfs.CROCS_IN_ADYEN_WEBHOOKS_QUEUE = CROCS_IN_ADYEN_WEBHOOKS_QUEUE

#EOMS-662 : Givex - Refund Process flow in OMS
yfs.CROCS_INT_RFO_PROCESS_QUEUE = CROCS_INT_RFO_PROCESS_QUEUE

#EOMS-538 : Givex - Refund Process flow in OMS
yfs.CROCS_IN_SHIPMENT_MONITOR_QUEUE = CROCS_IN_SHIPMENT_MONITOR_QUEUE

#EOMS-538 : Givex - Refund Process flow in OMS
yfs.CROCS_IN_SHIPMENT_UPDATE_MSG_QUEUE = CROCS_IN_SHIPMENT_UPDATE_MSG_QUEUE


#EOMS-648 Payment queues
yfs.CROCS_INT_PAYMENT_COLLECTION_QUEUE=CROCS_INT_PAYMENT_COLLECTION_QUEUE
yfs.CROCS_INT_PAYMENT_EXECUTE_QUEUE=CROCS_INT_PAYMENT_EXECUTE_QUEUE

#EOMS- 1903 Inbox Purge queues
yfs.CROCS_INT_INBOX_PURGE_QUEUE=CROCS_INT_INBOX_PURGE_QUEUE

#EOMS-2015 : Configure schedule & release agents
yfs.CROCS_INT_SCHEDULE_ORD_QUEUE=CROCS_INT_SCHEDULE_ORD_QUEUE
yfs.CROCS_INT_RELEASE_ORD_QUEUE=CROCS_INT_RELEASE_ORD_QUEUE

#EOMS-744 Return order details from OMS to WMS 
yfs.CROCS_OUT_CREATE_RETURN_QUEUE = CROCS_OUT_CREATE_RETURN_QUEUE

#EOMS-2025 Auth Reversal on Full Order Cancel 
yfs.CROCS_INT_AUTH_VOID_QUEUE = CROCS_INT_AUTH_VOID_QUEUE

#EOMS-698 Shipment Confirmation From WMS
yfs.CROCS_IN_SHIPMENT_CONFIRM_MSG_QUEUE = CROCS_IN_SHIPMENT_CONFIRM_MSG_QUEUE

#EOMS-747 Return Receipt Receive From WMS
yfs.CROCS_IN_RECEIVE_RETURN_QUEUE = CROCS_IN_RECEIVE_RETURN_QUEUE

#EOMS-768 Send Invoice To SAP
yfs.CROCS_OUT_SEND_INVOICE_MSG_QUEUE = CROCS_OUT_SEND_INVOICE_MSG_QUEUE
yfs.CROCS_INT_SEND_INVOICE_QUEUE = CROCS_INT_SEND_INVOICE_QUEUE

#EOMS-1492 Narvar Create Order Implementation
yfs.CROCS_IN_CREATE_NARVAR_RO_QUEUE = CROCS_IN_CREATE_NARVAR_RO_QUEUE

#EOMS-602 Confirm Shipment Notification To SFCC
yfs.CROCS_OUT_SHIP_CONFIRM_MSG_QUEUE = CROCS_OUT_SHIP_CONFIRM_MSG_QUEUE

#Enable Loggind
yfs.log4j2.customPackages=com.crocs

#EOMS-1514 Return Order Migration
yfs.CROCS_INT_PURGE_RETURN_QUEUE = CROCS_INT_PURGE_RETURN_QUEUE

#EOMS-1511 Sales Order Migration
yfs.CROCS_INT_SALES_ORDER_PURGE_QUEUE = CROCS_INT_SALES_ORDER_PURGE_QUEUE
yfs.CROCS_IN_IMPORT_SALES_ORDER_QUEUE = CROCS_IN_IMPORT_SALES_ORDER_QUEUE
yfs.CROCS_INT_IMPORT_SO_SHIPMENT_ORDER_QUEUE = CROCS_INT_IMPORT_SO_SHIPMENT_ORDER_QUEUE

#EOMS-1495 APTOS Return
yfs.CROCS_IN_CREATE_POS_RETURN_QUEUE = CROCS_IN_CREATE_POS_RETURN_QUEUE
yfs.CROCS_INT_PAYMENT_COLLECTION_RETURN_QUEUE = CROCS_INT_PAYMENT_COLLECTION_RETURN_QUEUE
yfs.CROCS_INT_PAYMENT_EXECUTE_RETURN_QUEUE = CROCS_INT_PAYMENT_EXECUTE_RETURN_QUEUE

#EOMS-1514 Return Order Migration
yfs.CROCS_IN_RETURN_MIGRATION_QUEUE = CROCS_IN_RETURN_MIGRATION_QUEUE

#EOMS-1488 Publish Update to Aptos - Implementation
yfs.CROCS_OUT_UPDATE_TO_POS_QUEUE = CROCS_OUT_UPDATE_TO_POS_QUEUE

#Return Order Invoice Creation
yfs.CROCS_INT_RETURN_ORDER_INVOICE_QUEUE = CROCS_INT_RETURN_ORDER_INVOICE_QUEUE
#Publish Return Invoice to SAP
yfs.CROCS_OUT_RETURN_ORDER_INVOICE_QUEUE =CROCS_OUT_SEND_RETURN_INVOICE_MSG_QUEUE

#Publish Invoice to SAP
yfs.CROCS_OUT_CREATE_INVOICE_QUEUE =CROCS_OUT_CREATE_INVOICE_QUEUE

#GDPR properties
yfs.gdpr.enabled =Y
yfs.CROCS_IN_GDPR_MANAGE_REQUEST_QUEUE =CROCS_IN_GDPR_MANAGE_REQUEST_QUEUE
yfs.YFS_PERSON_INFO.personalinfoattributes=AddressLine1,EMailID,FirstName,LastName,MobilePhone,DayPhone
yfs.YFS_CUSTOMER_CONTACT.personalinfoattributes=DayPhone,FirstName,EmailID,LastName,MobilePhone
yfs.YFS_ORDER_HEADER.personalinfoattributes=CustomerFirstName,CustomerLastName,CustomerPhoneNo,CustomerEMailID
yfs.YFS_PAYMENT.personalinfoattributes=FirstName,LastName

#EOMS -3346 Send Return Confirmation Notification
yfs.CROCS_OUT_REFUND_CONFIRM_MSG_QUEUE=CROCS_OUT_REFUND_CONFIRM_MSG_QUEUE

#EOMS-1485 Return Order update to Forter
yfs.CROCS_INT_FORTER_ORDER_UPDATE_QUEUE=CROCS_INT_FORTER_ORDER_UPDATE_QUEUE

#Close Order Related
yfs.CROCS_INT_CLOSE_ORDER_QUEUE=CROCS_INT_CLOSE_ORDER_QUEUE
yfs.CROCS_INT_CLOSE_SHIPMENT_QUEUE=CROCS_INT_CLOSE_SHIPMENT_QUEUE

# NOTE: This property is commented out because, after the latest release, it causes issues during JAR build.
# It is recommended to update this property via SMA rather than directly modifying the COP file.
# Resolved Issue Link: https://www.ibm.com/docs/en/order-management?topic=updating-resolved-issues
#Invoice_Complete parameter for canceled lines is set as Y and if order is completely invoiced it allows creation of debit memo in the system.
#yfs.yfs.suppressModTypeValidationForCancelledOrders=Y

# EOMS-734 Narvar Return Label Generation Queue
yfs.CROCS_INT_NARVAR_RETURN_LABEL_QUEUE=CROCS_INT_NARVAR_RETURN_LABEL_QUEUE

#EOMS-3877
yfs.CROCS_INT_ADYEN_WEBHOOK_PROCESSING_QUEUE = CROCS_INT_ADYEN_WEBHOOK_PROCESSING_QUEUE
# Order Acknowledgment TO SFCC
yfs.CROCS_OUT_ORD_ACK_MSG_QUEUE=CROCS_OUT_ORD_ACK_MSG_QUEUE

#EOMS-3896 Vertex create exception queue
yfs.CROCS_INT_VERTEX_CREATE_EXP_QUEUE=CROCS_INT_VERTEX_CREATE_EXP_QUEUE

#EOMS-4257 Shipment OS Message for Narvar will be posted to Q for Async Service to Pick and process further. 
yfs.CROCS_INT_SHIPPED_NARVAR_UPDATE_QUEUE=CROCS_INT_SHIPPED_NARVAR_UPDATE_QUEUE

#EOMS-4270 Vertex Invoice Tax Posting Queue
yfs.CROCS_INT_VERTEX_INVOICE_QUEUE=CROCS_INT_VERTEX_INVOICE_QUEUE

#EOMS-4625: Move invoice publish from creation to collection.
yfs.CROCS_INT_PUBLISH_INVOICE_TO_SAP_QUEUE = CROCS_INT_PUBLISH_INVOICE_TO_SAP_QUEUE

#EOMS-4431: Canceling Return line which are in Created status
yfs.CROCS_INT_RETURN_MONITOR_QUEUE = CROCS_INT_RETURN_MONITOR_QUEUE 
#EOMS-4470
yfs.CROCS_INT_CONFIRM_SHIPMENT_EMAIL_QUEUE=CROCS_INT_CONFIRM_SHIPMENT_EMAIL_QUEUE
yfs.CROCS_INT_APTOS_ORDER_UPDATE_QUEUE=CROCS_INT_APTOS_ORDER_UPDATE_QUEUE
#EOMS-3695
yfs.CROCS_IN_SAP_INVOICE_ACK_UPDATE_QUEUE=CROCS_IN_SAP_INVOICE_ACK_UPDATE_QUEUE

#EOMS-4677 : Inventory OnHand Supply delta sync feed
yfs.CROCS_IN_DELTA_SUPPLY_FEED_QUEUE = CROCS_IN_DELTA_SUPPLY_FEED_QUEUE

#EOMS-4866, EOMS-4851, EOMS-4863, EOMS-4865, EOMS-737 and EOMS-738
yfs.CROCS_IN_SHIPMENT_CONFIRM_UPS_QUEUE = CROCS_IN_SHIPMENT_CONFIRM_UPS_QUEUE
yfs.CROCS_OUT_SHIPMENT_RELEASE_UPS_QUEUE = CROCS_OUT_SHIPMENT_RELEASE_UPS_QUEUE
yfs.CROCS_IN_SHIPMENT_UPDATE_UPS_QUEUE = CROCS_IN_SHIPMENT_UPDATE_UPS_QUEUE
yfs.CROCS_IN_RECEIVE_RETURN_UPS_QUEUE = CROCS_IN_RECEIVE_RETURN_UPS_QUEUE
yfs.CROCS_OUT_CREATE_RETURN_UPS_QUEUE = CROCS_OUT_CREATE_RETURN_UPS_QUEUE

#EOMS-735 Narvar return label internal queue for CA
yfs.CROCS_CA_INT_NARVAR_RETURN_LABEL_QUEUE=CROCS_CA_INT_NARVAR_RETURN_LABEL_QUEUE
#Crocs CA create order queue
yfs.CROCS_IN_CREATE_ORDER_CA_QUEUE=CROCS_IN_CREATE_ORDER_CA_QUEUE
# Internal Queue for CA Shipment Confirmation Email
yfs.CROCS_CA_INT_CONFIRM_SHIPMENT_EMAIL_QUEUE=CROCS_CA_INT_CONFIRM_SHIPMENT_EMAIL_QUEUE

# MarketPlace SO and RO Queues 
yfs.CROCS_IN_CREATE_MP_ORDER_QUEUE = CROCS_IN_CREATE_MP_ORDER_QUEUE
yfs.CROCS_IN_CREATE_MP_RETURN_QUEUE = CROCS_IN_CREATE_MP_RETURN_QUEUE

#EOMS-5547 Status Queues
yfs.CROCS_INT_ORDER_STATUS_UPD_QUEUE = CROCS_INT_ORDER_STATUS_UPD_QUEUE
yfs.CROCS_OUT_ORDER_STATUS_UPD_QUEUE = CROCS_OUT_ORDER_STATUS_UPD_QUEUE

#EOMS-5887 Queue for processing async request
yfs.CROCS_INT_PROCESS_ASYNC_REQUEST_QUEUE = CROCS_INT_PROCESS_ASYNC_REQUEST_QUEUE

#--------------------------------------------------------------------------------------------
# Cache Properties
#--------------------------------------------------------------------------------------------
dbclassCache.YFS_ITEM.enabled=false
dbclassCache.YFS_ITEM_ALIAS.enabled=false
dbclassCache.YFS_ITEM_UOM.enabled=false
dbclassCache.YFS_ITEM_INSTRUCTION.enabled=false
dbclassCache.YFS_ADDITIONAL_ATTRIBUTE=false
dbclassCache.YFS_ITEM_LOCALE=false
dbclassCache.YFS_LANGUAGE_DESCRIPTION=false
dbclassCache.YFS_CATEGORY=false
dbclassCache.YFS_USER.enabled=false
dbclassCache.YFS_SEARCH_INDEX.enabled=false
dbclassCache.YFS_SEARCH_INDEX_TRIGGER.enabled=false
dbclassCache.YFS_SEARCH_INDEX_PROCESS.enabled=false
dbclassCache.YFS_SEARCH_INDEX_FACET.enabled=false
dbclassCache.YFS_CUSTOMER.enabled=false
dbclassCache.YFS_CUSTOMER_CONTACT.enabled=false
dbclassCache.YFS_CUSTOMER_ADDNL_ADDRESS.enabled=false

#Transfer Order 
yfs.CROCS_IN_RETAIL_CREATE_ORDER_QUEUE =CROCS_IN_RETAIL_CREATE_ORDER_QUEUE
yfs.CROCS_INT_RETAIL_SCHEDULE_ORDER_QUEUE=CROCS_INT_RETAIL_SCHEDULE_ORDER_QUEUE
yfs.CROCS_INT_RETAIL_RELEASE_ORDER_QUEUE=CROCS_INT_RETAIL_RELEASE_ORDER_QUEUE
yfs.CROCS_IN_RETAIL_ITEM_FEED_QUEUE=CROCS_IN_RETAIL_ITEM_FEED_QUEUE
#EOMS-14029 INT QUEUE FOR APAC,EMEA SCHEDULER
yfs.CROCS_INT_RETAIL_APAC_SCHEDULE_ORDER_QUEUE=CROCS_INT_RETAIL_APAC_SCHEDULE_ORDER_QUEUE
yfs.CROCS_INT_RETAIL_EMEA_SCHEDULE_ORDER_QUEUE=CROCS_INT_RETAIL_EMEA_SCHEDULE_ORDER_QUEUE

#Export Purge
yfs.CROCS_INT_EXPORT_PURGE_QUEUE =CROCS_INT_EXPORT_PURGE_QUEUE
yfs.CROCS_INT_REPROCESS_ERROR_QUEUE =CROCS_INT_REPROCESS_ERROR_QUEUE

#HeyDude Queues
yfs.NA_3PL_FULFILLMENT_ORDER_OUT =NA_3PL_FULFILLMENT_ORDER_OUT
yfs.NA_3PL_SHIP_CONFIRM_IN =NA_3PL_SHIP_CONFIRM_IN
yfs.NA_3PL_RETURN_RECEIPT_IN =NA_3PL_RETURN_RECEIPT_IN
yfs.NA_3PL_RETURN_ORDER_OUT =NA_3PL_RETURN_ORDER_OUT

#EOMS-6076 HeyDude US,CA and AU create order queues
yfs.HEYDUDE_IN_CREATE_ORDER_US_QUEUE = HEYDUDE_IN_CREATE_ORDER_US_QUEUE
yfs.HEYDUDE_IN_CREATE_ORDER_CA_QUEUE = HEYDUDE_IN_CREATE_ORDER_CA_QUEUE
yfs.HEYDUDE_IN_CREATE_ORDER_AU_QUEUE = HEYDUDE_IN_CREATE_ORDER_AU_QUEUE

#EOMS-6163 HeyDude Invoice queue
yfs.HD_OUT_CREATE_INVOICE_QUEUE = HD_OUT_CREATE_INVOICE_QUEUE

#EOMS-7161 HeyDude GLOBALE Return Order QUEUE
yfs.HEYDUDE_IN_GLOBALE_CREATE_RO_QUEUE = HEYDUDE_IN_GLOBALE_CREATE_RO_QUEUE

#EOMS-6121 HeyDude Migration Queues
yfs.HEYDUDE_IN_ORDER_MIGRATION_QUEUE = HEYDUDE_IN_ORDER_MIGRATION_QUEUE
yfs.HEYDUDE_IN_RETURN_MIGRATION_QUEUE = HEYDUDE_IN_RETURN_MIGRATION_QUEUE
yfs.HEYDUDE_INT_IMPORT_SHIPMENT_QUEUE = HEYDUDE_INT_IMPORT_SHIPMENT_QUEUE
#EOMS-8528 CROCS AU CREATE ORDER QUEUE
yfs.CROCS_AU_IN_CREATE_ORDER_QUEUE = CROCS_AU_IN_CREATE_ORDER_QUEUE

#EOMS - 8586 Queue for SAP Organization Feed
yfs.CROCS_IN_SAP_CREATE_STORE_ORG_QUEUE = CROCS_IN_SAP_CREATE_STORE_ORG_QUEUE


#EOMS-6963- LVDC Release Queue
yfs.CROCS_OUT_NV_SHIPMENT_RELEASE_QUEUE = CROCS_OUT_NV_SHIPMENT_RELEASE_QUEUE

#Crocs AU Release Outbound Queue
yfs.APAC_3PL_FULFILLMENT_ORDER_OUT = APAC_3PL_FULFILLMENT_ORDER_OUT

#Crocs AU Shipment Update Queue
yfs.APAC_3PL_SHP_UPDATE_IN = APAC_3PL_SHP_UPDATE_IN

# Crocs AU Shipment Confirmation Queue
yfs.APAC_3PL_SHP_CONFIRM_IN = APAC_3PL_SHP_CONFIRM_IN

# Crocs AU Return Update to Maersk 3PL Queue
yfs.APAC_3PL_RETURN_ORDER_OUT = APAC_3PL_RETURN_ORDER_OUT

# Crocs AU Return receipt Queue
yfs.APAC_3PL_RETURN_RECEIPT_IN = APAC_3PL_RETURN_RECEIPT_IN

# EOMS 6966 Outbound queue to send Return Order from OMS to WMS
yfs.CROCS_OUT_NV_CREATE_RETURN_QUEUE = CROCS_OUT_NV_CREATE_RETURN_QUEUE

#EOMS-11110: CROCS SG Create Order Queue
yfs.CROCS_SG_IN_CREATE_ORDER_QUEUE = CROCS_SG_IN_CREATE_ORDER_QUEUE

#EOMS-9713 EMEA Create Order Queues
yfs.CROCS_EMEA_HD_IN_CREATE_ORDER_QUEUE = CROCS_EMEA_HD_IN_CREATE_ORDER_QUEUE
yfs.CROCS_EMEA_IN_CREATE_ORDER_QUEUE = CROCS_EMEA_IN_CREATE_ORDER_QUEUE

#EOMS-10347 EMEA Send ReleaseOrder Outbound Queue
yfs.CROCS_OUT_NL_SHIPMENT_RELEASE_QUEUE= CROCS_OUT_NL_SHIPMENT_RELEASE_QUEUE

#EOMS-12143 EMEA Publish return order details to NLDC Outbound Queue
yfs.CROCS_OUT_NL_CREATE_RETURN_QUEUE = CROCS_OUT_NL_CREATE_RETURN_QUEUE

#EOMS-11371 CROCS_KR | OMS| Create Order for Crocs KR - implementation
yfs.CROCS_KR_IN_CREATE_ORDER_QUEUE=CROCS_KR_IN_CREATE_ORDER_QUEUE
 
