name: OMS Preprod Pipeline

  on:
    workflow_dispatch:

  jobs:
    build:
      runs-on: self-hosted

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v5

        - name: Verify Environment
          run: |
            echo "Current Directory:"
            pwd
            echo ""
            echo "Repository Files:"
            ls -la
            echo ""
            echo "Java Version:"
            java -version

        - name: Build Extension JAR
          run: |
            cd /home/nayeem501/oms/devtoolkit_docker
            ./sci_ant.sh -f ../devtoolkit/devtoolkit_extensions.xml importfromproject -Dprojectdir=${{ github.workspace }}/sourcecode
