name: My First Workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello Nayeem! Welcome to GitHub Actions."

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la
